/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createEndpointFactory, type BinaryUpload, type HttpResult, type RequestOptions, type StatusRange } from "@accord/client";
import { z } from "zod";
type AccordSimplify<T> = T extends unknown ? {
    [K in keyof T]: T[K];
} : never;
type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T;
type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T;
export type Problem = {
    readonly "code": string;
    readonly "message": string;
};
export type ProblemRequest = {
    readonly "code": string;
    readonly "message": string;
};
export type Task = {
    readonly "createdAt": string;
    readonly "id": string;
    readonly "labels"?: {
        readonly [key: string]: string;
    };
    readonly "status": ("open" | "done") & string;
    readonly "title": string;
};
export type TaskRequest = {
    readonly "createdAt"?: never;
    readonly "id"?: never;
    readonly "labels"?: {
        readonly [key: string]: string;
    };
    readonly "status": ("open" | "done") & string;
    readonly "title": string;
};
export type ListInput = {
    readonly "status"?: ("open" | "done") & string;
    readonly "limit"?: number;
};
export type ListArguments = [
    input?: {
        readonly "status"?: ("open" | "done") & string;
        readonly "limit"?: number;
    },
    options?: RequestOptions
];
export type ListResponse = {
    readonly "items": ReadonlyArray<Task>;
    readonly "nextCursor"?: string;
};
export type ListError = never;
export type ListResponses = {
    readonly "200": {
        readonly "items": ReadonlyArray<Task>;
        readonly "nextCursor"?: string;
    };
};
export type ListFullResponse = HttpResult<200, {
    readonly "items": ReadonlyArray<Task>;
    readonly "nextCursor"?: string;
}>;
export type ListContract = {
    readonly "args": ListArguments;
    readonly "input": ListInput;
    readonly "response": ListResponse;
    readonly "error": ListError;
    readonly "responses": ListResponses;
    readonly "fullResponse": ListFullResponse;
};
export type CreateInput = TaskRequest;
export type CreateArguments = [
    input: TaskRequest,
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type CreateResponse = Task;
export type CreateError = Problem;
export type CreateResponses = {
    readonly "201": Task;
    readonly "422": Problem;
};
export type CreateFullResponse = HttpResult<201, Task>;
export type CreateContract = {
    readonly "args": CreateArguments;
    readonly "input": CreateInput;
    readonly "response": CreateResponse;
    readonly "error": CreateError;
    readonly "responses": CreateResponses;
    readonly "fullResponse": CreateFullResponse;
};
export type GetInput = {
    readonly "id": string;
};
export type GetArguments = [
    input: {
        readonly "id": string;
    },
    options?: RequestOptions
];
export type GetResponse = Task;
export type GetError = Problem;
export type GetResponses = {
    readonly "200": Task;
    readonly "404": Problem;
};
export type GetFullResponse = HttpResult<200, Task>;
export type GetContract = {
    readonly "args": GetArguments;
    readonly "input": GetInput;
    readonly "response": GetResponse;
    readonly "error": GetError;
    readonly "responses": GetResponses;
    readonly "fullResponse": GetFullResponse;
};
export type UpdateInput = {
    readonly "id": string;
    readonly "body"?: {
        readonly "status"?: ("open" | "done") & string;
        readonly "title"?: string;
    };
};
export type UpdateArguments = [
    input: {
        readonly "id": string;
        readonly "body"?: {
            readonly "status"?: ("open" | "done") & string;
            readonly "title"?: string;
        };
    },
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type UpdateResponse = Task;
export type UpdateError = never;
export type UpdateResponses = {
    readonly "200": Task;
};
export type UpdateFullResponse = HttpResult<200, Task>;
export type UpdateContract = {
    readonly "args": UpdateArguments;
    readonly "input": UpdateInput;
    readonly "response": UpdateResponse;
    readonly "error": UpdateError;
    readonly "responses": UpdateResponses;
    readonly "fullResponse": UpdateFullResponse;
};
const TaskSchema = z.strictObject({
    "createdAt": z.iso.datetime({ offset: true }),
    "id": z.string(),
    "labels": z.looseObject({}).catchall(z.string()).optional(),
    "status": z.intersection(z.string(), z.union([z.literal("open"), z.literal("done")])),
    "title": z.string().refine(value => [...value].length >= 1, "Must satisfy minLength: 1").refine(value => [...value].length <= 200, "Must satisfy maxLength: 200")
});
export const List200Schema = z.strictObject({
    "items": z.array(TaskSchema),
    "nextCursor": z.string().optional()
});
export const Create201Schema = TaskSchema;
const ProblemSchema = z.strictObject({
    "code": z.string(),
    "message": z.string()
});
export const Create422Schema = ProblemSchema;
export const Get200Schema = TaskSchema;
export const Get404Schema = ProblemSchema;
export const Update200Schema = TaskSchema;
const defineEndpoint = createEndpointFactory("a0e40c2397785a61");
export const api = {
    "tasks": {
        "list": defineEndpoint<ListContract, "query">({
            "method": "GET",
            "path": "/tasks",
            "id": "list",
            "kind": "query",
            "queryParams": [
                {
                    "name": "status"
                },
                {
                    "name": "limit"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": List200Schema
                }
            }
        }),
        "create": defineEndpoint<CreateContract, "mutation">({
            "method": "POST",
            "path": "/tasks",
            "id": "create",
            "kind": "mutation",
            "requestBody": {
                "type": "json",
                "required": true,
                "fields": [
                    "labels",
                    "status",
                    "title"
                ]
            },
            "responses": {
                "201": {
                    "mediaType": "application/json",
                    "schema": Create201Schema
                },
                "422": {
                    "mediaType": "application/problem+json",
                    "schema": Create422Schema
                }
            }
        }),
        "get": defineEndpoint<GetContract, "query">({
            "method": "GET",
            "path": "/tasks/{id}",
            "id": "get",
            "kind": "query",
            "pathParams": [
                {
                    "name": "id"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": Get200Schema
                },
                "404": {
                    "mediaType": "application/problem+json",
                    "schema": Get404Schema
                }
            }
        }),
        "update": defineEndpoint<UpdateContract, "mutation">({
            "method": "PATCH",
            "path": "/tasks/{id}",
            "id": "update",
            "kind": "mutation",
            "pathParams": [
                {
                    "name": "id"
                }
            ],
            "requestBody": {
                "type": "json",
                "mode": "separate"
            },
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": Update200Schema
                }
            }
        })
    }
};
