/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { defineApi } from "@accord/client";
import { endpoints as assetsEndpoints } from "./sdk/endpoints/assets.js";
export type * from "./sdk/types/assets.js";
export const api = defineApi("f8d72c46252ec3f3", {
    "assets": assetsEndpoints
});
