/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createEndpointFactory, type BinaryUpload, type HttpResult, type RequestOptions, type StatusRange } from "@accord/client";
type AccordSimplify<T> = T extends unknown ? {
    [K in keyof T]: T[K];
} : never;
type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T;
type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T;
export type UploadInput = {
    readonly "file": BinaryUpload;
    readonly "metadata": {
        readonly "description"?: string | null;
        readonly "name": string;
    };
    readonly "tags"?: ReadonlyArray<string>;
};
export type UploadArguments = [
    input: {
        readonly "file": BinaryUpload;
        readonly "metadata": {
            readonly "description"?: string | null;
            readonly "name": string;
        };
        readonly "tags"?: ReadonlyArray<string>;
    },
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "multipart/form-data" | `multipart/form-data;${string}`;
        };
    }
];
export type UploadResponse = {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
};
export type UploadError = never;
export type UploadResponses = {
    readonly "201": {
        readonly "id": string;
        readonly "name": string;
        readonly "size": number;
    };
};
export type UploadFullResponse = HttpResult<201, {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
}>;
export type UploadContract = {
    readonly "args": UploadArguments;
    readonly "input": UploadInput;
    readonly "response": UploadResponse;
    readonly "error": UploadError;
    readonly "responses": UploadResponses;
    readonly "fullResponse": UploadFullResponse;
};
export type RenameInput = {
    readonly "id": string;
    readonly "body": {
        readonly "id": string;
        readonly "name": string;
    };
};
export type RenameArguments = [
    input: {
        readonly "id": string;
        readonly "body": {
            readonly "id": string;
            readonly "name": string;
        };
    },
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type RenameResponse = {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
};
export type RenameError = never;
export type RenameResponses = {
    readonly "200": {
        readonly "id": string;
        readonly "name": string;
        readonly "size": number;
    };
};
export type RenameFullResponse = HttpResult<200, {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
}>;
export type RenameContract = {
    readonly "args": RenameArguments;
    readonly "input": RenameInput;
    readonly "response": RenameResponse;
    readonly "error": RenameError;
    readonly "responses": RenameResponses;
    readonly "fullResponse": RenameFullResponse;
};
export type RemoveInput = {
    readonly "id": string;
};
export type RemoveArguments = [
    input: {
        readonly "id": string;
    },
    options?: RequestOptions
];
export type RemoveResponse = undefined;
export type RemoveError = never;
export type RemoveResponses = {
    readonly "204": undefined;
};
export type RemoveFullResponse = HttpResult<204, undefined>;
export type RemoveContract = {
    readonly "args": RemoveArguments;
    readonly "input": RemoveInput;
    readonly "response": RemoveResponse;
    readonly "error": RemoveError;
    readonly "responses": RemoveResponses;
    readonly "fullResponse": RemoveFullResponse;
};
const defineEndpoint = createEndpointFactory("582fb1aea7c8bea6");
export const api = {
    "assets": {
        "upload": defineEndpoint<UploadContract, "mutation">({
            "method": "POST",
            "path": "/assets",
            "id": "upload",
            "kind": "mutation",
            "requestBody": {
                "content": [
                    {
                        "mediaType": "multipart/form-data",
                        "codec": {
                            "kind": "form",
                            "mediaType": "multipart/form-data",
                            "fields": {
                                "file": {
                                    "mediaType": "application/octet-stream",
                                    "codec": {
                                        "kind": "bytes",
                                        "value": "upload"
                                    },
                                    "multiple": false,
                                    "headers": {}
                                },
                                "metadata": {
                                    "mediaType": "application/json",
                                    "codec": {
                                        "kind": "json"
                                    },
                                    "multiple": false,
                                    "headers": {}
                                },
                                "tags": {
                                    "mediaType": "text/plain",
                                    "codec": {
                                        "kind": "text"
                                    },
                                    "multiple": true,
                                    "headers": {}
                                }
                            },
                            "patterns": {},
                            "additional": {
                                "mediaType": "application/octet-stream",
                                "codec": {
                                    "kind": "bytes",
                                    "value": "upload"
                                },
                                "multiple": false,
                                "headers": {}
                            }
                        }
                    }
                ],
                "required": true,
                "fields": [
                    "file",
                    "metadata",
                    "tags"
                ]
            },
            "responses": {
                "201": {
                    "mediaType": "application/json"
                }
            }
        }),
        "rename": defineEndpoint<RenameContract, "mutation">({
            "method": "PATCH",
            "path": "/assets/{id}",
            "id": "rename",
            "kind": "mutation",
            "pathParams": [
                {
                    "name": "id"
                }
            ],
            "requestBody": {
                "content": [
                    {
                        "mediaType": "application/json"
                    }
                ],
                "required": true,
                "mode": "separate"
            },
            "responses": {
                "200": {
                    "mediaType": "application/json"
                }
            }
        }),
        "remove": defineEndpoint<RemoveContract, "mutation">({
            "method": "DELETE",
            "path": "/assets/{id}",
            "id": "remove",
            "kind": "mutation",
            "pathParams": [
                {
                    "name": "id"
                }
            ],
            "responses": {
                "204": {}
            }
        })
    }
};
