/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { defineEndpoint, type BinaryUpload, type HttpResult, type RequestOptions, type StatusRange } from "@accord/client";
type AccordSimplify<T> = T extends unknown ? {
    [K in keyof T]: T[K];
} : never;
type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T;
type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T;
export type AssetsUploadInput = {
    readonly "file": BinaryUpload;
    readonly "metadata": {
        readonly "description"?: string | null;
        readonly "name": string;
    };
    readonly "tags"?: ReadonlyArray<string>;
};
export type AssetsUploadArguments = [
    input: {
        readonly "file": BinaryUpload;
        readonly "metadata": {
            readonly "description"?: string | null;
            readonly "name": string;
        };
        readonly "tags"?: ReadonlyArray<string>;
    },
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "multipart/form-data" | `multipart/form-data;${string}`;
        };
    }
];
export type AssetsUploadResponse = {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
};
export type AssetsUploadError = never;
export type AssetsUploadResponses = {
    readonly "201": {
        readonly "id": string;
        readonly "name": string;
        readonly "size": number;
    };
};
export type AssetsUploadFullResponse = HttpResult<201, {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
}>;
export type AssetsUploadContract = {
    readonly "args": AssetsUploadArguments;
    readonly "input": AssetsUploadInput;
    readonly "response": AssetsUploadResponse;
    readonly "error": AssetsUploadError;
    readonly "responses": AssetsUploadResponses;
    readonly "fullResponse": AssetsUploadFullResponse;
};
export type AssetsRenameInput = {
    readonly "id": string;
    readonly "body": {
        readonly "id": string;
        readonly "name": string;
    };
};
export type AssetsRenameArguments = [
    input: {
        readonly "id": string;
        readonly "body": {
            readonly "id": string;
            readonly "name": string;
        };
    },
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type AssetsRenameResponse = {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
};
export type AssetsRenameError = never;
export type AssetsRenameResponses = {
    readonly "200": {
        readonly "id": string;
        readonly "name": string;
        readonly "size": number;
    };
};
export type AssetsRenameFullResponse = HttpResult<200, {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
}>;
export type AssetsRenameContract = {
    readonly "args": AssetsRenameArguments;
    readonly "input": AssetsRenameInput;
    readonly "response": AssetsRenameResponse;
    readonly "error": AssetsRenameError;
    readonly "responses": AssetsRenameResponses;
    readonly "fullResponse": AssetsRenameFullResponse;
};
export type AssetsRemoveInput = {
    readonly "id": string;
};
export type AssetsRemoveArguments = [
    input: {
        readonly "id": string;
    },
    options?: RequestOptions
];
export type AssetsRemoveResponse = undefined;
export type AssetsRemoveError = never;
export type AssetsRemoveResponses = {
    readonly "204": undefined;
};
export type AssetsRemoveFullResponse = HttpResult<204, undefined>;
export type AssetsRemoveContract = {
    readonly "args": AssetsRemoveArguments;
    readonly "input": AssetsRemoveInput;
    readonly "response": AssetsRemoveResponse;
    readonly "error": AssetsRemoveError;
    readonly "responses": AssetsRemoveResponses;
    readonly "fullResponse": AssetsRemoveFullResponse;
};
type _AssetsUploadInput = AssetsUploadInput;
type _AssetsUploadResponse = AssetsUploadResponse;
type _AssetsUploadError = AssetsUploadError;
type _AssetsUploadResponses = AssetsUploadResponses;
type _AssetsUploadArguments = AssetsUploadArguments;
type _AssetsUploadFullResponse = AssetsUploadFullResponse;
type _AssetsRenameInput = AssetsRenameInput;
type _AssetsRenameResponse = AssetsRenameResponse;
type _AssetsRenameError = AssetsRenameError;
type _AssetsRenameResponses = AssetsRenameResponses;
type _AssetsRenameArguments = AssetsRenameArguments;
type _AssetsRenameFullResponse = AssetsRenameFullResponse;
type _AssetsRemoveInput = AssetsRemoveInput;
type _AssetsRemoveResponse = AssetsRemoveResponse;
type _AssetsRemoveError = AssetsRemoveError;
type _AssetsRemoveResponses = AssetsRemoveResponses;
type _AssetsRemoveArguments = AssetsRemoveArguments;
type _AssetsRemoveFullResponse = AssetsRemoveFullResponse;
export const api = {
    "assets": {
        "upload": defineEndpoint<AssetsUploadContract, "mutation">({
            "kind": "endpoint",
            "plan": {
                "apiId": "c51c0cec0551be53",
                "method": "POST",
                "path": "/assets",
                "operationId": "upload",
                "operationKind": "mutation",
                "parameters": [],
                "responses": [
                    {
                        "status": 201,
                        "content": [
                            {
                                "mediaType": "application/json",
                                "representation": {
                                    "key": "response-201-0",
                                    "codec": {
                                        "kind": "json"
                                    }
                                }
                            }
                        ],
                        "headers": []
                    }
                ],
                "resultMode": "payload",
                "servers": [
                    {
                        "url": "https://assets.example.test/{region}/v1",
                        "variables": {
                            "region": {
                                "default": "eu",
                                "enum": [
                                    "eu",
                                    "us"
                                ]
                            }
                        }
                    }
                ],
                "security": [
                    {
                        "apiKey": []
                    }
                ],
                "securitySchemes": {
                    "apiKey": {
                        "type": "apiKey",
                        "name": "X-API-Key",
                        "in": "header"
                    }
                },
                "requestBody": {
                    "required": true,
                    "mode": "merge",
                    "fields": [
                        "file",
                        "metadata",
                        "tags"
                    ],
                    "content": [
                        {
                            "mediaType": "multipart/form-data",
                            "representation": {
                                "key": "request-0",
                                "codec": {
                                    "kind": "form",
                                    "mediaType": "multipart/form-data",
                                    "fields": {
                                        "file": {
                                            "mediaType": "application/octet-stream",
                                            "codec": {
                                                "kind": "bytes",
                                                "value": "upload"
                                            },
                                            "multiple": false,
                                            "headers": {}
                                        },
                                        "metadata": {
                                            "mediaType": "application/json",
                                            "codec": {
                                                "kind": "json"
                                            },
                                            "multiple": false,
                                            "headers": {}
                                        },
                                        "tags": {
                                            "mediaType": "text/plain",
                                            "codec": {
                                                "kind": "text"
                                            },
                                            "multiple": true,
                                            "headers": {}
                                        }
                                    },
                                    "patterns": {},
                                    "additional": {
                                        "mediaType": "application/octet-stream",
                                        "codec": {
                                            "kind": "bytes",
                                            "value": "upload"
                                        },
                                        "multiple": false,
                                        "headers": {}
                                    }
                                }
                            }
                        }
                    ],
                    "defaultMediaType": "multipart/form-data"
                }
            }
        }),
        "rename": defineEndpoint<AssetsRenameContract, "mutation">({
            "kind": "endpoint",
            "plan": {
                "apiId": "c51c0cec0551be53",
                "method": "PATCH",
                "path": "/assets/{id}",
                "operationId": "rename",
                "operationKind": "mutation",
                "parameters": [
                    {
                        "name": "id",
                        "inputName": "id",
                        "in": "path",
                        "required": true,
                        "style": "simple",
                        "explode": false,
                        "allowReserved": false
                    }
                ],
                "responses": [
                    {
                        "status": 200,
                        "content": [
                            {
                                "mediaType": "application/json",
                                "representation": {
                                    "key": "response-200-0",
                                    "codec": {
                                        "kind": "json"
                                    }
                                }
                            }
                        ],
                        "headers": []
                    }
                ],
                "resultMode": "payload",
                "servers": [
                    {
                        "url": "https://assets.example.test/{region}/v1",
                        "variables": {
                            "region": {
                                "default": "eu",
                                "enum": [
                                    "eu",
                                    "us"
                                ]
                            }
                        }
                    }
                ],
                "security": [
                    {
                        "apiKey": []
                    }
                ],
                "securitySchemes": {
                    "apiKey": {
                        "type": "apiKey",
                        "name": "X-API-Key",
                        "in": "header"
                    }
                },
                "requestBody": {
                    "required": true,
                    "mode": "separate",
                    "fields": [
                        "id",
                        "name"
                    ],
                    "content": [
                        {
                            "mediaType": "application/json",
                            "representation": {
                                "key": "request-0",
                                "codec": {
                                    "kind": "json"
                                }
                            }
                        }
                    ],
                    "defaultMediaType": "application/json"
                }
            }
        }),
        "remove": defineEndpoint<AssetsRemoveContract, "mutation">({
            "kind": "endpoint",
            "plan": {
                "apiId": "c51c0cec0551be53",
                "method": "DELETE",
                "path": "/assets/{id}",
                "operationId": "remove",
                "operationKind": "mutation",
                "parameters": [
                    {
                        "name": "id",
                        "inputName": "id",
                        "in": "path",
                        "required": true,
                        "style": "simple",
                        "explode": false,
                        "allowReserved": false
                    }
                ],
                "responses": [
                    {
                        "status": 204,
                        "content": [],
                        "headers": []
                    }
                ],
                "resultMode": "payload",
                "servers": [
                    {
                        "url": "https://assets.example.test/{region}/v1",
                        "variables": {
                            "region": {
                                "default": "eu",
                                "enum": [
                                    "eu",
                                    "us"
                                ]
                            }
                        }
                    }
                ],
                "security": [
                    {
                        "apiKey": []
                    }
                ],
                "securitySchemes": {
                    "apiKey": {
                        "type": "apiKey",
                        "name": "X-API-Key",
                        "in": "header"
                    }
                }
            }
        })
    }
};
export namespace AccordTypes {
    export type AssetsUploadInput = _AssetsUploadInput;
    export type AssetsUploadResponse = _AssetsUploadResponse;
    export type AssetsUploadError = _AssetsUploadError;
    export type AssetsUploadResponses = _AssetsUploadResponses;
    export type AssetsUploadArguments = _AssetsUploadArguments;
    export type AssetsUploadFullResponse = _AssetsUploadFullResponse;
    export type AssetsRenameInput = _AssetsRenameInput;
    export type AssetsRenameResponse = _AssetsRenameResponse;
    export type AssetsRenameError = _AssetsRenameError;
    export type AssetsRenameResponses = _AssetsRenameResponses;
    export type AssetsRenameArguments = _AssetsRenameArguments;
    export type AssetsRenameFullResponse = _AssetsRenameFullResponse;
    export type AssetsRemoveInput = _AssetsRemoveInput;
    export type AssetsRemoveResponse = _AssetsRemoveResponse;
    export type AssetsRemoveError = _AssetsRemoveError;
    export type AssetsRemoveResponses = _AssetsRemoveResponses;
    export type AssetsRemoveArguments = _AssetsRemoveArguments;
    export type AssetsRemoveFullResponse = _AssetsRemoveFullResponse;
}
