/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createEndpointFactory } from "@accord/client";
import type { CreateContract, GetContract, DownloadContract } from "../types/imports.js";
import {
    Create200Schema,
    Create202Schema,
    Create400Schema,
    Get200Schema,
    Download200Schema
} from "../schemas.js";
const defineEndpoint = createEndpointFactory("0f2f07b43a1ba796");
export const endpoints = {
    "create": defineEndpoint<CreateContract, "mutation">({
        "method": "POST",
        "path": "/imports",
        "id": "create",
        "kind": "mutation",
        "resultMode": "status",
        "requestBody": [
            {
                "type": "json",
                "required": true,
                "mode": "separate"
            },
            {
                "type": "text",
                "mediaType": "text/csv",
                "required": true,
                "mode": "separate"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": Create200Schema
            },
            "202": {
                "mediaType": "application/json",
                "schema": Create202Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": Create400Schema
            }
        }
    }),
    "get": defineEndpoint<GetContract, "query">({
        "method": "GET",
        "path": "/imports/{jobId}",
        "id": "get",
        "kind": "query",
        "pathParams": [
            {
                "name": "jobId"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": Get200Schema
            }
        }
    }),
    "report": {
        "download": defineEndpoint<DownloadContract, "query">({
            "method": "GET",
            "path": "/imports/{jobId}/report",
            "id": "download",
            "kind": "query",
            "pathParams": [
                {
                    "name": "jobId"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/octet-stream",
                    "schema": Download200Schema
                }
            }
        })
    }
};
