/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createEndpointFactory } from "@accord/client";
import type { ListContract, CreateContract, GetContract, UpdateContract } from "../types/tasks.js";
import {
    List200Schema,
    Create201Schema,
    Create422Schema,
    Get200Schema,
    Get404Schema,
    Update200Schema
} from "../schemas.js";
const defineEndpoint = createEndpointFactory("a0e40c2397785a61");
export const endpoints = {
    "list": defineEndpoint<ListContract, "query">({
        "method": "GET",
        "path": "/tasks",
        "id": "list",
        "kind": "query",
        "queryParams": [
            {
                "name": "status"
            },
            {
                "name": "limit"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": List200Schema
            }
        }
    }),
    "create": defineEndpoint<CreateContract, "mutation">({
        "method": "POST",
        "path": "/tasks",
        "id": "create",
        "kind": "mutation",
        "requestBody": {
            "type": "json",
            "required": true,
            "fields": [
                "labels",
                "status",
                "title"
            ]
        },
        "responses": {
            "201": {
                "mediaType": "application/json",
                "schema": Create201Schema
            },
            "422": {
                "mediaType": "application/problem+json",
                "schema": Create422Schema
            }
        }
    }),
    "get": defineEndpoint<GetContract, "query">({
        "method": "GET",
        "path": "/tasks/{id}",
        "id": "get",
        "kind": "query",
        "pathParams": [
            {
                "name": "id"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": Get200Schema
            },
            "404": {
                "mediaType": "application/problem+json",
                "schema": Get404Schema
            }
        }
    }),
    "update": defineEndpoint<UpdateContract, "mutation">({
        "method": "PATCH",
        "path": "/tasks/{id}",
        "id": "update",
        "kind": "mutation",
        "pathParams": [
            {
                "name": "id"
            }
        ],
        "requestBody": {
            "type": "json",
            "mode": "separate"
        },
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": Update200Schema
            }
        }
    })
};
