/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
export type AccordSimplify<T> = T extends unknown ? {
    [K in keyof T]: T[K];
} : never;
export type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T;
export type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T;
