/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { BinaryUpload, HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
export type UploadInput = {
    "file": BinaryUpload;
    "metadata": {
        "description"?: string | null;
        "name": string;
    };
    "tags"?: string[];
};
export type UploadArguments = [
    input: {
        "file": BinaryUpload;
        "metadata": {
            "description"?: string | null;
            "name": string;
        };
        "tags"?: string[];
    },
    options?: RequestOptionsFor<"multipart/form-data">
];
export type UploadResponse = {
    "id": string;
    "name": string;
    "size": number;
};
export type UploadError = never;
export type UploadResponses = {
    "201": {
        "id": string;
        "name": string;
        "size": number;
    };
};
export type UploadFullResponse = HttpResult<201, {
    "id": string;
    "name": string;
    "size": number;
}>;
export type UploadContract = {
    "args": UploadArguments;
    "input": UploadInput;
    "response": UploadResponse;
    "error": UploadError;
    "responses": UploadResponses;
    "fullResponse": UploadFullResponse;
};
export type RenameInput = {
    "id": string;
    "body": {
        "id": string;
        "name": string;
    };
};
export type RenameArguments = [
    input: {
        "id": string;
        "body": {
            "id": string;
            "name": string;
        };
    },
    options?: RequestOptionsFor<"application/json">
];
export type RenameResponse = {
    "id": string;
    "name": string;
    "size": number;
};
export type RenameError = never;
export type RenameResponses = {
    "200": {
        "id": string;
        "name": string;
        "size": number;
    };
};
export type RenameFullResponse = HttpResult<200, {
    "id": string;
    "name": string;
    "size": number;
}>;
export type RenameContract = {
    "args": RenameArguments;
    "input": RenameInput;
    "response": RenameResponse;
    "error": RenameError;
    "responses": RenameResponses;
    "fullResponse": RenameFullResponse;
};
export type RemoveInput = {
    "id": string;
};
export type RemoveArguments = [
    input: {
        "id": string;
    },
    options?: RequestOptions
];
export type RemoveResponse = undefined;
export type RemoveError = never;
export type RemoveResponses = {
    "204": undefined;
};
export type RemoveFullResponse = HttpResult<204, undefined>;
export type RemoveContract = {
    "args": RemoveArguments;
    "input": RemoveInput;
    "response": RemoveResponse;
    "error": RemoveError;
    "responses": RemoveResponses;
    "fullResponse": RemoveFullResponse;
};
