/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { BinaryUpload, HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
export type UploadInput = {
    readonly "file": BinaryUpload;
    readonly "metadata": {
        readonly "description"?: string | null;
        readonly "name": string;
    };
    readonly "tags"?: ReadonlyArray<string>;
};
export type UploadArguments = [
    input: {
        readonly "file": BinaryUpload;
        readonly "metadata": {
            readonly "description"?: string | null;
            readonly "name": string;
        };
        readonly "tags"?: ReadonlyArray<string>;
    },
    options?: RequestOptionsFor<"multipart/form-data">
];
export type UploadResponse = {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
};
export type UploadError = never;
export type UploadResponses = {
    readonly "201": {
        readonly "id": string;
        readonly "name": string;
        readonly "size": number;
    };
};
export type UploadFullResponse = HttpResult<201, {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
}>;
export type UploadContract = {
    readonly "args": UploadArguments;
    readonly "input": UploadInput;
    readonly "response": UploadResponse;
    readonly "error": UploadError;
    readonly "responses": UploadResponses;
    readonly "fullResponse": UploadFullResponse;
};
export type RenameInput = {
    readonly "id": string;
    readonly "body": {
        readonly "id": string;
        readonly "name": string;
    };
};
export type RenameArguments = [
    input: {
        readonly "id": string;
        readonly "body": {
            readonly "id": string;
            readonly "name": string;
        };
    },
    options?: RequestOptionsFor<"application/json">
];
export type RenameResponse = {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
};
export type RenameError = never;
export type RenameResponses = {
    readonly "200": {
        readonly "id": string;
        readonly "name": string;
        readonly "size": number;
    };
};
export type RenameFullResponse = HttpResult<200, {
    readonly "id": string;
    readonly "name": string;
    readonly "size": number;
}>;
export type RenameContract = {
    readonly "args": RenameArguments;
    readonly "input": RenameInput;
    readonly "response": RenameResponse;
    readonly "error": RenameError;
    readonly "responses": RenameResponses;
    readonly "fullResponse": RenameFullResponse;
};
export type RemoveInput = {
    readonly "id": string;
};
export type RemoveArguments = [
    input: {
        readonly "id": string;
    },
    options?: RequestOptions
];
export type RemoveResponse = undefined;
export type RemoveError = never;
export type RemoveResponses = {
    readonly "204": undefined;
};
export type RemoveFullResponse = HttpResult<204, undefined>;
export type RemoveContract = {
    readonly "args": RemoveArguments;
    readonly "input": RemoveInput;
    readonly "response": RemoveResponse;
    readonly "error": RemoveError;
    readonly "responses": RemoveResponses;
    readonly "fullResponse": RemoveFullResponse;
};
