/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
export type AccordSimplify<T> = T extends unknown ? {
    [K in keyof T]: T[K];
} : never;
export type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T;
export type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T;
export type Problem = {
    readonly "code": string;
    readonly "message": string;
};
export type Task = {
    readonly "createdAt": string;
    readonly "id": string;
    readonly "labels"?: {
        readonly [key: string]: string;
    };
    readonly "status": ("open" | "done") & string;
    readonly "title": string;
};
export type TaskRequest = {
    readonly "createdAt"?: never;
    readonly "id"?: never;
    readonly "labels"?: {
        readonly [key: string]: string;
    };
    readonly "status": ("open" | "done") & string;
    readonly "title": string;
};
