/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { z } from "zod";
const TaskSchema = z.strictObject({
    "createdAt": z.iso.datetime({ offset: true }),
    "id": z.string(),
    "labels": z.looseObject({}).catchall(z.string()).optional(),
    "status": z.intersection(z.string(), z.union([z.literal("open"), z.literal("done")])),
    "title": z.string().refine(value => [...value].length >= 1, "Must satisfy minLength: 1").refine(value => [...value].length <= 200, "Must satisfy maxLength: 200")
});
export const List200Schema = z.strictObject({
    "items": z.array(TaskSchema),
    "nextCursor": z.string().optional()
});
export const Create201Schema = TaskSchema;
const ProblemSchema = z.strictObject({
    "code": z.string(),
    "message": z.string()
});
export const Create422Schema = ProblemSchema;
export const Get200Schema = TaskSchema;
export const Get404Schema = ProblemSchema;
export const Update200Schema = TaskSchema;
