/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
export type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T;
export type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T;
export type ImportJob = {
    readonly "jobId": string;
    readonly "state": "queued";
};
export type ImportResult = {
    readonly "imported": number;
    readonly "state": "completed";
};
