/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { z } from "zod";
const ImportResultSchema = z.strictObject({
    "imported": z.number().refine(Number.isInteger, "Expected integer").gte(0),
    "state": z.literal("completed")
});
export const Create200Schema = ImportResultSchema;
const ImportJobSchema = z.strictObject({
    "jobId": z.string(),
    "state": z.literal("queued")
});
export const Create202Schema = ImportJobSchema;
export const Create400Schema = z.looseObject({
    "message": z.string()
});
export const Get200Schema = z.xor([ImportJobSchema, ImportResultSchema]);
export const Download200Schema = z.instanceof(ArrayBuffer);
