/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
export type Problem = {
    "code": string;
    "message": string;
};
export type Task = {
    "createdAt": string;
    "id": string;
    "labels"?: {
        [key: string]: string;
    };
    "status": ("open" | "done") & string;
    "title": string;
};
export type TaskRequest = {
    "createdAt"?: never;
    "id"?: never;
    "labels"?: {
        [key: string]: string;
    };
    "status": ("open" | "done") & string;
    "title": string;
};
export type ListInput = {
    "status"?: ("open" | "done") & string;
    "limit"?: number;
};
export type ListArguments = [
    input?: {
        "status"?: ("open" | "done") & string;
        "limit"?: number;
    },
    options?: RequestOptions
];
export type ListResponse = {
    "items": Task[];
    "nextCursor"?: string;
};
export type ListError = never;
export type ListResponses = {
    "200": {
        "items": Task[];
        "nextCursor"?: string;
    };
};
export type ListFullResponse = HttpResult<200, {
    "items": Task[];
    "nextCursor"?: string;
}>;
export type ListContract = {
    "args": ListArguments;
    "input": ListInput;
    "response": ListResponse;
    "error": ListError;
    "responses": ListResponses;
    "fullResponse": ListFullResponse;
};
export type CreateInput = TaskRequest;
export type CreateArguments = [
    input: TaskRequest,
    options?: RequestOptionsFor<"application/json">
];
export type CreateResponse = Task;
export type CreateError = Problem;
export type CreateResponses = {
    "201": Task;
    "422": Problem;
};
export type CreateFullResponse = HttpResult<201, Task>;
export type CreateContract = {
    "args": CreateArguments;
    "input": CreateInput;
    "response": CreateResponse;
    "error": CreateError;
    "responses": CreateResponses;
    "fullResponse": CreateFullResponse;
};
export type GetInput = {
    "id": string;
};
export type GetArguments = [
    input: {
        "id": string;
    },
    options?: RequestOptions
];
export type GetResponse = Task;
export type GetError = Problem;
export type GetResponses = {
    "200": Task;
    "404": Problem;
};
export type GetFullResponse = HttpResult<200, Task>;
export type GetContract = {
    "args": GetArguments;
    "input": GetInput;
    "response": GetResponse;
    "error": GetError;
    "responses": GetResponses;
    "fullResponse": GetFullResponse;
};
export type UpdateInput = {
    "id": string;
    "body"?: {
        "status"?: ("open" | "done") & string;
        "title"?: string;
    };
};
export type UpdateArguments = [
    input: {
        "id": string;
        "body"?: {
            "status"?: ("open" | "done") & string;
            "title"?: string;
        };
    },
    options?: RequestOptionsFor<"application/json">
];
export type UpdateResponse = Task;
export type UpdateError = never;
export type UpdateResponses = {
    "200": Task;
};
export type UpdateFullResponse = HttpResult<200, Task>;
export type UpdateContract = {
    "args": UpdateArguments;
    "input": UpdateInput;
    "response": UpdateResponse;
    "error": UpdateError;
    "responses": UpdateResponses;
    "fullResponse": UpdateFullResponse;
};
