/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
export type Problem = {
    readonly "code": string;
    readonly "message": string;
};
export type Task = {
    readonly "createdAt": string;
    readonly "id": string;
    readonly "labels"?: {
        readonly [key: string]: string;
    };
    readonly "status": ("open" | "done") & string;
    readonly "title": string;
};
export type TaskRequest = {
    readonly "createdAt"?: never;
    readonly "id"?: never;
    readonly "labels"?: {
        readonly [key: string]: string;
    };
    readonly "status": ("open" | "done") & string;
    readonly "title": string;
};
export type ListInput = {
    readonly "status"?: ("open" | "done") & string;
    readonly "limit"?: number;
};
export type ListArguments = [
    input?: {
        readonly "status"?: ("open" | "done") & string;
        readonly "limit"?: number;
    },
    options?: RequestOptions
];
export type ListResponse = {
    readonly "items": ReadonlyArray<Task>;
    readonly "nextCursor"?: string;
};
export type ListError = never;
export type ListResponses = {
    readonly "200": {
        readonly "items": ReadonlyArray<Task>;
        readonly "nextCursor"?: string;
    };
};
export type ListFullResponse = HttpResult<200, {
    readonly "items": ReadonlyArray<Task>;
    readonly "nextCursor"?: string;
}>;
export type ListContract = {
    readonly "args": ListArguments;
    readonly "input": ListInput;
    readonly "response": ListResponse;
    readonly "error": ListError;
    readonly "responses": ListResponses;
    readonly "fullResponse": ListFullResponse;
};
export type CreateInput = TaskRequest;
export type CreateArguments = [
    input: TaskRequest,
    options?: RequestOptionsFor<"application/json">
];
export type CreateResponse = Task;
export type CreateError = Problem;
export type CreateResponses = {
    readonly "201": Task;
    readonly "422": Problem;
};
export type CreateFullResponse = HttpResult<201, Task>;
export type CreateContract = {
    readonly "args": CreateArguments;
    readonly "input": CreateInput;
    readonly "response": CreateResponse;
    readonly "error": CreateError;
    readonly "responses": CreateResponses;
    readonly "fullResponse": CreateFullResponse;
};
export type GetInput = {
    readonly "id": string;
};
export type GetArguments = [
    input: {
        readonly "id": string;
    },
    options?: RequestOptions
];
export type GetResponse = Task;
export type GetError = Problem;
export type GetResponses = {
    readonly "200": Task;
    readonly "404": Problem;
};
export type GetFullResponse = HttpResult<200, Task>;
export type GetContract = {
    readonly "args": GetArguments;
    readonly "input": GetInput;
    readonly "response": GetResponse;
    readonly "error": GetError;
    readonly "responses": GetResponses;
    readonly "fullResponse": GetFullResponse;
};
export type UpdateInput = {
    readonly "id": string;
    readonly "body"?: {
        readonly "status"?: ("open" | "done") & string;
        readonly "title"?: string;
    };
};
export type UpdateArguments = [
    input: {
        readonly "id": string;
        readonly "body"?: {
            readonly "status"?: ("open" | "done") & string;
            readonly "title"?: string;
        };
    },
    options?: RequestOptionsFor<"application/json">
];
export type UpdateResponse = Task;
export type UpdateError = never;
export type UpdateResponses = {
    readonly "200": Task;
};
export type UpdateFullResponse = HttpResult<200, Task>;
export type UpdateContract = {
    readonly "args": UpdateArguments;
    readonly "input": UpdateInput;
    readonly "response": UpdateResponse;
    readonly "error": UpdateError;
    readonly "responses": UpdateResponses;
    readonly "fullResponse": UpdateFullResponse;
};
