/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
import type { ImportJob, ImportResult } from "../models.js";
export type CreateInput = {
    readonly "body": {
        readonly "rows": ReadonlyArray<{
            readonly "email": string;
            readonly [key: string]: string;
        }>;
    };
} | {
    readonly "body": string;
};
export type CreateArguments = [
    input: {
        readonly "body": {
            readonly "rows": ReadonlyArray<{
                readonly "email": string;
                readonly [key: string]: string;
            }>;
        };
    },
    options?: RequestOptionsFor<"application/json">
] | [
    input: {
        readonly "body": string;
    },
    options: RequestOptionsFor<"text/csv", true>
];
export type CreateResponse = {
    readonly "status": 200;
    readonly "data": ImportResult;
} | {
    readonly "status": 202;
    readonly "data": ImportJob;
};
export type CreateError = {
    readonly "message": string;
    readonly [key: string]: unknown;
};
export type CreateResponses = {
    readonly "200": ImportResult;
    readonly "202": ImportJob;
    readonly "400": {
        readonly "message": string;
        readonly [key: string]: unknown;
    };
};
export type CreateFullResponse = HttpResult<200, ImportResult> | HttpResult<202, ImportJob>;
export type CreateContract = {
    readonly "args": CreateArguments;
    readonly "input": CreateInput;
    readonly "response": CreateResponse;
    readonly "error": CreateError;
    readonly "responses": CreateResponses;
    readonly "fullResponse": CreateFullResponse;
};
export type GetInput = {
    readonly "jobId": string;
};
export type GetArguments = [
    input: {
        readonly "jobId": string;
    },
    options?: RequestOptions
];
export type GetResponse = ImportJob | ImportResult;
export type GetError = never;
export type GetResponses = {
    readonly "200": ImportJob | ImportResult;
};
export type GetFullResponse = HttpResult<200, ImportJob | ImportResult>;
export type GetContract = {
    readonly "args": GetArguments;
    readonly "input": GetInput;
    readonly "response": GetResponse;
    readonly "error": GetError;
    readonly "responses": GetResponses;
    readonly "fullResponse": GetFullResponse;
};
export type DownloadInput = {
    readonly "jobId": string;
};
export type DownloadArguments = [
    input: {
        readonly "jobId": string;
    },
    options?: RequestOptions
];
export type DownloadResponse = ArrayBuffer;
export type DownloadError = never;
export type DownloadResponses = {
    readonly "200": ArrayBuffer;
};
export type DownloadFullResponse = HttpResult<200, ArrayBuffer>;
export type DownloadContract = {
    readonly "args": DownloadArguments;
    readonly "input": DownloadInput;
    readonly "response": DownloadResponse;
    readonly "error": DownloadError;
    readonly "responses": DownloadResponses;
    readonly "fullResponse": DownloadFullResponse;
};
