/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
export type ImportJob = {
    "jobId": string;
    "state": "queued";
};
export type ImportResult = {
    "imported": number;
    "state": "completed";
};
export type CreateInput = {
    "body": {
        "rows": {
            "email": string;
            [key: string]: string;
        }[];
    };
} | {
    "body": string;
};
export type CreateArguments = [
    input: {
        "body": {
            "rows": {
                "email": string;
                [key: string]: string;
            }[];
        };
    },
    options?: RequestOptionsFor<"application/json">
] | [
    input: {
        "body": string;
    },
    options: RequestOptionsFor<"text/csv", true>
];
export type CreateResponse = {
    "status": 200;
    "data": ImportResult;
} | {
    "status": 202;
    "data": ImportJob;
};
export type CreateError = {
    "message": string;
    [key: string]: unknown;
};
export type CreateResponses = {
    "200": ImportResult;
    "202": ImportJob;
    "400": {
        "message": string;
        [key: string]: unknown;
    };
};
export type CreateFullResponse = HttpResult<200, ImportResult> | HttpResult<202, ImportJob>;
export type CreateContract = {
    "args": CreateArguments;
    "input": CreateInput;
    "response": CreateResponse;
    "error": CreateError;
    "responses": CreateResponses;
    "fullResponse": CreateFullResponse;
};
export type GetInput = {
    "jobId": string;
};
export type GetArguments = [
    input: {
        "jobId": string;
    },
    options?: RequestOptions
];
export type GetResponse = ImportJob | ImportResult;
export type GetError = never;
export type GetResponses = {
    "200": ImportJob | ImportResult;
};
export type GetFullResponse = HttpResult<200, ImportJob | ImportResult>;
export type GetContract = {
    "args": GetArguments;
    "input": GetInput;
    "response": GetResponse;
    "error": GetError;
    "responses": GetResponses;
    "fullResponse": GetFullResponse;
};
export type DownloadInput = {
    "jobId": string;
};
export type DownloadArguments = [
    input: {
        "jobId": string;
    },
    options?: RequestOptions
];
export type DownloadResponse = ArrayBuffer;
export type DownloadError = never;
export type DownloadResponses = {
    "200": ArrayBuffer;
};
export type DownloadFullResponse = HttpResult<200, ArrayBuffer>;
export type DownloadContract = {
    "args": DownloadArguments;
    "input": DownloadInput;
    "response": DownloadResponse;
    "error": DownloadError;
    "responses": DownloadResponses;
    "fullResponse": DownloadFullResponse;
};
