/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { defineApi } from "@accord/client";
import { endpoints as importsEndpoints } from "./sdk/endpoints/imports.js";
export type * from "./sdk/types/imports.js";
export * from "./sdk/schemas.js";
export const api = defineApi("0f2f07b43a1ba796", {
    "imports": importsEndpoints
});
