import ts from "typescript"
import { modelModules, sourceTypeReferences } from "./model-modules.js"
import { sanitizeIdentifier } from "./naming.js"
import type { ValidationSource } from "./validation-adapter.js"

export const generatedHeader =
  "/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */"

export const typeHelpers = [
  "type ObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T",
  "type ArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T",
]
const helperNames = ["ObjectConstraints", "ArrayConstraints"]
const clientTypes = [
  "BinaryUpload",
  "HttpResult",
  "RequestOptions",
  "RequestOptionsFor",
  "StatusRange",
]

export function formatSource(source: string): string {
  return ts
    .createPrinter({ newLine: ts.NewLineKind.LineFeed })
    .printFile(
      ts.createSourceFile("sdk.ts", source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS),
    )
}

/** The TS printer leaves named imports/exports on one line, even for large APIs. */
function formatModule(source: string): string {
  let formatted = formatSource(source)
  const file = ts.createSourceFile("module.ts", formatted, ts.ScriptTarget.Latest, true)
  for (const statement of [...file.statements].reverse()) {
    const bindings = ts.isImportDeclaration(statement)
      ? statement.importClause?.namedBindings
      : ts.isExportDeclaration(statement)
        ? statement.exportClause
        : undefined
    if (!bindings || (!ts.isNamedImports(bindings) && !ts.isNamedExports(bindings))) continue
    if (statement.getText(file).length <= 100 || bindings.elements.length < 2) continue
    const names = bindings.elements.map((element) => `    ${element.getText(file)}`)
    formatted =
      formatted.slice(0, bindings.getStart(file)) +
      `{\n${names.join(",\n")}\n}` +
      formatted.slice(bindings.getEnd())
  }
  return formatted
}

interface EndpointGroup {
  readonly name: string
  readonly types: string
  readonly contracts: readonly string[]
  readonly schemas: readonly string[]
  readonly endpoints: string
}

interface ModuleInput {
  readonly apiId: string
  readonly models: ReadonlyMap<string, string>
  readonly modelFamilies: readonly (readonly string[])[]
  readonly groups: readonly EndpointGroup[]
  readonly validation: ValidationSource | undefined
}

/** Import only referenced types, keeping public declarations unqualified and readable. */
function typeImports(
  usedTypes: ReadonlySet<string>,
  candidates: readonly string[],
  from: string,
): string {
  const used = candidates.filter((name) => usedTypes.has(name))
  return used.length ? `import type { ${used.sort().join(", ")} } from ${JSON.stringify(from)}` : ""
}

function localHelpers(usedTypes: ReadonlySet<string>): readonly string[] {
  return typeHelpers.filter((_, index) => usedTypes.has(helperNames[index]!))
}

function groupFileNames(groups: readonly EndpointGroup[]): ReadonlyMap<string, string> {
  const names = new Map<string, string>()
  const used = new Set<string>()
  for (const group of groups) {
    let core = sanitizeIdentifier(group.name)
    // Reserve the shared types module and keep filenames portable on Windows.
    if (/^(?:shared|con|prn|aux|nul|com[0-9]|lpt[0-9])$/i.test(core)) core += "Api"
    let name = core
    for (let index = 2; used.has(name.toLowerCase()); index++) name = `${core}${index}`
    used.add(name.toLowerCase())
    names.set(group.name, name)
  }
  return names
}

export function renderModules(input: ModuleInput) {
  const files: Record<string, string> = {}
  const add = (path: string, parts: readonly string[]) => {
    files[path] = formatModule([generatedHeader, ...parts.filter(Boolean), ""].join("\n\n"))
  }
  const groupNames = groupFileNames(input.groups)
  const modelsByFile = new Map<string, string[]>()
  const placement = modelModules(input.models, input.modelFamilies, input.groups)
  for (const [name, group] of placement) {
    const file = group === undefined ? "shared" : groupNames.get(group)!
    const names = modelsByFile.get(file) ?? []
    names.push(name)
    modelsByFile.set(file, names)
  }
  const modelImports = (usedTypes: ReadonlySet<string>, prefix: string, self?: string) =>
    [...modelsByFile].flatMap(([file, names]) =>
      file === self ? [] : [typeImports(usedTypes, names, `${prefix}${file}.js`)],
    )
  const typeFiles = new Map(input.groups.map((group) => [groupNames.get(group.name)!, group.types]))
  if (modelsByFile.has("shared")) typeFiles.set("shared", "")
  for (const [file, operations] of typeFiles) {
    const source = [
      ...(modelsByFile.get(file) ?? []).map((name) => input.models.get(name)!),
      operations,
    ].join("\n\n")
    const usedTypes = sourceTypeReferences(source)
    add(`types/${file}.ts`, [
      typeImports(usedTypes, clientTypes, "@accord/client"),
      ...modelImports(usedTypes, "./", file),
      ...localHelpers(usedTypes),
      source,
    ])
  }
  if (input.validation) {
    const schemas = input.validation.declarations.join("\n\n")
    const usedTypes = sourceTypeReferences(schemas)
    add("schemas.ts", [
      ...input.validation.imports,
      ...modelImports(usedTypes, "./types/"),
      typeImports(usedTypes, clientTypes, "@accord/client"),
      ...localHelpers(usedTypes),
      schemas,
    ])
  }
  const imports: string[] = []
  const namespaces: string[] = []
  for (const group of input.groups) {
    const file = groupNames.get(group.name)!
    add(`endpoints/${file}.ts`, [
      'import { createEndpointFactory } from "@accord/client"',
      `import type { ${group.contracts.join(", ")} } from "../types/${file}.js"`,
      group.schemas.length ? `import { ${group.schemas.join(", ")} } from "../schemas.js"` : "",
      `const defineEndpoint = createEndpointFactory(${JSON.stringify(input.apiId)})`,
      `export const endpoints = ${group.endpoints}`,
    ])
    imports.push(`import { endpoints as ${file}Endpoints } from "./endpoints/${file}.js"`)
    namespaces.push(`${JSON.stringify(group.name)}: ${file}Endpoints`)
  }
  add("index.ts", [
    ...imports,
    ...[...typeFiles.keys()].map((file) => `export type * from "./types/${file}.js"`),
    input.validation ? 'export * from "./schemas.js"' : "",
    `export const api = {\n${namespaces.join(",\n")}\n}`,
  ])
  return files
}
