import type {
  NormalizedApi,
  NormalizedOperation,
  NormalizedParameter,
  NormalizedRequestBody,
} from "./types.js"

interface RenderNode {
  endpoint?: NormalizedOperation
  readonly children: Map<string, RenderNode>
}

export function renderGeneratedModule(api: NormalizedApi, openApiTypesSource: string): string {
  const lines: string[] = [
    "/* This file was generated by @accord/codegen. Do not edit manually. */",
    'import type { EndpointDescriptor, ErrorOf, InputOf, ResponseOf, ResponsesOf } from "@accord/client"',
    "",
    openApiTypesSource.trim(),
    "",
    ...renderTypeHelpers(),
    "",
  ]

  for (const operation of api.operations) {
    lines.push(...renderOperationTypes(operation), "")
  }

  lines.push(`export const api = ${renderApiTree(api)}`, "", ...renderExportedTypes(api), "")
  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n")}\n`
}

export function renderNormalizedApi(api: NormalizedApi): string {
  return `${JSON.stringify(api, null, 2)}\n`
}

function renderTypeHelpers(): string[] {
  return [
    "type AccordOperation<TPath extends keyof paths, TMethod extends PropertyKey> =",
    "  TMethod extends keyof paths[TPath] ? NonNullable<paths[TPath][TMethod]> : never",
    "",
    "type AccordParameterGroup<TOperation, TLocation extends PropertyKey> =",
    "  TOperation extends { parameters?: infer TParameters }",
    "    ? NonNullable<TParameters> extends infer TGroups",
    "      ? TGroups extends object",
    "        ? TLocation extends keyof TGroups",
    "          ? NonNullable<TGroups[TLocation]> extends object",
    "            ? NonNullable<TGroups[TLocation]>",
    "            : {}",
    "          : {}",
    "        : {}",
    "      : {}",
    "    : {}",
    "",
    "type AccordRename<TValue, TMap extends object> = {",
    "  [TKey in keyof TValue as TKey extends keyof TMap",
    "    ? TMap[TKey] extends PropertyKey",
    "      ? TMap[TKey]",
    "      : TKey",
    "    : TKey]: TValue[TKey]",
    "}",
    "",
    "type AccordRequestBody<TOperation, TContentType extends PropertyKey> =",
    "  TOperation extends { requestBody?: infer TRequestBody }",
    "    ? NonNullable<TRequestBody> extends { content: infer TContent }",
    "      ? TContentType extends keyof TContent",
    "        ? TContent[TContentType]",
    "        : never",
    "      : never",
    "    : never",
    "",
    "type AccordResponsesObject<TOperation> =",
    "  TOperation extends { responses: infer TResponses } ? TResponses : {}",
    "",
    "type AccordResponsePayload<TResponse> =",
    "  TResponse extends { content: infer TContent }",
    "    ? TContent extends object",
    "      ? TContent[keyof TContent]",
    "      : undefined",
    "    : undefined",
    "",
    "type AccordResponseAt<TOperation, TStatus extends PropertyKey> =",
    "  TStatus extends keyof AccordResponsesObject<TOperation>",
    "    ? AccordResponsePayload<AccordResponsesObject<TOperation>[TStatus]>",
    "    : never",
    "",
    "type AccordResponseUnion<TOperation, TStatuses extends PropertyKey> =",
    "  TStatuses extends PropertyKey ? AccordResponseAt<TOperation, TStatuses> : never",
    "",
    "type AccordUnknownIfNever<TValue> = [TValue] extends [never] ? unknown : TValue",
    "",
    "type AccordResponseMap<TOperation, TStatuses extends PropertyKey> = {",
    "  [TStatus in TStatuses]: AccordResponseAt<TOperation, TStatus>",
    "}",
  ]
}

function renderOperationTypes(operation: NormalizedOperation): string[] {
  const prefix = `Accord${operation.typeName}`
  const operationType = `${prefix}Operation`
  const endpointTypes = `${prefix}EndpointTypes`
  const pathMap = parameterRenameMap(operation.parameters, "path")
  const queryMap = parameterRenameMap(operation.parameters, "query")
  const headerMap = parameterRenameMap(operation.parameters, "header")
  const cookieMap = parameterRenameMap(operation.parameters, "cookie")
  const successStatuses = operation.responses
    .map((response) => response.status)
    .filter(isSuccessStatus)
  const errorStatuses = operation.responses
    .map((response) => response.status)
    .filter((status) => !isSuccessStatus(status))
  const allStatuses = operation.responses.map((response) => response.status)
  const body = operation.requestBody
    ? `AccordRequestBody<${operationType}, ${JSON.stringify(operation.requestBody.contentType)}>`
    : "never"

  return [
    `type ${operationType} = AccordOperation<${JSON.stringify(operation.path)}, ${JSON.stringify(operation.methodKey)}>`,
    `type ${endpointTypes} = {`,
    `  readonly path: AccordRename<AccordParameterGroup<${operationType}, "path">, ${renderStringMapType(pathMap)}>`,
    `  readonly query: AccordRename<AccordParameterGroup<${operationType}, "query">, ${renderStringMapType(queryMap)}>`,
    `  readonly headers: AccordRename<AccordParameterGroup<${operationType}, "header">, ${renderStringMapType(headerMap)}>`,
    `  readonly cookies: AccordRename<AccordParameterGroup<${operationType}, "cookie">, ${renderStringMapType(cookieMap)}>`,
    `  readonly body: ${body}`,
    `  readonly bodyRequired: ${operation.requestBody?.required === true ? "true" : "false"}`,
    `  readonly response: AccordUnknownIfNever<AccordResponseUnion<${operationType}, ${renderStatusUnion(successStatuses)}>>`,
    `  readonly error: AccordUnknownIfNever<AccordResponseUnion<${operationType}, ${renderStatusUnion(errorStatuses)}>>`,
    `  readonly responses: AccordResponseMap<${operationType}, ${renderStatusUnion(allStatuses)}>`,
    "}",
  ]
}

function parameterRenameMap(
  parameters: readonly NormalizedParameter[],
  location: NormalizedParameter["in"],
): Readonly<Record<string, string>> {
  return Object.fromEntries(
    parameters
      .filter((parameter) => parameter.in === location)
      .map((parameter) => [parameter.name, parameter.inputName]),
  )
}

function renderStringMapType(map: Readonly<Record<string, string>>): string {
  const entries = Object.entries(map)
  if (entries.length === 0) return "{}"
  return `{ ${entries.map(([key, value]) => `${JSON.stringify(key)}: ${JSON.stringify(value)}`).join("; ")} }`
}

function isSuccessStatus(status: number | string): boolean {
  return (typeof status === "number" && status >= 200 && status < 300) || status === "2XX"
}

function renderStatusUnion(statuses: readonly (number | string)[]): string {
  if (statuses.length === 0) return "never"
  return [...new Set(statuses)]
    .map((status) => (typeof status === "number" ? String(status) : JSON.stringify(status)))
    .join(" | ")
}

function renderApiTree(api: NormalizedApi): string {
  const root: RenderNode = { children: new Map() }
  for (const operation of api.operations) {
    let node = root
    for (const segment of [...operation.namespace, operation.operationName]) {
      let child = node.children.get(segment)
      if (!child) {
        child = { children: new Map() }
        node.children.set(segment, child)
      }
      node = child
    }
    node.endpoint = operation
  }
  return renderNode(root, 0)
}

function renderNode(node: RenderNode, depth: number): string {
  if (node.endpoint) return renderEndpoint(node.endpoint, depth)
  const indentation = "  ".repeat(depth)
  const childIndentation = "  ".repeat(depth + 1)
  const entries = [...node.children.entries()].sort(([left], [right]) => left.localeCompare(right))
  if (entries.length === 0) return "{} as const"
  const body = entries
    .map(
      ([key, child]) =>
        `${childIndentation}${JSON.stringify(key)}: ${renderNode(child, depth + 1)}`,
    )
    .join(",\n")
  return `{\n${body},\n${indentation}} as const`
}

function renderEndpoint(operation: NormalizedOperation, depth: number): string {
  const descriptor = endpointRuntimeDescriptor(operation)
  const json = JSON.stringify(descriptor, null, 2)
    .split("\n")
    .map((line, index) => (index === 0 ? line : `${"  ".repeat(depth)}${line}`))
    .join("\n")
  const endpointType = `EndpointDescriptor<Accord${operation.typeName}EndpointTypes, ${JSON.stringify(operation.bodyMode)}, ${JSON.stringify(operation.operationKind)}>`
  return `(${json} as const satisfies ${endpointType}) as ${endpointType}`
}

function endpointRuntimeDescriptor(operation: NormalizedOperation): object {
  return {
    kind: "endpoint",
    method: operation.method,
    path: operation.path,
    ...(operation.operationId !== undefined ? { operationId: operation.operationId } : {}),
    operationKind: operation.operationKind,
    bodyMode: operation.bodyMode,
    parameters: operation.parameters,
    ...(operation.requestBody !== undefined
      ? { requestBody: publicRequestBody(operation.requestBody) }
      : {}),
    responses: operation.responses,
  }
}

function publicRequestBody(requestBody: NormalizedRequestBody): object {
  return {
    required: requestBody.required,
    contentType: requestBody.contentType,
    contentTypes: requestBody.contentTypes,
    fields: requestBody.fields,
    ...(requestBody.encoding !== undefined ? { encoding: requestBody.encoding } : {}),
  }
}

function renderExportedTypes(api: NormalizedApi): string[] {
  const lines = ["export namespace AccordTypes {"]
  for (const operation of api.operations) {
    const name = operation.typeName
    const access = ["api", ...operation.namespace, operation.operationName]
      .map((segment, index) => (index === 0 ? segment : `[${JSON.stringify(segment)}]`))
      .join("")
    lines.push(
      `  export type ${name}Endpoint = typeof ${access}`,
      `  export type ${name}Input = InputOf<${name}Endpoint>`,
      `  export type ${name}Response = ResponseOf<${name}Endpoint>`,
      `  export type ${name}Error = ErrorOf<${name}Endpoint>`,
      `  export type ${name}Responses = ResponsesOf<${name}Endpoint>`,
    )
  }
  lines.push("}")
  return lines
}
