import ts from "typescript"
import { sanitizeIdentifier } from "./naming.js"
import type { ValidationSource } from "./validation-adapter.js"

export const generatedHeader =
  "/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */"

export const typeHelpers = [
  "type AccordSimplify<T> = T extends unknown ? { [K in keyof T]: T[K] } : never",
  "type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T",
  "type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T",
]
const helperNames = ["AccordSimplify", "AccordObjectConstraints", "AccordArrayConstraints"]
const clientTypes = ["BinaryUpload", "HttpResult", "RequestOptions", "StatusRange"]

export function formatSource(source: string): string {
  return ts
    .createPrinter({ newLine: ts.NewLineKind.LineFeed })
    .printFile(
      ts.createSourceFile("sdk.ts", source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS),
    )
}

/** The TS printer leaves named imports/exports on one line, even for large APIs. */
function formatModule(source: string): string {
  let formatted = formatSource(source)
  const file = ts.createSourceFile("module.ts", formatted, ts.ScriptTarget.Latest, true)
  for (const statement of [...file.statements].reverse()) {
    const bindings = ts.isImportDeclaration(statement)
      ? statement.importClause?.namedBindings
      : ts.isExportDeclaration(statement)
        ? statement.exportClause
        : undefined
    if (!bindings || (!ts.isNamedImports(bindings) && !ts.isNamedExports(bindings))) continue
    if (statement.getText(file).length <= 100 || bindings.elements.length < 2) continue
    const names = bindings.elements.map((element) => `    ${element.getText(file)}`)
    formatted =
      formatted.slice(0, bindings.getStart(file)) +
      `{\n${names.join(",\n")}\n}` +
      formatted.slice(bindings.getEnd())
  }
  return formatted
}

interface EndpointGroup {
  readonly name: string
  readonly types: string
  readonly contracts: readonly string[]
  readonly schemas: readonly string[]
  readonly endpoints: string
}

interface ModuleInput {
  readonly apiId: string
  readonly models: ReadonlyMap<string, string>
  readonly groups: readonly EndpointGroup[]
  readonly validation: ValidationSource | undefined
}

/** Import only referenced types, keeping public declarations unqualified and readable. */
function typeImports(source: string, candidates: readonly string[], from: string): string {
  const available = new Set(candidates)
  const used = new Set<string>()
  const visit = (node: ts.Node, shadowed: ReadonlySet<string>): void => {
    const scoped = new Set(shadowed)
    if (ts.isTypeAliasDeclaration(node) || ts.isFunctionTypeNode(node))
      for (const parameter of node.typeParameters ?? []) scoped.add(parameter.name.text)
    if (ts.isMappedTypeNode(node)) scoped.add(node.typeParameter.name.text)
    if (ts.isTypeReferenceNode(node) && ts.isIdentifier(node.typeName)) {
      const name = node.typeName.text
      if (available.has(name) && !scoped.has(name)) used.add(name)
    }
    ts.forEachChild(node, (child) => visit(child, scoped))
  }
  visit(ts.createSourceFile("module.ts", source, ts.ScriptTarget.Latest, true), new Set())
  return used.size
    ? `import type { ${[...used].sort().join(", ")} } from ${JSON.stringify(from)}`
    : ""
}

function groupFileNames(groups: readonly EndpointGroup[]): ReadonlyMap<string, string> {
  const names = new Map<string, string>()
  const used = new Set<string>()
  for (const group of groups) {
    let core = sanitizeIdentifier(group.name)
    // Keep filenames portable, including on case-insensitive Windows filesystems.
    if (/^(?:con|prn|aux|nul|com[0-9]|lpt[0-9])$/i.test(core)) core += "Api"
    let name = core
    for (let index = 2; used.has(name.toLowerCase()); index++) name = `${core}${index}`
    used.add(name.toLowerCase())
    names.set(group.name, name)
  }
  return names
}

export function renderModules(input: ModuleInput) {
  const files: Record<string, string> = {}
  const add = (path: string, parts: readonly string[]) => {
    files[path] = formatModule([generatedHeader, ...parts.filter(Boolean), ""].join("\n\n"))
  }
  const models = [...input.models.values()].join("\n\n")
  const modelNames = [...input.models.keys()]
  const internalNames = [...modelNames, ...helperNames]
  add("models.ts", [
    typeImports(models, clientTypes, "@accord/client"),
    ...typeHelpers.map((helper) => `export ${helper}`),
    models,
  ])
  if (input.validation) {
    const schemas = input.validation.declarations.join("\n\n")
    add("schemas.ts", [
      ...input.validation.imports,
      typeImports(schemas, internalNames, "./models.js"),
      typeImports(schemas, clientTypes, "@accord/client"),
      schemas,
    ])
  }
  const groupNames = groupFileNames(input.groups)
  const imports: string[] = []
  const exports: string[] = []
  const namespaces: string[] = []
  for (const group of input.groups) {
    const file = groupNames.get(group.name)!
    add(`types/${file}.ts`, [
      typeImports(group.types, clientTypes, "@accord/client"),
      typeImports(group.types, internalNames, "../models.js"),
      group.types,
    ])
    add(`endpoints/${file}.ts`, [
      'import { createEndpointFactory } from "@accord/client"',
      `import type { ${group.contracts.join(", ")} } from "../types/${file}.js"`,
      group.schemas.length ? `import { ${group.schemas.join(", ")} } from "../schemas.js"` : "",
      `const defineEndpoint = createEndpointFactory(${JSON.stringify(input.apiId)})`,
      `export const endpoints = ${group.endpoints}`,
    ])
    imports.push(`import { endpoints as ${file}Endpoints } from "./endpoints/${file}.js"`)
    exports.push(`export type * from "./types/${file}.js"`)
    namespaces.push(`${JSON.stringify(group.name)}: ${file}Endpoints`)
  }
  add("index.ts", [
    ...imports,
    modelNames.length ? `export type { ${modelNames.join(", ")} } from "./models.js"` : "",
    ...exports,
    input.validation ? 'export * from "./schemas.js"' : "",
    `export const api = {\n${namespaces.join(",\n")}\n}`,
  ])
  return files
}
