import type { ValidationFunction } from "@accord/client/validation"
export declare const check0: ValidationFunction
export declare const check1: ValidationFunction
export declare const check2: ValidationFunction
export declare const check3: ValidationFunction
export declare const check4: ValidationFunction
export declare const check5: ValidationFunction
export declare const check6: ValidationFunction
export declare const check7: ValidationFunction
export declare const check8: ValidationFunction
export declare const check9: ValidationFunction
export declare const check10: ValidationFunction
export declare const check11: ValidationFunction
export declare const check12: ValidationFunction
export declare const check13: ValidationFunction
export declare const check14: ValidationFunction
export declare const check15: ValidationFunction
export declare const check16: ValidationFunction
export declare const check17: ValidationFunction
export declare const check18: ValidationFunction
export declare const check19: ValidationFunction
export declare const check20: ValidationFunction
export declare const check21: ValidationFunction
export declare const check22: ValidationFunction
export declare const check23: ValidationFunction
export declare const check24: ValidationFunction
export declare const check25: ValidationFunction
export declare const check26: ValidationFunction
export declare const check27: ValidationFunction
export declare const check28: ValidationFunction
export declare const check29: ValidationFunction
export declare const check30: ValidationFunction
export declare const check31: ValidationFunction
export declare const check32: ValidationFunction
export declare const check33: ValidationFunction
export declare const check34: ValidationFunction
export declare const check35: ValidationFunction
export declare const check36: ValidationFunction
export declare const check37: ValidationFunction
export declare const check38: ValidationFunction
export declare const check39: ValidationFunction
export declare const check40: ValidationFunction
export declare const check41: ValidationFunction
export declare const check42: ValidationFunction
export declare const check43: ValidationFunction
export declare const check44: ValidationFunction
export declare const check45: ValidationFunction
export declare const check46: ValidationFunction
export declare const check47: ValidationFunction
export declare const check48: ValidationFunction
export declare const check49: ValidationFunction
export declare const check50: ValidationFunction
export declare const check51: ValidationFunction
export declare const check52: ValidationFunction
export declare const check53: ValidationFunction
export declare const check54: ValidationFunction
export declare const check55: ValidationFunction
export declare const check56: ValidationFunction
export declare const check57: ValidationFunction
export declare const check58: ValidationFunction
export declare const check59: ValidationFunction
export declare const check60: ValidationFunction
export declare const check61: ValidationFunction
export declare const check62: ValidationFunction
export declare const check63: ValidationFunction
export declare const check64: ValidationFunction
export declare const check65: ValidationFunction
export declare const check66: ValidationFunction
export declare const check67: ValidationFunction
export declare const check68: ValidationFunction
export declare const check69: ValidationFunction
export declare const check70: ValidationFunction
export declare const check71: ValidationFunction
export declare const check72: ValidationFunction
export declare const check73: ValidationFunction
