/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { defineApi } from "@accord/client";
import { endpoints as documentsEndpoints } from "./endpoints/documents.js";
import { endpoints as investorsEndpoints } from "./endpoints/investors.js";
import { endpoints as jobsEndpoints } from "./endpoints/jobs.js";
import { endpoints as offeringsEndpoints } from "./endpoints/offerings.js";
import { endpoints as subscriptionsEndpoints } from "./endpoints/subscriptions.js";
export type * from "./types/documents.js";
export type * from "./types/investors.js";
export type * from "./types/jobs.js";
export type * from "./types/offerings.js";
export type * from "./types/subscriptions.js";
export type * from "./types/shared.js";
export * from "./schemas.js";
export const api = defineApi("dc085c6fffabdb3b", {
    "documents": documentsEndpoints,
    "investors": investorsEndpoints,
    "jobs": jobsEndpoints,
    "offerings": offeringsEndpoints,
    "subscriptions": subscriptionsEndpoints
});
