/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createQueryHooks } from "@accord/react-query";
export const { Provider: MarketProvider, useQuery: useMarket, useMutation: useMarketMutation } = createQueryHooks();
export {
    apiQuery as marketQuery,
    apiQueryResponse as marketQueryResponse,
    apiQueryKey as marketQueryKey,
    apiMutation as marketMutation,
    apiMutationCall as marketMutationCall,
    apiMutationKey as marketMutationKey
} from "@accord/react-query";
