/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { z } from "zod";
const DocumentDtoSchema = z.strictObject({
    "category": z.intersection(z.string(), z.union([z.literal("terms"), z.literal("prospectus"), z.literal("other")])),
    "filename": z.string(),
    "id": z.uuid(),
    "note": z.string().optional(),
    "offeringId": z.uuid(),
    "size": z.number().refine(Number.isInteger, "Expected integer").gte(0)
});
export const GetDocument200Schema = DocumentDtoSchema;
const ErrorDtoSchema = z.strictObject({
    "code": z.string(),
    "details": z.array(z.string()).optional(),
    "message": z.string(),
    "statusCode": z.number().refine(Number.isInteger, "Expected integer")
});
export const GetDocument400Schema = ErrorDtoSchema;
export const GetDocument401Schema = ErrorDtoSchema;
export const GetDocument404Schema = ErrorDtoSchema;
export const DeleteDocument400Schema = ErrorDtoSchema;
export const DeleteDocument401Schema = ErrorDtoSchema;
export const DeleteDocument404Schema = ErrorDtoSchema;
export const DownloadDocument200Schema = z.instanceof(ArrayBuffer);
export const DownloadDocument400Schema = ErrorDtoSchema;
export const DownloadDocument401Schema = ErrorDtoSchema;
export const DownloadDocument404Schema = ErrorDtoSchema;
const IndividualInvestorDtoSchema = z.strictObject({
    "country": z.string().refine(value => [...value].length >= 2, "Must satisfy minLength: 2").refine(value => [...value].length <= 2, "Must satisfy maxLength: 2"),
    "displayName": z.string().refine(value => [...value].length >= 2, "Must satisfy minLength: 2"),
    "email": z.email(),
    "id": z.uuid(),
    "kind": z.intersection(z.string(), z.literal("individual"))
});
const CompanyInvestorDtoSchema = z.strictObject({
    "country": z.string().refine(value => [...value].length >= 2, "Must satisfy minLength: 2").refine(value => [...value].length <= 2, "Must satisfy maxLength: 2"),
    "displayName": z.string().refine(value => [...value].length >= 2, "Must satisfy minLength: 2"),
    "email": z.email(),
    "id": z.uuid(),
    "kind": z.intersection(z.string(), z.literal("company")),
    "registrationNumber": z.string().refine(value => [...value].length >= 3, "Must satisfy minLength: 3")
});
export const ListInvestors200Schema = z.array(z.xor([IndividualInvestorDtoSchema, CompanyInvestorDtoSchema]));
export const ListInvestors400Schema = ErrorDtoSchema;
export const ListInvestors401Schema = ErrorDtoSchema;
export const ListInvestors404Schema = ErrorDtoSchema;
export const CreateCompanyInvestor201Schema = CompanyInvestorDtoSchema;
export const CreateCompanyInvestor400Schema = ErrorDtoSchema;
export const CreateCompanyInvestor401Schema = ErrorDtoSchema;
export const CreateCompanyInvestor404Schema = ErrorDtoSchema;
export const CreateIndividualInvestor201Schema = IndividualInvestorDtoSchema;
export const CreateIndividualInvestor400Schema = ErrorDtoSchema;
export const CreateIndividualInvestor401Schema = ErrorDtoSchema;
export const CreateIndividualInvestor404Schema = ErrorDtoSchema;
export const GetInvestor200Schema = z.xor([IndividualInvestorDtoSchema, CompanyInvestorDtoSchema]);
export const GetInvestor400Schema = ErrorDtoSchema;
export const GetInvestor401Schema = ErrorDtoSchema;
export const GetInvestor404Schema = ErrorDtoSchema;
const SubscriptionDtoSchema = z.strictObject({
    "amount": z.string().regex(new RegExp("^[0-9]+\\.[0-9]{2}$", "u")),
    "id": z.uuid(),
    "investorId": z.uuid(),
    "metadata": z.looseObject({}).catchall(z.string()).optional(),
    "offeringId": z.uuid(),
    "status": z.intersection(z.string(), z.union([z.literal("draft"), z.literal("submitted")])),
    "submittedAt": z.union([z.iso.datetime({ offset: true }), z.null()])
});
export const GetSubmissionJob200Schema = z.strictObject({
    "id": z.uuid(),
    "result": SubscriptionDtoSchema,
    "state": z.intersection(z.string(), z.literal("completed"))
});
export const GetSubmissionJob400Schema = ErrorDtoSchema;
export const GetSubmissionJob401Schema = ErrorDtoSchema;
export const GetSubmissionJob404Schema = ErrorDtoSchema;
const CurrencySchema = z.intersection(z.string(), z.union([z.literal("EUR"), z.literal("USD")]));
const OfferingDtoSchema = z.strictObject({
    "createdAt": z.iso.datetime({ offset: true }),
    "description": z.union([z.string(), z.null()]).optional(),
    "id": z.uuid(),
    "name": z.string().refine(value => [...value].length >= 3, "Must satisfy minLength: 3"),
    "status": z.intersection(z.string(), z.union([z.literal("draft"), z.literal("open"), z.literal("closed")])),
    "tags": z.array(z.string()).optional(),
    "terms": z.strictObject({
        "closesAt": z.iso.datetime({ offset: true }),
        "currency": CurrencySchema,
        "minimumInvestment": z.string().regex(new RegExp("^[0-9]+\\.[0-9]{2}$", "u"))
    })
});
export const ListOfferings200Schema = z.strictObject({
    "items": z.array(OfferingDtoSchema),
    "limit": z.number().refine(Number.isInteger, "Expected integer").gte(1),
    "page": z.number().refine(Number.isInteger, "Expected integer").gte(1),
    "total": z.number().refine(Number.isInteger, "Expected integer").gte(0)
});
export const ListOfferings400Schema = ErrorDtoSchema;
export const ListOfferings401Schema = ErrorDtoSchema;
export const ListOfferings404Schema = ErrorDtoSchema;
export const CreateOffering201Schema = OfferingDtoSchema;
export const CreateOffering400Schema = ErrorDtoSchema;
export const CreateOffering401Schema = ErrorDtoSchema;
export const CreateOffering404Schema = ErrorDtoSchema;
export const GetOffering200Schema = OfferingDtoSchema;
export const GetOffering400Schema = ErrorDtoSchema;
export const GetOffering401Schema = ErrorDtoSchema;
export const GetOffering404Schema = ErrorDtoSchema;
export const UpdateOffering200Schema = OfferingDtoSchema;
export const UpdateOffering400Schema = ErrorDtoSchema;
export const UpdateOffering401Schema = ErrorDtoSchema;
export const UpdateOffering404Schema = ErrorDtoSchema;
export const DeleteOffering400Schema = ErrorDtoSchema;
export const DeleteOffering401Schema = ErrorDtoSchema;
export const DeleteOffering404Schema = ErrorDtoSchema;
export const DeleteOffering409Schema = ErrorDtoSchema;
export const ListDocuments200Schema = z.array(DocumentDtoSchema);
export const ListDocuments400Schema = ErrorDtoSchema;
export const ListDocuments401Schema = ErrorDtoSchema;
export const ListDocuments404Schema = ErrorDtoSchema;
export const UploadDocument201Schema = DocumentDtoSchema;
export const UploadDocument400Schema = ErrorDtoSchema;
export const UploadDocument401Schema = ErrorDtoSchema;
export const UploadDocument404Schema = ErrorDtoSchema;
export const UploadDocument413Schema = ErrorDtoSchema;
export const ExportOffering200JsonSchema = z.strictObject({
    "currency": CurrencySchema,
    "offeringId": z.uuid(),
    "subscriptionCount": z.number().refine(Number.isInteger, "Expected integer").gte(0)
});
export const ExportOffering200CsvSchema = z.string();
export const ExportOffering400Schema = ErrorDtoSchema;
export const ExportOffering401Schema = ErrorDtoSchema;
export const ExportOffering404Schema = ErrorDtoSchema;
export const ListSubscriptions200Schema = z.strictObject({
    "items": z.array(SubscriptionDtoSchema),
    "limit": z.number().refine(Number.isInteger, "Expected integer").gte(1),
    "page": z.number().refine(Number.isInteger, "Expected integer").gte(1),
    "total": z.number().refine(Number.isInteger, "Expected integer").gte(0)
});
export const ListSubscriptions400Schema = ErrorDtoSchema;
export const ListSubscriptions401Schema = ErrorDtoSchema;
export const ListSubscriptions404Schema = ErrorDtoSchema;
export const CreateSubscription201Schema = SubscriptionDtoSchema;
export const CreateSubscription400Schema = ErrorDtoSchema;
export const CreateSubscription401Schema = ErrorDtoSchema;
export const CreateSubscription404Schema = ErrorDtoSchema;
export const GetSubscription200Schema = SubscriptionDtoSchema;
export const GetSubscription400Schema = ErrorDtoSchema;
export const GetSubscription401Schema = ErrorDtoSchema;
export const GetSubscription404Schema = ErrorDtoSchema;
export const SubmitSubscription200Schema = SubscriptionDtoSchema;
export const SubmitSubscription202Schema = z.strictObject({
    "jobId": z.uuid(),
    "state": z.intersection(z.string(), z.literal("accepted"))
});
export const SubmitSubscription400Schema = ErrorDtoSchema;
export const SubmitSubscription401Schema = ErrorDtoSchema;
export const SubmitSubscription404Schema = ErrorDtoSchema;
