/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createEndpointFactory, type BinaryUpload, type HttpResult, type RequestOptions, type StatusRange } from "@accord/client";
import { z } from "zod";
type AccordSimplify<T> = T extends unknown ? {
    [K in keyof T]: T[K];
} : never;
type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T;
type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T;
export type AcceptedSubmissionDto = {
    readonly "jobId": string;
    readonly "state": "accepted" & string;
};
export type AcceptedSubmissionDtoRequest = {
    readonly "jobId": string;
    readonly "state": "accepted" & string;
};
export type CompanyInvestorDto = {
    readonly "country": string;
    readonly "displayName": string;
    readonly "email": string;
    readonly "id": string;
    readonly "kind": "company" & string;
    readonly "registrationNumber": string;
};
export type CompanyInvestorDtoRequest = {
    readonly "country": string;
    readonly "displayName": string;
    readonly "email": string;
    readonly "id"?: never;
    readonly "kind": "company" & string;
    readonly "registrationNumber": string;
};
export type CreateCompanyInvestorDto = {
    readonly "country": string;
    readonly "displayName": string;
    readonly "email": string;
    readonly "kind": "company" & string;
    readonly "onboardingNote"?: never;
    readonly "registrationNumber": string;
};
export type CreateCompanyInvestorDtoRequest = {
    readonly "country": string;
    readonly "displayName": string;
    readonly "email": string;
    readonly "kind": "company" & string;
    readonly "onboardingNote"?: string;
    readonly "registrationNumber": string;
};
export type CreateIndividualInvestorDto = {
    readonly "country": string;
    readonly "displayName": string;
    readonly "email": string;
    readonly "kind": "individual" & string;
    readonly "onboardingNote"?: never;
};
export type CreateIndividualInvestorDtoRequest = {
    readonly "country": string;
    readonly "displayName": string;
    readonly "email": string;
    readonly "kind": "individual" & string;
    readonly "onboardingNote"?: string;
};
export type Currency = ("EUR" | "USD") & string;
export type TermsDto = {
    readonly "closesAt": string;
    readonly "currency": Currency;
    readonly "minimumInvestment": string;
};
export type CreateOfferingDto = {
    readonly "description"?: string | null;
    readonly "name": string;
    readonly "tags"?: ReadonlyArray<string>;
    readonly "terms": TermsDto;
};
export type CurrencyRequest = ("EUR" | "USD") & string;
export type TermsDtoRequest = {
    readonly "closesAt": string;
    readonly "currency": CurrencyRequest;
    readonly "minimumInvestment": string;
};
export type CreateOfferingDtoRequest = {
    readonly "description"?: string | null;
    readonly "name": string;
    readonly "tags"?: ReadonlyArray<string>;
    readonly "terms": TermsDtoRequest;
};
export type CreateSubscriptionDto = {
    readonly "amount": string;
    readonly "investorId": string;
    readonly "metadata"?: {
        readonly [key: string]: string;
    };
};
export type CreateSubscriptionDtoRequest = {
    readonly "amount": string;
    readonly "investorId": string;
    readonly "metadata"?: {
        readonly [key: string]: string;
    };
};
export type DocumentCategory = ("terms" | "prospectus" | "other") & string;
export type DocumentCategoryRequest = ("terms" | "prospectus" | "other") & string;
export type DocumentDto = {
    readonly "category": DocumentCategory;
    readonly "filename": string;
    readonly "id": string;
    readonly "note"?: string;
    readonly "offeringId": string;
    readonly "size": number;
};
export type DocumentDtoRequest = {
    readonly "category": DocumentCategoryRequest;
    readonly "filename": string;
    readonly "id"?: never;
    readonly "note"?: string;
    readonly "offeringId"?: never;
    readonly "size": number;
};
export type IndividualInvestorDto = {
    readonly "country": string;
    readonly "displayName": string;
    readonly "email": string;
    readonly "id": string;
    readonly "kind": "individual" & string;
};
export type IndividualInvestorDtoRequest = {
    readonly "country": string;
    readonly "displayName": string;
    readonly "email": string;
    readonly "id"?: never;
    readonly "kind": "individual" & string;
};
export type OfferingStatus = ("draft" | "open" | "closed") & string;
export type OfferingDto = {
    readonly "createdAt": string;
    readonly "description"?: string | null;
    readonly "id": string;
    readonly "name": string;
    readonly "status": OfferingStatus;
    readonly "tags"?: ReadonlyArray<string>;
    readonly "terms": TermsDto;
};
export type OfferingStatusRequest = ("draft" | "open" | "closed") & string;
export type OfferingDtoRequest = {
    readonly "createdAt"?: never;
    readonly "description"?: string | null;
    readonly "id"?: never;
    readonly "name": string;
    readonly "status": OfferingStatusRequest;
    readonly "tags"?: ReadonlyArray<string>;
    readonly "terms": TermsDtoRequest;
};
export type OfferingDtoPage = {
    readonly "items": ReadonlyArray<OfferingDto>;
    readonly "limit": number;
    readonly "page": number;
    readonly "total": number;
};
export type OfferingDtoPageRequest = {
    readonly "items": ReadonlyArray<OfferingDtoRequest>;
    readonly "limit": number;
    readonly "page": number;
    readonly "total": number;
};
export type OfferingReportDto = {
    readonly "currency": Currency;
    readonly "offeringId": string;
    readonly "subscriptionCount": number;
};
export type OfferingReportDtoRequest = {
    readonly "currency": CurrencyRequest;
    readonly "offeringId": string;
    readonly "subscriptionCount": number;
};
export type ProblemDto = {
    readonly "code": string;
    readonly "details"?: ReadonlyArray<string>;
    readonly "message": string;
    readonly "statusCode": number;
};
export type ProblemDtoRequest = {
    readonly "code": string;
    readonly "details"?: ReadonlyArray<string>;
    readonly "message": string;
    readonly "statusCode": number;
};
export type SubscriptionStatus = ("draft" | "submitted") & string;
export type SubscriptionDto = {
    readonly "amount": string;
    readonly "id": string;
    readonly "investorId": string;
    readonly "metadata"?: {
        readonly [key: string]: string;
    };
    readonly "offeringId": string;
    readonly "status": SubscriptionStatus;
    readonly "submittedAt": string | null;
};
export type SubmissionJobDto = {
    readonly "id": string;
    readonly "result": SubscriptionDto;
    readonly "state": "completed" & string;
};
export type SubscriptionStatusRequest = ("draft" | "submitted") & string;
export type SubscriptionDtoRequest = {
    readonly "amount": string;
    readonly "id"?: never;
    readonly "investorId": string;
    readonly "metadata"?: {
        readonly [key: string]: string;
    };
    readonly "offeringId"?: never;
    readonly "status": SubscriptionStatusRequest;
    readonly "submittedAt"?: never;
};
export type SubmissionJobDtoRequest = {
    readonly "id": string;
    readonly "result": SubscriptionDtoRequest;
    readonly "state": "completed" & string;
};
export type SubscriptionDtoPage = {
    readonly "items": ReadonlyArray<SubscriptionDto>;
    readonly "limit": number;
    readonly "page": number;
    readonly "total": number;
};
export type SubscriptionDtoPageRequest = {
    readonly "items": ReadonlyArray<SubscriptionDtoRequest>;
    readonly "limit": number;
    readonly "page": number;
    readonly "total": number;
};
export type UpdateOfferingDto = {
    readonly "description"?: string | null;
    readonly "name"?: string;
    readonly "tags"?: ReadonlyArray<string>;
    readonly "terms"?: TermsDto;
};
export type UpdateOfferingDtoRequest = {
    readonly "description"?: string | null;
    readonly "name"?: string;
    readonly "tags"?: ReadonlyArray<string>;
    readonly "terms"?: TermsDtoRequest;
};
export type UploadDocumentDto = {
    readonly "category": DocumentCategory;
    readonly "file": string;
    readonly "note"?: string;
};
export type UploadDocumentDtoRequest = {
    readonly "category": DocumentCategoryRequest;
    readonly "file": string;
    readonly "note"?: string;
};
export type UploadDocumentDtoRequestForm = {
    readonly "category": DocumentCategoryRequest;
    readonly "file": BinaryUpload;
    readonly "note"?: string;
};
export type GetDocumentInput = {
    readonly "documentId": string;
};
export type GetDocumentArguments = [
    input: {
        readonly "documentId": string;
    },
    options?: RequestOptions
];
export type GetDocumentResponse = DocumentDto;
export type GetDocumentError = ProblemDto;
export type GetDocumentResponses = {
    readonly "200": DocumentDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type GetDocumentFullResponse = HttpResult<200, DocumentDto>;
export type GetDocumentContract = {
    readonly "args": GetDocumentArguments;
    readonly "input": GetDocumentInput;
    readonly "response": GetDocumentResponse;
    readonly "error": GetDocumentError;
    readonly "responses": GetDocumentResponses;
    readonly "fullResponse": GetDocumentFullResponse;
};
export type DeleteDocumentInput = {
    readonly "documentId": string;
};
export type DeleteDocumentArguments = [
    input: {
        readonly "documentId": string;
    },
    options?: RequestOptions
];
export type DeleteDocumentResponse = undefined;
export type DeleteDocumentError = ProblemDto;
export type DeleteDocumentResponses = {
    readonly "204": undefined;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type DeleteDocumentFullResponse = HttpResult<204, undefined>;
export type DeleteDocumentContract = {
    readonly "args": DeleteDocumentArguments;
    readonly "input": DeleteDocumentInput;
    readonly "response": DeleteDocumentResponse;
    readonly "error": DeleteDocumentError;
    readonly "responses": DeleteDocumentResponses;
    readonly "fullResponse": DeleteDocumentFullResponse;
};
export type DownloadDocumentInput = {
    readonly "documentId": string;
};
export type DownloadDocumentArguments = [
    input: {
        readonly "documentId": string;
    },
    options?: RequestOptions
];
export type DownloadDocumentResponse = ArrayBuffer;
export type DownloadDocumentError = ProblemDto;
export type DownloadDocumentResponses = {
    readonly "200": ArrayBuffer;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type DownloadDocumentFullResponse = HttpResult<200, ArrayBuffer>;
export type DownloadDocumentContract = {
    readonly "args": DownloadDocumentArguments;
    readonly "input": DownloadDocumentInput;
    readonly "response": DownloadDocumentResponse;
    readonly "error": DownloadDocumentError;
    readonly "responses": DownloadDocumentResponses;
    readonly "fullResponse": DownloadDocumentFullResponse;
};
export type CreateCompanyInvestorInput = CreateCompanyInvestorDtoRequest;
export type CreateCompanyInvestorArguments = [
    input: CreateCompanyInvestorDtoRequest,
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type CreateCompanyInvestorResponse = CompanyInvestorDto;
export type CreateCompanyInvestorError = ProblemDto;
export type CreateCompanyInvestorResponses = {
    readonly "201": CompanyInvestorDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type CreateCompanyInvestorFullResponse = HttpResult<201, CompanyInvestorDto>;
export type CreateCompanyInvestorContract = {
    readonly "args": CreateCompanyInvestorArguments;
    readonly "input": CreateCompanyInvestorInput;
    readonly "response": CreateCompanyInvestorResponse;
    readonly "error": CreateCompanyInvestorError;
    readonly "responses": CreateCompanyInvestorResponses;
    readonly "fullResponse": CreateCompanyInvestorFullResponse;
};
export type CreateIndividualInvestorInput = CreateIndividualInvestorDtoRequest;
export type CreateIndividualInvestorArguments = [
    input: CreateIndividualInvestorDtoRequest,
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type CreateIndividualInvestorResponse = IndividualInvestorDto;
export type CreateIndividualInvestorError = ProblemDto;
export type CreateIndividualInvestorResponses = {
    readonly "201": IndividualInvestorDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type CreateIndividualInvestorFullResponse = HttpResult<201, IndividualInvestorDto>;
export type CreateIndividualInvestorContract = {
    readonly "args": CreateIndividualInvestorArguments;
    readonly "input": CreateIndividualInvestorInput;
    readonly "response": CreateIndividualInvestorResponse;
    readonly "error": CreateIndividualInvestorError;
    readonly "responses": CreateIndividualInvestorResponses;
    readonly "fullResponse": CreateIndividualInvestorFullResponse;
};
export type GetInvestorInput = {
    readonly "investorId": string;
};
export type GetInvestorArguments = [
    input: {
        readonly "investorId": string;
    },
    options?: RequestOptions
];
export type GetInvestorResponse = IndividualInvestorDto | CompanyInvestorDto;
export type GetInvestorError = ProblemDto;
export type GetInvestorResponses = {
    readonly "200": IndividualInvestorDto | CompanyInvestorDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type GetInvestorFullResponse = HttpResult<200, IndividualInvestorDto | CompanyInvestorDto>;
export type GetInvestorContract = {
    readonly "args": GetInvestorArguments;
    readonly "input": GetInvestorInput;
    readonly "response": GetInvestorResponse;
    readonly "error": GetInvestorError;
    readonly "responses": GetInvestorResponses;
    readonly "fullResponse": GetInvestorFullResponse;
};
export type GetSubmissionJobInput = {
    readonly "jobId": string;
};
export type GetSubmissionJobArguments = [
    input: {
        readonly "jobId": string;
    },
    options?: RequestOptions
];
export type GetSubmissionJobResponse = SubmissionJobDto;
export type GetSubmissionJobError = ProblemDto;
export type GetSubmissionJobResponses = {
    readonly "200": SubmissionJobDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type GetSubmissionJobFullResponse = HttpResult<200, SubmissionJobDto>;
export type GetSubmissionJobContract = {
    readonly "args": GetSubmissionJobArguments;
    readonly "input": GetSubmissionJobInput;
    readonly "response": GetSubmissionJobResponse;
    readonly "error": GetSubmissionJobError;
    readonly "responses": GetSubmissionJobResponses;
    readonly "fullResponse": GetSubmissionJobFullResponse;
};
export type ListOfferingsInput = {
    readonly "page"?: number;
    readonly "limit"?: number;
    readonly "status"?: ReadonlyArray<OfferingStatusRequest>;
};
export type ListOfferingsArguments = [
    input?: {
        readonly "page"?: number;
        readonly "limit"?: number;
        readonly "status"?: ReadonlyArray<OfferingStatusRequest>;
    },
    options?: RequestOptions
];
export type ListOfferingsResponse = OfferingDtoPage;
export type ListOfferingsError = ProblemDto;
export type ListOfferingsResponses = {
    readonly "200": OfferingDtoPage;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type ListOfferingsFullResponse = HttpResult<200, OfferingDtoPage>;
export type ListOfferingsContract = {
    readonly "args": ListOfferingsArguments;
    readonly "input": ListOfferingsInput;
    readonly "response": ListOfferingsResponse;
    readonly "error": ListOfferingsError;
    readonly "responses": ListOfferingsResponses;
    readonly "fullResponse": ListOfferingsFullResponse;
};
export type CreateOfferingInput = CreateOfferingDtoRequest;
export type CreateOfferingArguments = [
    input: CreateOfferingDtoRequest,
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type CreateOfferingResponse = OfferingDto;
export type CreateOfferingError = ProblemDto;
export type CreateOfferingResponses = {
    readonly "201": OfferingDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type CreateOfferingFullResponse = HttpResult<201, OfferingDto>;
export type CreateOfferingContract = {
    readonly "args": CreateOfferingArguments;
    readonly "input": CreateOfferingInput;
    readonly "response": CreateOfferingResponse;
    readonly "error": CreateOfferingError;
    readonly "responses": CreateOfferingResponses;
    readonly "fullResponse": CreateOfferingFullResponse;
};
export type GetOfferingInput = {
    readonly "offeringId": string;
};
export type GetOfferingArguments = [
    input: {
        readonly "offeringId": string;
    },
    options?: RequestOptions
];
export type GetOfferingResponse = OfferingDto;
export type GetOfferingError = ProblemDto;
export type GetOfferingResponses = {
    readonly "200": OfferingDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type GetOfferingFullResponse = HttpResult<200, OfferingDto>;
export type GetOfferingContract = {
    readonly "args": GetOfferingArguments;
    readonly "input": GetOfferingInput;
    readonly "response": GetOfferingResponse;
    readonly "error": GetOfferingError;
    readonly "responses": GetOfferingResponses;
    readonly "fullResponse": GetOfferingFullResponse;
};
export type UpdateOfferingInput = {
    readonly "offeringId": string;
    readonly "body"?: UpdateOfferingDtoRequest;
};
export type UpdateOfferingArguments = [
    input: {
        readonly "offeringId": string;
        readonly "body"?: UpdateOfferingDtoRequest;
    },
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type UpdateOfferingResponse = OfferingDto;
export type UpdateOfferingError = ProblemDto;
export type UpdateOfferingResponses = {
    readonly "200": OfferingDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type UpdateOfferingFullResponse = HttpResult<200, OfferingDto>;
export type UpdateOfferingContract = {
    readonly "args": UpdateOfferingArguments;
    readonly "input": UpdateOfferingInput;
    readonly "response": UpdateOfferingResponse;
    readonly "error": UpdateOfferingError;
    readonly "responses": UpdateOfferingResponses;
    readonly "fullResponse": UpdateOfferingFullResponse;
};
export type DeleteOfferingInput = {
    readonly "offeringId": string;
};
export type DeleteOfferingArguments = [
    input: {
        readonly "offeringId": string;
    },
    options?: RequestOptions
];
export type DeleteOfferingResponse = undefined;
export type DeleteOfferingError = ProblemDto;
export type DeleteOfferingResponses = {
    readonly "204": undefined;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
    readonly "409": ProblemDto;
};
export type DeleteOfferingFullResponse = HttpResult<204, undefined>;
export type DeleteOfferingContract = {
    readonly "args": DeleteOfferingArguments;
    readonly "input": DeleteOfferingInput;
    readonly "response": DeleteOfferingResponse;
    readonly "error": DeleteOfferingError;
    readonly "responses": DeleteOfferingResponses;
    readonly "fullResponse": DeleteOfferingFullResponse;
};
export type UploadDocumentInput = AccordSimplify<{
    readonly "offeringId": string;
} & UploadDocumentDtoRequestForm>;
export type UploadDocumentArguments = [
    input: AccordSimplify<{
        readonly "offeringId": string;
    } & UploadDocumentDtoRequestForm>,
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "multipart/form-data" | `multipart/form-data;${string}`;
        };
    }
];
export type UploadDocumentResponse = DocumentDto;
export type UploadDocumentError = ProblemDto;
export type UploadDocumentResponses = {
    readonly "201": DocumentDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
    readonly "413": ProblemDto;
};
export type UploadDocumentFullResponse = HttpResult<201, DocumentDto>;
export type UploadDocumentContract = {
    readonly "args": UploadDocumentArguments;
    readonly "input": UploadDocumentInput;
    readonly "response": UploadDocumentResponse;
    readonly "error": UploadDocumentError;
    readonly "responses": UploadDocumentResponses;
    readonly "fullResponse": UploadDocumentFullResponse;
};
export type ExportOfferingInput = {
    readonly "offeringId": string;
};
export type ExportOfferingArguments = [
    input: {
        readonly "offeringId": string;
    },
    options?: RequestOptions
];
export type ExportOfferingResponse = OfferingReportDto | string;
export type ExportOfferingError = ProblemDto;
export type ExportOfferingResponses = {
    readonly "200": OfferingReportDto | string;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type ExportOfferingFullResponse = (HttpResult<200, OfferingReportDto> & {
    readonly "mediaType": "application/json";
}) | (HttpResult<200, string> & {
    readonly "mediaType": "text/csv";
});
export type ExportOfferingContract = {
    readonly "args": ExportOfferingArguments;
    readonly "input": ExportOfferingInput;
    readonly "response": ExportOfferingResponse;
    readonly "error": ExportOfferingError;
    readonly "responses": ExportOfferingResponses;
    readonly "fullResponse": ExportOfferingFullResponse;
};
export type ListSubscriptionsInput = {
    readonly "offeringId": string;
    readonly "page"?: number;
    readonly "limit"?: number;
    readonly "investorId"?: string;
};
export type ListSubscriptionsArguments = [
    input: {
        readonly "offeringId": string;
        readonly "page"?: number;
        readonly "limit"?: number;
        readonly "investorId"?: string;
    },
    options?: RequestOptions
];
export type ListSubscriptionsResponse = SubscriptionDtoPage;
export type ListSubscriptionsError = ProblemDto;
export type ListSubscriptionsResponses = {
    readonly "200": SubscriptionDtoPage;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type ListSubscriptionsFullResponse = HttpResult<200, SubscriptionDtoPage>;
export type ListSubscriptionsContract = {
    readonly "args": ListSubscriptionsArguments;
    readonly "input": ListSubscriptionsInput;
    readonly "response": ListSubscriptionsResponse;
    readonly "error": ListSubscriptionsError;
    readonly "responses": ListSubscriptionsResponses;
    readonly "fullResponse": ListSubscriptionsFullResponse;
};
export type CreateSubscriptionInput = AccordSimplify<{
    readonly "offeringId": string;
} & CreateSubscriptionDtoRequest>;
export type CreateSubscriptionArguments = [
    input: AccordSimplify<{
        readonly "offeringId": string;
    } & CreateSubscriptionDtoRequest>,
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type CreateSubscriptionResponse = SubscriptionDto;
export type CreateSubscriptionError = ProblemDto;
export type CreateSubscriptionResponses = {
    readonly "201": SubscriptionDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type CreateSubscriptionFullResponse = HttpResult<201, SubscriptionDto>;
export type CreateSubscriptionContract = {
    readonly "args": CreateSubscriptionArguments;
    readonly "input": CreateSubscriptionInput;
    readonly "response": CreateSubscriptionResponse;
    readonly "error": CreateSubscriptionError;
    readonly "responses": CreateSubscriptionResponses;
    readonly "fullResponse": CreateSubscriptionFullResponse;
};
export type GetSubscriptionInput = {
    readonly "subscriptionId": string;
};
export type GetSubscriptionArguments = [
    input: {
        readonly "subscriptionId": string;
    },
    options?: RequestOptions
];
export type GetSubscriptionResponse = SubscriptionDto;
export type GetSubscriptionError = ProblemDto;
export type GetSubscriptionResponses = {
    readonly "200": SubscriptionDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type GetSubscriptionFullResponse = HttpResult<200, SubscriptionDto>;
export type GetSubscriptionContract = {
    readonly "args": GetSubscriptionArguments;
    readonly "input": GetSubscriptionInput;
    readonly "response": GetSubscriptionResponse;
    readonly "error": GetSubscriptionError;
    readonly "responses": GetSubscriptionResponses;
    readonly "fullResponse": GetSubscriptionFullResponse;
};
export type SubmitSubscriptionInput = {
    readonly "subscriptionId": string;
    readonly "background"?: boolean;
};
export type SubmitSubscriptionArguments = [
    input: {
        readonly "subscriptionId": string;
        readonly "background"?: boolean;
    },
    options?: RequestOptions
];
export type SubmitSubscriptionResponse = {
    readonly "status": 200;
    readonly "data": SubscriptionDto;
} | {
    readonly "status": 202;
    readonly "data": AcceptedSubmissionDto;
};
export type SubmitSubscriptionError = ProblemDto;
export type SubmitSubscriptionResponses = {
    readonly "200": SubscriptionDto;
    readonly "202": AcceptedSubmissionDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type SubmitSubscriptionFullResponse = HttpResult<200, SubscriptionDto> | HttpResult<202, AcceptedSubmissionDto>;
export type SubmitSubscriptionContract = {
    readonly "args": SubmitSubscriptionArguments;
    readonly "input": SubmitSubscriptionInput;
    readonly "response": SubmitSubscriptionResponse;
    readonly "error": SubmitSubscriptionError;
    readonly "responses": SubmitSubscriptionResponses;
    readonly "fullResponse": SubmitSubscriptionFullResponse;
};
const DocumentDtoSchema = z.strictObject({
    "category": z.intersection(z.string(), z.union([z.literal("terms"), z.literal("prospectus"), z.literal("other")])),
    "filename": z.string(),
    "id": z.uuid(),
    "note": z.string().optional(),
    "offeringId": z.uuid(),
    "size": z.number().refine(Number.isInteger, "Expected integer").gte(0)
});
export const GetDocument200Schema = DocumentDtoSchema;
const ProblemDtoSchema = z.strictObject({
    "code": z.string(),
    "details": z.array(z.string()).optional(),
    "message": z.string(),
    "statusCode": z.number().refine(Number.isInteger, "Expected integer")
});
export const GetDocument400Schema = ProblemDtoSchema;
export const GetDocument401Schema = ProblemDtoSchema;
export const GetDocument404Schema = ProblemDtoSchema;
export const DeleteDocument400Schema = ProblemDtoSchema;
export const DeleteDocument401Schema = ProblemDtoSchema;
export const DeleteDocument404Schema = ProblemDtoSchema;
export const DownloadDocument200Schema = z.instanceof(ArrayBuffer);
export const DownloadDocument400Schema = ProblemDtoSchema;
export const DownloadDocument401Schema = ProblemDtoSchema;
export const DownloadDocument404Schema = ProblemDtoSchema;
const CompanyInvestorDtoSchema = z.strictObject({
    "country": z.string().refine(value => [...value].length >= 2, "Must satisfy minLength: 2").refine(value => [...value].length <= 2, "Must satisfy maxLength: 2"),
    "displayName": z.string().refine(value => [...value].length >= 2, "Must satisfy minLength: 2"),
    "email": z.email(),
    "id": z.uuid(),
    "kind": z.intersection(z.string(), z.literal("company")),
    "registrationNumber": z.string().refine(value => [...value].length >= 3, "Must satisfy minLength: 3")
});
export const CreateCompanyInvestor201Schema = CompanyInvestorDtoSchema;
export const CreateCompanyInvestor400Schema = ProblemDtoSchema;
export const CreateCompanyInvestor401Schema = ProblemDtoSchema;
export const CreateCompanyInvestor404Schema = ProblemDtoSchema;
const IndividualInvestorDtoSchema = z.strictObject({
    "country": z.string().refine(value => [...value].length >= 2, "Must satisfy minLength: 2").refine(value => [...value].length <= 2, "Must satisfy maxLength: 2"),
    "displayName": z.string().refine(value => [...value].length >= 2, "Must satisfy minLength: 2"),
    "email": z.email(),
    "id": z.uuid(),
    "kind": z.intersection(z.string(), z.literal("individual"))
});
export const CreateIndividualInvestor201Schema = IndividualInvestorDtoSchema;
export const CreateIndividualInvestor400Schema = ProblemDtoSchema;
export const CreateIndividualInvestor401Schema = ProblemDtoSchema;
export const CreateIndividualInvestor404Schema = ProblemDtoSchema;
export const GetInvestor200Schema = z.xor([IndividualInvestorDtoSchema, CompanyInvestorDtoSchema]);
export const GetInvestor400Schema = ProblemDtoSchema;
export const GetInvestor401Schema = ProblemDtoSchema;
export const GetInvestor404Schema = ProblemDtoSchema;
const SubscriptionDtoSchema = z.strictObject({
    "amount": z.string().regex(new RegExp("^[0-9]+\\.[0-9]{2}$", "u")),
    "id": z.uuid(),
    "investorId": z.uuid(),
    "metadata": z.looseObject({}).catchall(z.string()).optional(),
    "offeringId": z.uuid(),
    "status": z.intersection(z.string(), z.union([z.literal("draft"), z.literal("submitted")])),
    "submittedAt": z.union([z.iso.datetime({ offset: true }), z.null()])
});
export const GetSubmissionJob200Schema = z.strictObject({
    "id": z.uuid(),
    "result": SubscriptionDtoSchema,
    "state": z.intersection(z.string(), z.literal("completed"))
});
export const GetSubmissionJob400Schema = ProblemDtoSchema;
export const GetSubmissionJob401Schema = ProblemDtoSchema;
export const GetSubmissionJob404Schema = ProblemDtoSchema;
const CurrencySchema = z.intersection(z.string(), z.union([z.literal("EUR"), z.literal("USD")]));
const OfferingDtoSchema = z.strictObject({
    "createdAt": z.iso.datetime({ offset: true }),
    "description": z.union([z.string(), z.null()]).optional(),
    "id": z.uuid(),
    "name": z.string().refine(value => [...value].length >= 3, "Must satisfy minLength: 3"),
    "status": z.intersection(z.string(), z.union([z.literal("draft"), z.literal("open"), z.literal("closed")])),
    "tags": z.array(z.string()).optional(),
    "terms": z.strictObject({
        "closesAt": z.iso.datetime({ offset: true }),
        "currency": CurrencySchema,
        "minimumInvestment": z.string().regex(new RegExp("^[0-9]+\\.[0-9]{2}$", "u"))
    })
});
export const ListOfferings200Schema = z.strictObject({
    "items": z.array(OfferingDtoSchema),
    "limit": z.number().refine(Number.isInteger, "Expected integer").gte(1),
    "page": z.number().refine(Number.isInteger, "Expected integer").gte(1),
    "total": z.number().refine(Number.isInteger, "Expected integer").gte(0)
});
export const ListOfferings400Schema = ProblemDtoSchema;
export const ListOfferings401Schema = ProblemDtoSchema;
export const ListOfferings404Schema = ProblemDtoSchema;
export const CreateOffering201Schema = OfferingDtoSchema;
export const CreateOffering400Schema = ProblemDtoSchema;
export const CreateOffering401Schema = ProblemDtoSchema;
export const CreateOffering404Schema = ProblemDtoSchema;
export const GetOffering200Schema = OfferingDtoSchema;
export const GetOffering400Schema = ProblemDtoSchema;
export const GetOffering401Schema = ProblemDtoSchema;
export const GetOffering404Schema = ProblemDtoSchema;
export const UpdateOffering200Schema = OfferingDtoSchema;
export const UpdateOffering400Schema = ProblemDtoSchema;
export const UpdateOffering401Schema = ProblemDtoSchema;
export const UpdateOffering404Schema = ProblemDtoSchema;
export const DeleteOffering400Schema = ProblemDtoSchema;
export const DeleteOffering401Schema = ProblemDtoSchema;
export const DeleteOffering404Schema = ProblemDtoSchema;
export const DeleteOffering409Schema = ProblemDtoSchema;
export const UploadDocument201Schema = DocumentDtoSchema;
export const UploadDocument400Schema = ProblemDtoSchema;
export const UploadDocument401Schema = ProblemDtoSchema;
export const UploadDocument404Schema = ProblemDtoSchema;
export const UploadDocument413Schema = ProblemDtoSchema;
export const ExportOffering200JsonSchema = z.strictObject({
    "currency": CurrencySchema,
    "offeringId": z.uuid(),
    "subscriptionCount": z.number().refine(Number.isInteger, "Expected integer").gte(0)
});
export const ExportOffering200CsvSchema = z.string();
export const ExportOffering400Schema = ProblemDtoSchema;
export const ExportOffering401Schema = ProblemDtoSchema;
export const ExportOffering404Schema = ProblemDtoSchema;
export const ListSubscriptions200Schema = z.strictObject({
    "items": z.array(SubscriptionDtoSchema),
    "limit": z.number().refine(Number.isInteger, "Expected integer").gte(1),
    "page": z.number().refine(Number.isInteger, "Expected integer").gte(1),
    "total": z.number().refine(Number.isInteger, "Expected integer").gte(0)
});
export const ListSubscriptions400Schema = ProblemDtoSchema;
export const ListSubscriptions401Schema = ProblemDtoSchema;
export const ListSubscriptions404Schema = ProblemDtoSchema;
export const CreateSubscription201Schema = SubscriptionDtoSchema;
export const CreateSubscription400Schema = ProblemDtoSchema;
export const CreateSubscription401Schema = ProblemDtoSchema;
export const CreateSubscription404Schema = ProblemDtoSchema;
export const GetSubscription200Schema = SubscriptionDtoSchema;
export const GetSubscription400Schema = ProblemDtoSchema;
export const GetSubscription401Schema = ProblemDtoSchema;
export const GetSubscription404Schema = ProblemDtoSchema;
export const SubmitSubscription200Schema = SubscriptionDtoSchema;
export const SubmitSubscription202Schema = z.strictObject({
    "jobId": z.uuid(),
    "state": z.intersection(z.string(), z.literal("accepted"))
});
export const SubmitSubscription400Schema = ProblemDtoSchema;
export const SubmitSubscription401Schema = ProblemDtoSchema;
export const SubmitSubscription404Schema = ProblemDtoSchema;
const defineEndpoint = createEndpointFactory("840f78478a19d000");
export const api = {
    "documents": {
        "getDocument": defineEndpoint<GetDocumentContract, "query">({
            "method": "GET",
            "path": "/api/v1/documents/{documentId}",
            "id": "getDocument",
            "kind": "query",
            "pathParams": [
                {
                    "name": "documentId"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": GetDocument200Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": GetDocument400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": GetDocument401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": GetDocument404Schema
                }
            }
        }),
        "deleteDocument": defineEndpoint<DeleteDocumentContract, "mutation">({
            "method": "DELETE",
            "path": "/api/v1/documents/{documentId}",
            "id": "deleteDocument",
            "kind": "mutation",
            "pathParams": [
                {
                    "name": "documentId"
                }
            ],
            "responses": {
                "204": {},
                "400": {
                    "mediaType": "application/json",
                    "schema": DeleteDocument400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": DeleteDocument401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": DeleteDocument404Schema
                }
            }
        }),
        "downloadDocument": defineEndpoint<DownloadDocumentContract, "query">({
            "method": "GET",
            "path": "/api/v1/documents/{documentId}/content",
            "id": "downloadDocument",
            "kind": "query",
            "pathParams": [
                {
                    "name": "documentId"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/octet-stream",
                    "schema": DownloadDocument200Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": DownloadDocument400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": DownloadDocument401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": DownloadDocument404Schema
                }
            }
        }),
        "uploadDocument": defineEndpoint<UploadDocumentContract, "mutation">({
            "method": "POST",
            "path": "/api/v1/offerings/{offeringId}/documents",
            "id": "uploadDocument",
            "kind": "mutation",
            "pathParams": [
                {
                    "name": "offeringId"
                }
            ],
            "requestBody": {
                "content": [
                    {
                        "mediaType": "multipart/form-data",
                        "codec": {
                            "kind": "form",
                            "mediaType": "multipart/form-data",
                            "fields": {
                                "category": {
                                    "mediaType": "text/plain",
                                    "codec": {
                                        "kind": "text"
                                    },
                                    "multiple": false,
                                    "headers": {}
                                },
                                "file": {
                                    "mediaType": "application/octet-stream",
                                    "codec": {
                                        "kind": "bytes",
                                        "value": "upload"
                                    },
                                    "multiple": false,
                                    "headers": {}
                                },
                                "note": {
                                    "mediaType": "text/plain",
                                    "codec": {
                                        "kind": "text"
                                    },
                                    "multiple": false,
                                    "headers": {}
                                }
                            },
                            "patterns": {},
                            "additional": {
                                "mediaType": "application/octet-stream",
                                "codec": {
                                    "kind": "bytes",
                                    "value": "upload"
                                },
                                "multiple": false,
                                "headers": {}
                            }
                        }
                    }
                ],
                "required": true,
                "fields": [
                    "category",
                    "file",
                    "note"
                ]
            },
            "responses": {
                "201": {
                    "mediaType": "application/json",
                    "schema": UploadDocument201Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": UploadDocument400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": UploadDocument401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": UploadDocument404Schema
                },
                "413": {
                    "mediaType": "application/json",
                    "schema": UploadDocument413Schema
                }
            }
        })
    },
    "investors": {
        "createCompanyInvestor": defineEndpoint<CreateCompanyInvestorContract, "mutation">({
            "method": "POST",
            "path": "/api/v1/investors/companies",
            "id": "createCompanyInvestor",
            "kind": "mutation",
            "requestBody": {
                "content": [
                    {
                        "mediaType": "application/json"
                    }
                ],
                "required": true,
                "fields": [
                    "country",
                    "displayName",
                    "email",
                    "kind",
                    "onboardingNote",
                    "registrationNumber"
                ]
            },
            "responses": {
                "201": {
                    "mediaType": "application/json",
                    "schema": CreateCompanyInvestor201Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": CreateCompanyInvestor400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": CreateCompanyInvestor401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": CreateCompanyInvestor404Schema
                }
            }
        }),
        "createIndividualInvestor": defineEndpoint<CreateIndividualInvestorContract, "mutation">({
            "method": "POST",
            "path": "/api/v1/investors/individuals",
            "id": "createIndividualInvestor",
            "kind": "mutation",
            "requestBody": {
                "content": [
                    {
                        "mediaType": "application/json"
                    }
                ],
                "required": true,
                "fields": [
                    "country",
                    "displayName",
                    "email",
                    "kind",
                    "onboardingNote"
                ]
            },
            "responses": {
                "201": {
                    "mediaType": "application/json",
                    "schema": CreateIndividualInvestor201Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": CreateIndividualInvestor400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": CreateIndividualInvestor401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": CreateIndividualInvestor404Schema
                }
            }
        }),
        "getInvestor": defineEndpoint<GetInvestorContract, "query">({
            "method": "GET",
            "path": "/api/v1/investors/{investorId}",
            "id": "getInvestor",
            "kind": "query",
            "pathParams": [
                {
                    "name": "investorId"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": GetInvestor200Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": GetInvestor400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": GetInvestor401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": GetInvestor404Schema
                }
            }
        })
    },
    "jobs": {
        "getSubmissionJob": defineEndpoint<GetSubmissionJobContract, "query">({
            "method": "GET",
            "path": "/api/v1/jobs/{jobId}",
            "id": "getSubmissionJob",
            "kind": "query",
            "pathParams": [
                {
                    "name": "jobId"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": GetSubmissionJob200Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": GetSubmissionJob400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": GetSubmissionJob401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": GetSubmissionJob404Schema
                }
            }
        })
    },
    "offerings": {
        "listOfferings": defineEndpoint<ListOfferingsContract, "query">({
            "method": "GET",
            "path": "/api/v1/offerings",
            "id": "listOfferings",
            "kind": "query",
            "queryParams": [
                {
                    "name": "page"
                },
                {
                    "name": "limit"
                },
                {
                    "name": "status"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": ListOfferings200Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": ListOfferings400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": ListOfferings401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": ListOfferings404Schema
                }
            }
        }),
        "createOffering": defineEndpoint<CreateOfferingContract, "mutation">({
            "method": "POST",
            "path": "/api/v1/offerings",
            "id": "createOffering",
            "kind": "mutation",
            "requestBody": {
                "content": [
                    {
                        "mediaType": "application/json"
                    }
                ],
                "required": true,
                "fields": [
                    "description",
                    "name",
                    "tags",
                    "terms"
                ]
            },
            "responses": {
                "201": {
                    "mediaType": "application/json",
                    "schema": CreateOffering201Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": CreateOffering400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": CreateOffering401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": CreateOffering404Schema
                }
            }
        }),
        "getOffering": defineEndpoint<GetOfferingContract, "query">({
            "method": "GET",
            "path": "/api/v1/offerings/{offeringId}",
            "id": "getOffering",
            "kind": "query",
            "pathParams": [
                {
                    "name": "offeringId"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": GetOffering200Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": GetOffering400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": GetOffering401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": GetOffering404Schema
                }
            }
        }),
        "updateOffering": defineEndpoint<UpdateOfferingContract, "mutation">({
            "method": "PATCH",
            "path": "/api/v1/offerings/{offeringId}",
            "id": "updateOffering",
            "kind": "mutation",
            "pathParams": [
                {
                    "name": "offeringId"
                }
            ],
            "requestBody": {
                "content": [
                    {
                        "mediaType": "application/json"
                    }
                ],
                "mode": "separate"
            },
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": UpdateOffering200Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": UpdateOffering400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": UpdateOffering401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": UpdateOffering404Schema
                }
            }
        }),
        "deleteOffering": defineEndpoint<DeleteOfferingContract, "mutation">({
            "method": "DELETE",
            "path": "/api/v1/offerings/{offeringId}",
            "id": "deleteOffering",
            "kind": "mutation",
            "pathParams": [
                {
                    "name": "offeringId"
                }
            ],
            "responses": {
                "204": {},
                "400": {
                    "mediaType": "application/json",
                    "schema": DeleteOffering400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": DeleteOffering401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": DeleteOffering404Schema
                },
                "409": {
                    "mediaType": "application/json",
                    "schema": DeleteOffering409Schema
                }
            }
        }),
        "exportOffering": defineEndpoint<ExportOfferingContract, "query">({
            "method": "GET",
            "path": "/api/v1/offerings/{offeringId}/report",
            "id": "exportOffering",
            "kind": "query",
            "pathParams": [
                {
                    "name": "offeringId"
                }
            ],
            "responses": {
                "200": [
                    {
                        "mediaType": "application/json",
                        "schema": ExportOffering200JsonSchema
                    },
                    {
                        "mediaType": "text/csv",
                        "schema": ExportOffering200CsvSchema
                    }
                ],
                "400": {
                    "mediaType": "application/json",
                    "schema": ExportOffering400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": ExportOffering401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": ExportOffering404Schema
                }
            }
        })
    },
    "subscriptions": {
        "listSubscriptions": defineEndpoint<ListSubscriptionsContract, "query">({
            "method": "GET",
            "path": "/api/v1/offerings/{offeringId}/subscriptions",
            "id": "listSubscriptions",
            "kind": "query",
            "pathParams": [
                {
                    "name": "offeringId"
                }
            ],
            "queryParams": [
                {
                    "name": "page"
                },
                {
                    "name": "limit"
                },
                {
                    "name": "investorId"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": ListSubscriptions200Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": ListSubscriptions400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": ListSubscriptions401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": ListSubscriptions404Schema
                }
            }
        }),
        "createSubscription": defineEndpoint<CreateSubscriptionContract, "mutation">({
            "method": "POST",
            "path": "/api/v1/offerings/{offeringId}/subscriptions",
            "id": "createSubscription",
            "kind": "mutation",
            "pathParams": [
                {
                    "name": "offeringId"
                }
            ],
            "requestBody": {
                "content": [
                    {
                        "mediaType": "application/json"
                    }
                ],
                "required": true,
                "fields": [
                    "amount",
                    "investorId",
                    "metadata"
                ]
            },
            "responses": {
                "201": {
                    "mediaType": "application/json",
                    "schema": CreateSubscription201Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": CreateSubscription400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": CreateSubscription401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": CreateSubscription404Schema
                }
            }
        }),
        "getSubscription": defineEndpoint<GetSubscriptionContract, "query">({
            "method": "GET",
            "path": "/api/v1/subscriptions/{subscriptionId}",
            "id": "getSubscription",
            "kind": "query",
            "pathParams": [
                {
                    "name": "subscriptionId"
                }
            ],
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": GetSubscription200Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": GetSubscription400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": GetSubscription401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": GetSubscription404Schema
                }
            }
        }),
        "submitSubscription": defineEndpoint<SubmitSubscriptionContract, "mutation">({
            "method": "POST",
            "path": "/api/v1/subscriptions/{subscriptionId}/submit",
            "id": "submitSubscription",
            "kind": "mutation",
            "pathParams": [
                {
                    "name": "subscriptionId"
                }
            ],
            "queryParams": [
                {
                    "name": "background"
                }
            ],
            "resultMode": "status",
            "responses": {
                "200": {
                    "mediaType": "application/json",
                    "schema": SubmitSubscription200Schema
                },
                "202": {
                    "mediaType": "application/json",
                    "schema": SubmitSubscription202Schema
                },
                "400": {
                    "mediaType": "application/json",
                    "schema": SubmitSubscription400Schema
                },
                "401": {
                    "mediaType": "application/json",
                    "schema": SubmitSubscription401Schema
                },
                "404": {
                    "mediaType": "application/json",
                    "schema": SubmitSubscription404Schema
                }
            }
        })
    }
};
