/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createEndpointFactory } from "@accord/client";
import type { UploadContract, RenameContract, RemoveContract } from "../types/assets.js";
const defineEndpoint = createEndpointFactory("f8d72c46252ec3f3");
export const endpoints = {
    "upload": defineEndpoint<UploadContract, "mutation">({
        "method": "POST",
        "path": "/assets",
        "id": "upload",
        "kind": "mutation",
        "requestBody": {
            "type": "multipart",
            "fields": {
                "file": {
                    "type": "binary"
                },
                "metadata": {
                    "type": "json"
                },
                "tags": {
                    "type": "text",
                    "multiple": true
                }
            },
            "required": true
        },
        "responses": {
            "201": {
                "mediaType": "application/json"
            }
        }
    }),
    "rename": defineEndpoint<RenameContract, "mutation">({
        "method": "PATCH",
        "path": "/assets/{id}",
        "id": "rename",
        "kind": "mutation",
        "pathParams": [
            {
                "name": "id"
            }
        ],
        "requestBody": {
            "type": "json",
            "required": true,
            "mode": "separate"
        },
        "responses": {
            "200": {
                "mediaType": "application/json"
            }
        }
    }),
    "remove": defineEndpoint<RemoveContract, "mutation">({
        "method": "DELETE",
        "path": "/assets/{id}",
        "id": "remove",
        "kind": "mutation",
        "pathParams": [
            {
                "name": "id"
            }
        ],
        "responses": {
            "204": {}
        }
    })
};
