/* This file was generated by @accord/codegen. Do not edit manually. */
import type { EndpointDescriptor, ErrorOf, InputOf, ResponseOf, ResponsesOf } from "@accord/client"

export interface paths {
  "/users": {
    parameters: { query?: never; header?: never; path?: never; cookie?: never }
    get: operations["listUsers"]
    post: operations["createUser"]
  }
  "/users/{userId}": {
    parameters: { query?: never; header?: never; path?: never; cookie?: never }
    get: operations["getUser"]
  }
}
export interface components {
  schemas: {
    User: { id: string; name: string; email?: string | null }
    CreateUser: { name: string; email?: string }
    ApiError: { code: string; message: string }
  }
}
export interface operations {
  listUsers: {
    parameters: { query?: { limit?: number }; header?: never; path?: never; cookie?: never }
    responses: { 200: { content: { "application/json": components["schemas"]["User"][] } } }
  }
  createUser: {
    parameters: { query?: never; header?: never; path?: never; cookie?: never }
    requestBody: { content: { "application/json": components["schemas"]["CreateUser"] } }
    responses: {
      201: { content: { "application/json": components["schemas"]["User"] } }
      400: { content: { "application/json": components["schemas"]["ApiError"] } }
    }
  }
  getUser: {
    parameters: { query?: never; header?: never; path: { userId: string }; cookie?: never }
    responses: {
      200: { content: { "application/json": components["schemas"]["User"] } }
      404: { content: { "application/json": components["schemas"]["ApiError"] } }
    }
  }
}

type AccordOperation<TPath extends keyof paths, TMethod extends PropertyKey> =
  TMethod extends keyof paths[TPath] ? NonNullable<paths[TPath][TMethod]> : never

type AccordParameterGroup<TOperation, TLocation extends PropertyKey> =
  TOperation extends { parameters?: infer TParameters }
    ? NonNullable<TParameters> extends infer TGroups
      ? TGroups extends object
        ? TLocation extends keyof TGroups
          ? NonNullable<TGroups[TLocation]> extends object
            ? NonNullable<TGroups[TLocation]>
            : {}
          : {}
        : {}
      : {}
    : {}

type AccordRename<TValue, TMap extends object> = {
  [TKey in keyof TValue as TKey extends keyof TMap
    ? TMap[TKey] extends PropertyKey
      ? TMap[TKey]
      : TKey
    : TKey]: TValue[TKey]
}

type AccordRequestBody<TOperation, TContentType extends PropertyKey> =
  TOperation extends { requestBody?: infer TRequestBody }
    ? NonNullable<TRequestBody> extends { content: infer TContent }
      ? TContentType extends keyof TContent
        ? TContent[TContentType]
        : never
      : never
    : never

type AccordResponsesObject<TOperation> =
  TOperation extends { responses: infer TResponses } ? TResponses : {}

type AccordResponsePayload<TResponse> =
  TResponse extends { content: infer TContent }
    ? TContent extends object
      ? TContent[keyof TContent]
      : undefined
    : undefined

type AccordResponseAt<TOperation, TStatus extends PropertyKey> =
  TStatus extends keyof AccordResponsesObject<TOperation>
    ? AccordResponsePayload<AccordResponsesObject<TOperation>[TStatus]>
    : never

type AccordResponseUnion<TOperation, TStatuses extends PropertyKey> =
  TStatuses extends PropertyKey ? AccordResponseAt<TOperation, TStatuses> : never

type AccordUnknownIfNever<TValue> = [TValue] extends [never] ? unknown : TValue

type AccordResponseMap<TOperation, TStatuses extends PropertyKey> = {
  [TStatus in TStatuses]: AccordResponseAt<TOperation, TStatus>
}

type AccordUsersListUsersOperation = AccordOperation<"/users", "get">
type AccordUsersListUsersEndpointTypes = {
  readonly path: AccordRename<AccordParameterGroup<AccordUsersListUsersOperation, "path">, {}>
  readonly query: AccordRename<AccordParameterGroup<AccordUsersListUsersOperation, "query">, { "limit": "limit" }>
  readonly headers: AccordRename<AccordParameterGroup<AccordUsersListUsersOperation, "header">, {}>
  readonly cookies: AccordRename<AccordParameterGroup<AccordUsersListUsersOperation, "cookie">, {}>
  readonly body: never
  readonly bodyRequired: false
  readonly response: AccordUnknownIfNever<AccordResponseUnion<AccordUsersListUsersOperation, 200>>
  readonly error: AccordUnknownIfNever<AccordResponseUnion<AccordUsersListUsersOperation, never>>
  readonly responses: AccordResponseMap<AccordUsersListUsersOperation, 200>
}

type AccordUsersCreateUserOperation = AccordOperation<"/users", "post">
type AccordUsersCreateUserEndpointTypes = {
  readonly path: AccordRename<AccordParameterGroup<AccordUsersCreateUserOperation, "path">, {}>
  readonly query: AccordRename<AccordParameterGroup<AccordUsersCreateUserOperation, "query">, {}>
  readonly headers: AccordRename<AccordParameterGroup<AccordUsersCreateUserOperation, "header">, {}>
  readonly cookies: AccordRename<AccordParameterGroup<AccordUsersCreateUserOperation, "cookie">, {}>
  readonly body: AccordRequestBody<AccordUsersCreateUserOperation, "application/json">
  readonly bodyRequired: true
  readonly response: AccordUnknownIfNever<AccordResponseUnion<AccordUsersCreateUserOperation, 201>>
  readonly error: AccordUnknownIfNever<AccordResponseUnion<AccordUsersCreateUserOperation, 400>>
  readonly responses: AccordResponseMap<AccordUsersCreateUserOperation, 201 | 400>
}

type AccordUsersGetUserOperation = AccordOperation<"/users/{userId}", "get">
type AccordUsersGetUserEndpointTypes = {
  readonly path: AccordRename<AccordParameterGroup<AccordUsersGetUserOperation, "path">, { "userId": "userId" }>
  readonly query: AccordRename<AccordParameterGroup<AccordUsersGetUserOperation, "query">, {}>
  readonly headers: AccordRename<AccordParameterGroup<AccordUsersGetUserOperation, "header">, {}>
  readonly cookies: AccordRename<AccordParameterGroup<AccordUsersGetUserOperation, "cookie">, {}>
  readonly body: never
  readonly bodyRequired: false
  readonly response: AccordUnknownIfNever<AccordResponseUnion<AccordUsersGetUserOperation, 200>>
  readonly error: AccordUnknownIfNever<AccordResponseUnion<AccordUsersGetUserOperation, 404>>
  readonly responses: AccordResponseMap<AccordUsersGetUserOperation, 200 | 404>
}

export const api = {
  "users": {
    "createUser": ({
      "kind": "endpoint",
      "method": "POST",
      "path": "/users",
      "operationId": "createUser",
      "operationKind": "mutation",
      "bodyMode": "merge",
      "parameters": [],
      "requestBody": {
        "required": true,
        "contentType": "application/json",
        "contentTypes": [
          "application/json"
        ],
        "fields": [
          "email",
          "name"
        ]
      },
      "responses": [
        {
          "status": 201,
          "contentTypes": [
            "application/json"
          ]
        },
        {
          "status": 400,
          "contentTypes": [
            "application/json"
          ]
        }
      ]
    } as const satisfies EndpointDescriptor<AccordUsersCreateUserEndpointTypes, "merge", "mutation">) as EndpointDescriptor<AccordUsersCreateUserEndpointTypes, "merge", "mutation">,
    "getUser": ({
      "kind": "endpoint",
      "method": "GET",
      "path": "/users/{userId}",
      "operationId": "getUser",
      "operationKind": "query",
      "bodyMode": "merge",
      "parameters": [
        {
          "name": "userId",
          "inputName": "userId",
          "in": "path",
          "required": true,
          "style": "simple",
          "explode": false,
          "allowReserved": false
        }
      ],
      "responses": [
        {
          "status": 200,
          "contentTypes": [
            "application/json"
          ]
        },
        {
          "status": 404,
          "contentTypes": [
            "application/json"
          ]
        }
      ]
    } as const satisfies EndpointDescriptor<AccordUsersGetUserEndpointTypes, "merge", "query">) as EndpointDescriptor<AccordUsersGetUserEndpointTypes, "merge", "query">,
    "listUsers": ({
      "kind": "endpoint",
      "method": "GET",
      "path": "/users",
      "operationId": "listUsers",
      "operationKind": "query",
      "bodyMode": "merge",
      "parameters": [
        {
          "name": "limit",
          "inputName": "limit",
          "in": "query",
          "required": false,
          "style": "form",
          "explode": true,
          "allowReserved": false
        }
      ],
      "responses": [
        {
          "status": 200,
          "contentTypes": [
            "application/json"
          ]
        }
      ]
    } as const satisfies EndpointDescriptor<AccordUsersListUsersEndpointTypes, "merge", "query">) as EndpointDescriptor<AccordUsersListUsersEndpointTypes, "merge", "query">,
  } as const,
} as const

export namespace AccordTypes {
  export type UsersListUsersEndpoint = typeof api["users"]["listUsers"]
  export type UsersListUsersInput = InputOf<UsersListUsersEndpoint>
  export type UsersListUsersResponse = ResponseOf<UsersListUsersEndpoint>
  export type UsersListUsersError = ErrorOf<UsersListUsersEndpoint>
  export type UsersListUsersResponses = ResponsesOf<UsersListUsersEndpoint>
  export type UsersCreateUserEndpoint = typeof api["users"]["createUser"]
  export type UsersCreateUserInput = InputOf<UsersCreateUserEndpoint>
  export type UsersCreateUserResponse = ResponseOf<UsersCreateUserEndpoint>
  export type UsersCreateUserError = ErrorOf<UsersCreateUserEndpoint>
  export type UsersCreateUserResponses = ResponsesOf<UsersCreateUserEndpoint>
  export type UsersGetUserEndpoint = typeof api["users"]["getUser"]
  export type UsersGetUserInput = InputOf<UsersGetUserEndpoint>
  export type UsersGetUserResponse = ResponseOf<UsersGetUserEndpoint>
  export type UsersGetUserError = ErrorOf<UsersGetUserEndpoint>
  export type UsersGetUserResponses = ResponsesOf<UsersGetUserEndpoint>
}
