/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { defineEndpoint, type BinaryUpload, type HttpResult, type RequestOptions, type StatusRange } from "@accord/client";
type AccordSimplify<T> = T extends unknown ? {
    [K in keyof T]: T[K];
} : never;
type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T;
type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T;
export type ApiError = {
    readonly "code": string;
    readonly "message": string;
    readonly [key: string]: unknown;
};
export type ApiErrorRequest = {
    readonly "code": string;
    readonly "message": string;
    readonly [key: string]: unknown;
};
export type CreateUser = {
    readonly "email"?: string;
    readonly "name": string;
    readonly [key: string]: unknown;
};
export type CreateUserRequest = {
    readonly "email"?: string;
    readonly "name": string;
    readonly [key: string]: unknown;
};
export type User = {
    readonly "email"?: string | null;
    readonly "id": string;
    readonly "name": string;
    readonly [key: string]: unknown;
};
export type UserRequest = {
    readonly "email"?: string | null;
    readonly "id": string;
    readonly "name": string;
    readonly [key: string]: unknown;
};
export type UsersListUsersInput = {
    readonly "limit"?: number;
};
export type UsersListUsersArguments = [
    input?: {
        readonly "limit"?: number;
    },
    options?: RequestOptions
];
export type UsersListUsersResponse = ReadonlyArray<User>;
export type UsersListUsersError = never;
export type UsersListUsersResponses = {
    readonly "200": ReadonlyArray<User>;
};
export type UsersListUsersFullResponse = HttpResult<200, ReadonlyArray<User>>;
export type UsersListUsersContract = {
    readonly "args": UsersListUsersArguments;
    readonly "input": UsersListUsersInput;
    readonly "response": UsersListUsersResponse;
    readonly "error": UsersListUsersError;
    readonly "responses": UsersListUsersResponses;
    readonly "fullResponse": UsersListUsersFullResponse;
};
export type UsersCreateUserInput = {
    readonly "body": CreateUserRequest;
};
export type UsersCreateUserArguments = [
    input: {
        readonly "body": CreateUserRequest;
    },
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type UsersCreateUserResponse = User;
export type UsersCreateUserError = ApiError;
export type UsersCreateUserResponses = {
    readonly "201": User;
    readonly "400": ApiError;
};
export type UsersCreateUserFullResponse = HttpResult<201, User>;
export type UsersCreateUserContract = {
    readonly "args": UsersCreateUserArguments;
    readonly "input": UsersCreateUserInput;
    readonly "response": UsersCreateUserResponse;
    readonly "error": UsersCreateUserError;
    readonly "responses": UsersCreateUserResponses;
    readonly "fullResponse": UsersCreateUserFullResponse;
};
export type UsersGetUserInput = {
    readonly "userId": string;
};
export type UsersGetUserArguments = [
    input: {
        readonly "userId": string;
    },
    options?: RequestOptions
];
export type UsersGetUserResponse = User;
export type UsersGetUserError = ApiError;
export type UsersGetUserResponses = {
    readonly "200": User;
    readonly "404": ApiError;
};
export type UsersGetUserFullResponse = HttpResult<200, User>;
export type UsersGetUserContract = {
    readonly "args": UsersGetUserArguments;
    readonly "input": UsersGetUserInput;
    readonly "response": UsersGetUserResponse;
    readonly "error": UsersGetUserError;
    readonly "responses": UsersGetUserResponses;
    readonly "fullResponse": UsersGetUserFullResponse;
};
export const api = {
    "users": {
        "listUsers": defineEndpoint<UsersListUsersContract, "query">({
            "apiId": "ca315a231708d818",
            "method": "GET",
            "path": "/users",
            "operationId": "listUsers",
            "operationKind": "query",
            "queryParams": [
                {
                    "name": "limit"
                }
            ],
            "responses": [
                {
                    "status": 200,
                    "content": [
                        {
                            "mediaType": "application/json"
                        }
                    ]
                }
            ]
        }),
        "createUser": defineEndpoint<UsersCreateUserContract, "mutation">({
            "apiId": "ca315a231708d818",
            "method": "POST",
            "path": "/users",
            "operationId": "createUser",
            "operationKind": "mutation",
            "requestBody": {
                "content": [
                    {
                        "mediaType": "application/json"
                    }
                ],
                "required": true,
                "mode": "separate"
            },
            "responses": [
                {
                    "status": 201,
                    "content": [
                        {
                            "mediaType": "application/json"
                        }
                    ]
                },
                {
                    "status": 400,
                    "content": [
                        {
                            "mediaType": "application/json"
                        }
                    ]
                }
            ]
        }),
        "getUser": defineEndpoint<UsersGetUserContract, "query">({
            "apiId": "ca315a231708d818",
            "method": "GET",
            "path": "/users/{userId}",
            "operationId": "getUser",
            "operationKind": "query",
            "pathParams": [
                {
                    "name": "userId"
                }
            ],
            "responses": [
                {
                    "status": 200,
                    "content": [
                        {
                            "mediaType": "application/json"
                        }
                    ]
                },
                {
                    "status": 404,
                    "content": [
                        {
                            "mediaType": "application/json"
                        }
                    ]
                }
            ]
        })
    }
};
