/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { defineEndpoint, type BinaryUpload, type HttpResult, type RequestOptions, type StatusRange } from "@accord/client";
type AccordSimplify<T> = T extends unknown ? {
    [K in keyof T]: T[K];
} : never;
type AccordObjectConstraints<T, R> = T extends readonly unknown[] ? T : T extends object ? T & R : T;
type AccordArrayConstraints<T, R> = T extends readonly unknown[] ? T & R : T;
export type ApiError = {
    readonly "code": string;
    readonly "message": string;
    readonly [key: string]: unknown;
};
export type ApiErrorRequest = {
    readonly "code": string;
    readonly "message": string;
    readonly [key: string]: unknown;
};
export type CreateUser = {
    readonly "email"?: string;
    readonly "name": string;
    readonly [key: string]: unknown;
};
export type CreateUserRequest = {
    readonly "email"?: string;
    readonly "name": string;
    readonly [key: string]: unknown;
};
export type User = {
    readonly "email"?: string | null;
    readonly "id": string;
    readonly "name": string;
    readonly [key: string]: unknown;
};
export type UserRequest = {
    readonly "email"?: string | null;
    readonly "id": string;
    readonly "name": string;
    readonly [key: string]: unknown;
};
export type UsersListUsersInput = {
    readonly "limit"?: number;
};
export type UsersListUsersArguments = [
    input?: {
        readonly "limit"?: number;
    },
    options?: RequestOptions
];
export type UsersListUsersResponse = ReadonlyArray<User>;
export type UsersListUsersError = never;
export type UsersListUsersResponses = {
    readonly "200": ReadonlyArray<User>;
};
export type UsersListUsersFullResponse = HttpResult<200, ReadonlyArray<User>>;
export type UsersListUsersContract = {
    readonly "args": UsersListUsersArguments;
    readonly "input": UsersListUsersInput;
    readonly "response": UsersListUsersResponse;
    readonly "error": UsersListUsersError;
    readonly "responses": UsersListUsersResponses;
    readonly "fullResponse": UsersListUsersFullResponse;
};
export type UsersCreateUserInput = {
    readonly "body": CreateUserRequest;
};
export type UsersCreateUserArguments = [
    input: {
        readonly "body": CreateUserRequest;
    },
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type UsersCreateUserResponse = User;
export type UsersCreateUserError = ApiError;
export type UsersCreateUserResponses = {
    readonly "201": User;
    readonly "400": ApiError;
};
export type UsersCreateUserFullResponse = HttpResult<201, User>;
export type UsersCreateUserContract = {
    readonly "args": UsersCreateUserArguments;
    readonly "input": UsersCreateUserInput;
    readonly "response": UsersCreateUserResponse;
    readonly "error": UsersCreateUserError;
    readonly "responses": UsersCreateUserResponses;
    readonly "fullResponse": UsersCreateUserFullResponse;
};
export type UsersGetUserInput = {
    readonly "userId": string;
};
export type UsersGetUserArguments = [
    input: {
        readonly "userId": string;
    },
    options?: RequestOptions
];
export type UsersGetUserResponse = User;
export type UsersGetUserError = ApiError;
export type UsersGetUserResponses = {
    readonly "200": User;
    readonly "404": ApiError;
};
export type UsersGetUserFullResponse = HttpResult<200, User>;
export type UsersGetUserContract = {
    readonly "args": UsersGetUserArguments;
    readonly "input": UsersGetUserInput;
    readonly "response": UsersGetUserResponse;
    readonly "error": UsersGetUserError;
    readonly "responses": UsersGetUserResponses;
    readonly "fullResponse": UsersGetUserFullResponse;
};
type _UsersListUsersInput = UsersListUsersInput;
type _UsersListUsersResponse = UsersListUsersResponse;
type _UsersListUsersError = UsersListUsersError;
type _UsersListUsersResponses = UsersListUsersResponses;
type _UsersListUsersArguments = UsersListUsersArguments;
type _UsersListUsersFullResponse = UsersListUsersFullResponse;
type _UsersCreateUserInput = UsersCreateUserInput;
type _UsersCreateUserResponse = UsersCreateUserResponse;
type _UsersCreateUserError = UsersCreateUserError;
type _UsersCreateUserResponses = UsersCreateUserResponses;
type _UsersCreateUserArguments = UsersCreateUserArguments;
type _UsersCreateUserFullResponse = UsersCreateUserFullResponse;
type _UsersGetUserInput = UsersGetUserInput;
type _UsersGetUserResponse = UsersGetUserResponse;
type _UsersGetUserError = UsersGetUserError;
type _UsersGetUserResponses = UsersGetUserResponses;
type _UsersGetUserArguments = UsersGetUserArguments;
type _UsersGetUserFullResponse = UsersGetUserFullResponse;
export const api = {
    "users": {
        "listUsers": defineEndpoint<UsersListUsersContract, "query">({
            "kind": "endpoint",
            "plan": {
                "apiId": "8f355a546a72debe",
                "method": "GET",
                "path": "/users",
                "operationId": "listUsers",
                "operationKind": "query",
                "parameters": [
                    {
                        "name": "limit",
                        "inputName": "limit",
                        "in": "query",
                        "required": false,
                        "style": "form",
                        "explode": true,
                        "allowReserved": false
                    }
                ],
                "responses": [
                    {
                        "status": 200,
                        "content": [
                            {
                                "mediaType": "application/json",
                                "representation": {
                                    "key": "response-200-0",
                                    "codec": {
                                        "kind": "json"
                                    }
                                }
                            }
                        ],
                        "headers": []
                    }
                ],
                "resultMode": "payload",
                "servers": [],
                "security": [],
                "securitySchemes": {}
            }
        }),
        "createUser": defineEndpoint<UsersCreateUserContract, "mutation">({
            "kind": "endpoint",
            "plan": {
                "apiId": "8f355a546a72debe",
                "method": "POST",
                "path": "/users",
                "operationId": "createUser",
                "operationKind": "mutation",
                "parameters": [],
                "responses": [
                    {
                        "status": 201,
                        "content": [
                            {
                                "mediaType": "application/json",
                                "representation": {
                                    "key": "response-201-0",
                                    "codec": {
                                        "kind": "json"
                                    }
                                }
                            }
                        ],
                        "headers": []
                    },
                    {
                        "status": 400,
                        "content": [
                            {
                                "mediaType": "application/json",
                                "representation": {
                                    "key": "response-400-0",
                                    "codec": {
                                        "kind": "json"
                                    }
                                }
                            }
                        ],
                        "headers": []
                    }
                ],
                "resultMode": "payload",
                "servers": [],
                "security": [],
                "securitySchemes": {},
                "requestBody": {
                    "required": true,
                    "mode": "separate",
                    "fields": [
                        "email",
                        "name"
                    ],
                    "content": [
                        {
                            "mediaType": "application/json",
                            "representation": {
                                "key": "request-0",
                                "codec": {
                                    "kind": "json"
                                }
                            }
                        }
                    ],
                    "defaultMediaType": "application/json"
                }
            }
        }),
        "getUser": defineEndpoint<UsersGetUserContract, "query">({
            "kind": "endpoint",
            "plan": {
                "apiId": "8f355a546a72debe",
                "method": "GET",
                "path": "/users/{userId}",
                "operationId": "getUser",
                "operationKind": "query",
                "parameters": [
                    {
                        "name": "userId",
                        "inputName": "userId",
                        "in": "path",
                        "required": true,
                        "style": "simple",
                        "explode": false,
                        "allowReserved": false
                    }
                ],
                "responses": [
                    {
                        "status": 200,
                        "content": [
                            {
                                "mediaType": "application/json",
                                "representation": {
                                    "key": "response-200-0",
                                    "codec": {
                                        "kind": "json"
                                    }
                                }
                            }
                        ],
                        "headers": []
                    },
                    {
                        "status": 404,
                        "content": [
                            {
                                "mediaType": "application/json",
                                "representation": {
                                    "key": "response-404-0",
                                    "codec": {
                                        "kind": "json"
                                    }
                                }
                            }
                        ],
                        "headers": []
                    }
                ],
                "resultMode": "payload",
                "servers": [],
                "security": [],
                "securitySchemes": {}
            }
        })
    }
};
export namespace AccordTypes {
    export type UsersListUsersInput = _UsersListUsersInput;
    export type UsersListUsersResponse = _UsersListUsersResponse;
    export type UsersListUsersError = _UsersListUsersError;
    export type UsersListUsersResponses = _UsersListUsersResponses;
    export type UsersListUsersArguments = _UsersListUsersArguments;
    export type UsersListUsersFullResponse = _UsersListUsersFullResponse;
    export type UsersCreateUserInput = _UsersCreateUserInput;
    export type UsersCreateUserResponse = _UsersCreateUserResponse;
    export type UsersCreateUserError = _UsersCreateUserError;
    export type UsersCreateUserResponses = _UsersCreateUserResponses;
    export type UsersCreateUserArguments = _UsersCreateUserArguments;
    export type UsersCreateUserFullResponse = _UsersCreateUserFullResponse;
    export type UsersGetUserInput = _UsersGetUserInput;
    export type UsersGetUserResponse = _UsersGetUserResponse;
    export type UsersGetUserError = _UsersGetUserError;
    export type UsersGetUserResponses = _UsersGetUserResponses;
    export type UsersGetUserArguments = _UsersGetUserArguments;
    export type UsersGetUserFullResponse = _UsersGetUserFullResponse;
}
