/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { defineEndpoint } from "@accord/client";
import type {
    GetDocumentContract,
    DeleteDocumentContract,
    DownloadDocumentContract,
    UploadDocumentContract
} from "../types/documents.js";
import {
    GetDocument200Schema,
    GetDocument400Schema,
    GetDocument401Schema,
    GetDocument404Schema,
    DeleteDocument400Schema,
    DeleteDocument401Schema,
    DeleteDocument404Schema,
    DownloadDocument200Schema,
    DownloadDocument400Schema,
    DownloadDocument401Schema,
    DownloadDocument404Schema,
    UploadDocument201Schema,
    UploadDocument400Schema,
    UploadDocument401Schema,
    UploadDocument404Schema,
    UploadDocument413Schema
} from "../schemas.js";
export const endpoints = {
    "getDocument": defineEndpoint<GetDocumentContract, "query">({
        "method": "GET",
        "path": "/api/v1/documents/{documentId}",
        "id": "getDocument",
        "kind": "query",
        "pathParams": [
            {
                "name": "documentId"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": GetDocument200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": GetDocument400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": GetDocument401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": GetDocument404Schema
            }
        }
    }),
    "deleteDocument": defineEndpoint<DeleteDocumentContract, "mutation">({
        "method": "DELETE",
        "path": "/api/v1/documents/{documentId}",
        "id": "deleteDocument",
        "kind": "mutation",
        "pathParams": [
            {
                "name": "documentId"
            }
        ],
        "responses": {
            "204": {},
            "400": {
                "mediaType": "application/json",
                "schema": DeleteDocument400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": DeleteDocument401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": DeleteDocument404Schema
            }
        }
    }),
    "downloadDocument": defineEndpoint<DownloadDocumentContract, "query">({
        "method": "GET",
        "path": "/api/v1/documents/{documentId}/content",
        "id": "downloadDocument",
        "kind": "query",
        "pathParams": [
            {
                "name": "documentId"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/octet-stream",
                "schema": DownloadDocument200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": DownloadDocument400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": DownloadDocument401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": DownloadDocument404Schema
            }
        }
    }),
    "uploadDocument": defineEndpoint<UploadDocumentContract, "mutation">({
        "method": "POST",
        "path": "/api/v1/offerings/{offeringId}/documents",
        "id": "uploadDocument",
        "kind": "mutation",
        "pathParams": [
            {
                "name": "offeringId"
            }
        ],
        "requestBody": {
            "type": "multipart",
            "fields": {
                "category": {
                    "type": "text"
                },
                "file": {
                    "type": "binary"
                },
                "note": {
                    "type": "text"
                }
            },
            "required": true
        },
        "responses": {
            "201": {
                "mediaType": "application/json",
                "schema": UploadDocument201Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": UploadDocument400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": UploadDocument401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": UploadDocument404Schema
            },
            "413": {
                "mediaType": "application/json",
                "schema": UploadDocument413Schema
            }
        }
    })
};
