/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { defineEndpoint } from "@accord/client";
import type {
    ListInvestorsContract,
    CreateCompanyInvestorContract,
    CreateIndividualInvestorContract,
    GetInvestorContract
} from "../types/investors.js";
import {
    ListInvestors200Schema,
    ListInvestors400Schema,
    ListInvestors401Schema,
    ListInvestors404Schema,
    CreateCompanyInvestor201Schema,
    CreateCompanyInvestor400Schema,
    CreateCompanyInvestor401Schema,
    CreateCompanyInvestor404Schema,
    CreateIndividualInvestor201Schema,
    CreateIndividualInvestor400Schema,
    CreateIndividualInvestor401Schema,
    CreateIndividualInvestor404Schema,
    GetInvestor200Schema,
    GetInvestor400Schema,
    GetInvestor401Schema,
    GetInvestor404Schema
} from "../schemas.js";
export const endpoints = {
    "listInvestors": defineEndpoint<ListInvestorsContract, "query">({
        "method": "GET",
        "path": "/api/v1/investors",
        "id": "listInvestors",
        "kind": "query",
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": ListInvestors200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": ListInvestors400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": ListInvestors401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": ListInvestors404Schema
            }
        }
    }),
    "createCompanyInvestor": defineEndpoint<CreateCompanyInvestorContract, "mutation">({
        "method": "POST",
        "path": "/api/v1/investors/companies",
        "id": "createCompanyInvestor",
        "kind": "mutation",
        "requestBody": {
            "type": "json",
            "required": true,
            "fields": [
                "country",
                "displayName",
                "email",
                "kind",
                "onboardingNote",
                "registrationNumber"
            ]
        },
        "responses": {
            "201": {
                "mediaType": "application/json",
                "schema": CreateCompanyInvestor201Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": CreateCompanyInvestor400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": CreateCompanyInvestor401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": CreateCompanyInvestor404Schema
            }
        }
    }),
    "createIndividualInvestor": defineEndpoint<CreateIndividualInvestorContract, "mutation">({
        "method": "POST",
        "path": "/api/v1/investors/individuals",
        "id": "createIndividualInvestor",
        "kind": "mutation",
        "requestBody": {
            "type": "json",
            "required": true,
            "fields": [
                "country",
                "displayName",
                "email",
                "kind",
                "onboardingNote"
            ]
        },
        "responses": {
            "201": {
                "mediaType": "application/json",
                "schema": CreateIndividualInvestor201Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": CreateIndividualInvestor400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": CreateIndividualInvestor401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": CreateIndividualInvestor404Schema
            }
        }
    }),
    "getInvestor": defineEndpoint<GetInvestorContract, "query">({
        "method": "GET",
        "path": "/api/v1/investors/{investorId}",
        "id": "getInvestor",
        "kind": "query",
        "pathParams": [
            {
                "name": "investorId"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": GetInvestor200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": GetInvestor400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": GetInvestor401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": GetInvestor404Schema
            }
        }
    })
};
