/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createEndpointFactory } from "@accord/client";
import type { GetSubmissionJobContract } from "../types/jobs.js";
import {
    GetSubmissionJob200Schema,
    GetSubmissionJob400Schema,
    GetSubmissionJob401Schema,
    GetSubmissionJob404Schema
} from "../schemas.js";
const defineEndpoint = createEndpointFactory("e93a4e55a06c37be");
export const endpoints = {
    "getSubmissionJob": defineEndpoint<GetSubmissionJobContract, "query">({
        "method": "GET",
        "path": "/api/v1/jobs/{jobId}",
        "id": "getSubmissionJob",
        "kind": "query",
        "pathParams": [
            {
                "name": "jobId"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": GetSubmissionJob200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": GetSubmissionJob400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": GetSubmissionJob401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": GetSubmissionJob404Schema
            }
        }
    })
};
