/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createEndpointFactory } from "@accord/client";
import type {
    ListOfferingsContract,
    CreateOfferingContract,
    GetOfferingContract,
    UpdateOfferingContract,
    DeleteOfferingContract,
    ExportOfferingContract
} from "../types/offerings.js";
import {
    ListOfferings200Schema,
    ListOfferings400Schema,
    ListOfferings401Schema,
    ListOfferings404Schema,
    CreateOffering201Schema,
    CreateOffering400Schema,
    CreateOffering401Schema,
    CreateOffering404Schema,
    GetOffering200Schema,
    GetOffering400Schema,
    GetOffering401Schema,
    GetOffering404Schema,
    UpdateOffering200Schema,
    UpdateOffering400Schema,
    UpdateOffering401Schema,
    UpdateOffering404Schema,
    DeleteOffering400Schema,
    DeleteOffering401Schema,
    DeleteOffering404Schema,
    DeleteOffering409Schema,
    ExportOffering200JsonSchema,
    ExportOffering200CsvSchema,
    ExportOffering400Schema,
    ExportOffering401Schema,
    ExportOffering404Schema
} from "../schemas.js";
const defineEndpoint = createEndpointFactory("dc085c6fffabdb3b");
export const endpoints = {
    "listOfferings": defineEndpoint<ListOfferingsContract, "query">({
        "method": "GET",
        "path": "/api/v1/offerings",
        "id": "listOfferings",
        "kind": "query",
        "queryParams": [
            {
                "name": "page"
            },
            {
                "name": "limit"
            },
            {
                "name": "status"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": ListOfferings200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": ListOfferings400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": ListOfferings401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": ListOfferings404Schema
            }
        }
    }),
    "createOffering": defineEndpoint<CreateOfferingContract, "mutation">({
        "method": "POST",
        "path": "/api/v1/offerings",
        "id": "createOffering",
        "kind": "mutation",
        "requestBody": {
            "type": "json",
            "required": true,
            "fields": [
                "description",
                "name",
                "tags",
                "terms"
            ]
        },
        "responses": {
            "201": {
                "mediaType": "application/json",
                "schema": CreateOffering201Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": CreateOffering400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": CreateOffering401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": CreateOffering404Schema
            }
        }
    }),
    "getOffering": defineEndpoint<GetOfferingContract, "query">({
        "method": "GET",
        "path": "/api/v1/offerings/{offeringId}",
        "id": "getOffering",
        "kind": "query",
        "pathParams": [
            {
                "name": "offeringId"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": GetOffering200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": GetOffering400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": GetOffering401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": GetOffering404Schema
            }
        }
    }),
    "updateOffering": defineEndpoint<UpdateOfferingContract, "mutation">({
        "method": "PATCH",
        "path": "/api/v1/offerings/{offeringId}",
        "id": "updateOffering",
        "kind": "mutation",
        "pathParams": [
            {
                "name": "offeringId"
            }
        ],
        "requestBody": {
            "type": "json",
            "mode": "separate"
        },
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": UpdateOffering200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": UpdateOffering400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": UpdateOffering401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": UpdateOffering404Schema
            }
        }
    }),
    "deleteOffering": defineEndpoint<DeleteOfferingContract, "mutation">({
        "method": "DELETE",
        "path": "/api/v1/offerings/{offeringId}",
        "id": "deleteOffering",
        "kind": "mutation",
        "pathParams": [
            {
                "name": "offeringId"
            }
        ],
        "responses": {
            "204": {},
            "400": {
                "mediaType": "application/json",
                "schema": DeleteOffering400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": DeleteOffering401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": DeleteOffering404Schema
            },
            "409": {
                "mediaType": "application/json",
                "schema": DeleteOffering409Schema
            }
        }
    }),
    "exportOffering": defineEndpoint<ExportOfferingContract, "query">({
        "method": "GET",
        "path": "/api/v1/offerings/{offeringId}/report",
        "id": "exportOffering",
        "kind": "query",
        "pathParams": [
            {
                "name": "offeringId"
            }
        ],
        "responses": {
            "200": [
                {
                    "mediaType": "application/json",
                    "schema": ExportOffering200JsonSchema
                },
                {
                    "mediaType": "text/csv",
                    "schema": ExportOffering200CsvSchema
                }
            ],
            "400": {
                "mediaType": "application/json",
                "schema": ExportOffering400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": ExportOffering401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": ExportOffering404Schema
            }
        }
    })
};
