/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import { createEndpointFactory } from "@accord/client";
import type {
    ListSubscriptionsContract,
    CreateSubscriptionContract,
    GetSubscriptionContract,
    SubmitSubscriptionContract
} from "../types/subscriptions.js";
import {
    ListSubscriptions200Schema,
    ListSubscriptions400Schema,
    ListSubscriptions401Schema,
    ListSubscriptions404Schema,
    CreateSubscription201Schema,
    CreateSubscription400Schema,
    CreateSubscription401Schema,
    CreateSubscription404Schema,
    GetSubscription200Schema,
    GetSubscription400Schema,
    GetSubscription401Schema,
    GetSubscription404Schema,
    SubmitSubscription200Schema,
    SubmitSubscription202Schema,
    SubmitSubscription400Schema,
    SubmitSubscription401Schema,
    SubmitSubscription404Schema
} from "../schemas.js";
const defineEndpoint = createEndpointFactory("dc085c6fffabdb3b");
export const endpoints = {
    "listSubscriptions": defineEndpoint<ListSubscriptionsContract, "query">({
        "method": "GET",
        "path": "/api/v1/offerings/{offeringId}/subscriptions",
        "id": "listSubscriptions",
        "kind": "query",
        "pathParams": [
            {
                "name": "offeringId"
            }
        ],
        "queryParams": [
            {
                "name": "page"
            },
            {
                "name": "limit"
            },
            {
                "name": "investorId"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": ListSubscriptions200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": ListSubscriptions400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": ListSubscriptions401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": ListSubscriptions404Schema
            }
        }
    }),
    "createSubscription": defineEndpoint<CreateSubscriptionContract, "mutation">({
        "method": "POST",
        "path": "/api/v1/offerings/{offeringId}/subscriptions",
        "id": "createSubscription",
        "kind": "mutation",
        "pathParams": [
            {
                "name": "offeringId"
            }
        ],
        "requestBody": {
            "type": "json",
            "required": true,
            "fields": [
                "amount",
                "investorId",
                "metadata"
            ]
        },
        "responses": {
            "201": {
                "mediaType": "application/json",
                "schema": CreateSubscription201Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": CreateSubscription400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": CreateSubscription401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": CreateSubscription404Schema
            }
        }
    }),
    "getSubscription": defineEndpoint<GetSubscriptionContract, "query">({
        "method": "GET",
        "path": "/api/v1/subscriptions/{subscriptionId}",
        "id": "getSubscription",
        "kind": "query",
        "pathParams": [
            {
                "name": "subscriptionId"
            }
        ],
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": GetSubscription200Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": GetSubscription400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": GetSubscription401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": GetSubscription404Schema
            }
        }
    }),
    "submitSubscription": defineEndpoint<SubmitSubscriptionContract, "mutation">({
        "method": "POST",
        "path": "/api/v1/subscriptions/{subscriptionId}/submit",
        "id": "submitSubscription",
        "kind": "mutation",
        "pathParams": [
            {
                "name": "subscriptionId"
            }
        ],
        "queryParams": [
            {
                "name": "background"
            }
        ],
        "resultMode": "status",
        "responses": {
            "200": {
                "mediaType": "application/json",
                "schema": SubmitSubscription200Schema
            },
            "202": {
                "mediaType": "application/json",
                "schema": SubmitSubscription202Schema
            },
            "400": {
                "mediaType": "application/json",
                "schema": SubmitSubscription400Schema
            },
            "401": {
                "mediaType": "application/json",
                "schema": SubmitSubscription401Schema
            },
            "404": {
                "mediaType": "application/json",
                "schema": SubmitSubscription404Schema
            }
        }
    })
};
