/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { BinaryUpload, HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
import type { ErrorDto } from "./shared.js";
export type DocumentCategory = ("terms" | "prospectus" | "other") & string;
export type DocumentDto = {
    "category": DocumentCategory;
    "filename": string;
    "id": string;
    "note"?: string;
    "offeringId": string;
    "size": number;
};
export type UploadDocumentDto = {
    "category": DocumentCategory;
    "file": string;
    "note"?: string;
};
export type UploadDocumentDtoForm = {
    "category": DocumentCategory;
    "file": BinaryUpload;
    "note"?: string;
};
export type GetDocumentInput = {
    "documentId": string;
};
export type GetDocumentArguments = [
    input: {
        "documentId": string;
    },
    options?: RequestOptions
];
export type GetDocumentResponse = DocumentDto;
export type GetDocumentError = ErrorDto;
export type GetDocumentResponses = {
    "200": DocumentDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type GetDocumentFullResponse = HttpResult<200, DocumentDto>;
export type GetDocumentContract = {
    "args": GetDocumentArguments;
    "input": GetDocumentInput;
    "response": GetDocumentResponse;
    "error": GetDocumentError;
    "responses": GetDocumentResponses;
    "fullResponse": GetDocumentFullResponse;
};
export type DeleteDocumentInput = {
    "documentId": string;
};
export type DeleteDocumentArguments = [
    input: {
        "documentId": string;
    },
    options?: RequestOptions
];
export type DeleteDocumentResponse = undefined;
export type DeleteDocumentError = ErrorDto;
export type DeleteDocumentResponses = {
    "204": undefined;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type DeleteDocumentFullResponse = HttpResult<204, undefined>;
export type DeleteDocumentContract = {
    "args": DeleteDocumentArguments;
    "input": DeleteDocumentInput;
    "response": DeleteDocumentResponse;
    "error": DeleteDocumentError;
    "responses": DeleteDocumentResponses;
    "fullResponse": DeleteDocumentFullResponse;
};
export type DownloadDocumentInput = {
    "documentId": string;
};
export type DownloadDocumentArguments = [
    input: {
        "documentId": string;
    },
    options?: RequestOptions
];
export type DownloadDocumentResponse = ArrayBuffer;
export type DownloadDocumentError = ErrorDto;
export type DownloadDocumentResponses = {
    "200": ArrayBuffer;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type DownloadDocumentFullResponse = HttpResult<200, ArrayBuffer>;
export type DownloadDocumentContract = {
    "args": DownloadDocumentArguments;
    "input": DownloadDocumentInput;
    "response": DownloadDocumentResponse;
    "error": DownloadDocumentError;
    "responses": DownloadDocumentResponses;
    "fullResponse": DownloadDocumentFullResponse;
};
export type ListDocumentsInput = {
    "offeringId": string;
};
export type ListDocumentsArguments = [
    input: {
        "offeringId": string;
    },
    options?: RequestOptions
];
export type ListDocumentsResponse = DocumentDto[];
export type ListDocumentsError = ErrorDto;
export type ListDocumentsResponses = {
    "200": DocumentDto[];
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type ListDocumentsFullResponse = HttpResult<200, DocumentDto[]>;
export type ListDocumentsContract = {
    "args": ListDocumentsArguments;
    "input": ListDocumentsInput;
    "response": ListDocumentsResponse;
    "error": ListDocumentsError;
    "responses": ListDocumentsResponses;
    "fullResponse": ListDocumentsFullResponse;
};
export type UploadDocumentInput = {
    "offeringId": string;
} & UploadDocumentDtoForm;
export type UploadDocumentArguments = [
    input: {
        "offeringId": string;
    } & UploadDocumentDtoForm,
    options?: RequestOptionsFor<"multipart/form-data">
];
export type UploadDocumentResponse = DocumentDto;
export type UploadDocumentError = ErrorDto;
export type UploadDocumentResponses = {
    "201": DocumentDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
    "413": ErrorDto;
};
export type UploadDocumentFullResponse = HttpResult<201, DocumentDto>;
export type UploadDocumentContract = {
    "args": UploadDocumentArguments;
    "input": UploadDocumentInput;
    "response": UploadDocumentResponse;
    "error": UploadDocumentError;
    "responses": UploadDocumentResponses;
    "fullResponse": UploadDocumentFullResponse;
};
