/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions } from "@accord/client";
import type {
    AccordSimplify,
    DocumentDto,
    ProblemDto,
    UploadDocumentDtoRequestForm
} from "../models.js";
export type GetDocumentInput = {
    readonly "documentId": string;
};
export type GetDocumentArguments = [
    input: {
        readonly "documentId": string;
    },
    options?: RequestOptions
];
export type GetDocumentResponse = DocumentDto;
export type GetDocumentError = ProblemDto;
export type GetDocumentResponses = {
    readonly "200": DocumentDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type GetDocumentFullResponse = HttpResult<200, DocumentDto>;
export type GetDocumentContract = {
    readonly "args": GetDocumentArguments;
    readonly "input": GetDocumentInput;
    readonly "response": GetDocumentResponse;
    readonly "error": GetDocumentError;
    readonly "responses": GetDocumentResponses;
    readonly "fullResponse": GetDocumentFullResponse;
};
export type DeleteDocumentInput = {
    readonly "documentId": string;
};
export type DeleteDocumentArguments = [
    input: {
        readonly "documentId": string;
    },
    options?: RequestOptions
];
export type DeleteDocumentResponse = undefined;
export type DeleteDocumentError = ProblemDto;
export type DeleteDocumentResponses = {
    readonly "204": undefined;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type DeleteDocumentFullResponse = HttpResult<204, undefined>;
export type DeleteDocumentContract = {
    readonly "args": DeleteDocumentArguments;
    readonly "input": DeleteDocumentInput;
    readonly "response": DeleteDocumentResponse;
    readonly "error": DeleteDocumentError;
    readonly "responses": DeleteDocumentResponses;
    readonly "fullResponse": DeleteDocumentFullResponse;
};
export type DownloadDocumentInput = {
    readonly "documentId": string;
};
export type DownloadDocumentArguments = [
    input: {
        readonly "documentId": string;
    },
    options?: RequestOptions
];
export type DownloadDocumentResponse = ArrayBuffer;
export type DownloadDocumentError = ProblemDto;
export type DownloadDocumentResponses = {
    readonly "200": ArrayBuffer;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type DownloadDocumentFullResponse = HttpResult<200, ArrayBuffer>;
export type DownloadDocumentContract = {
    readonly "args": DownloadDocumentArguments;
    readonly "input": DownloadDocumentInput;
    readonly "response": DownloadDocumentResponse;
    readonly "error": DownloadDocumentError;
    readonly "responses": DownloadDocumentResponses;
    readonly "fullResponse": DownloadDocumentFullResponse;
};
export type UploadDocumentInput = AccordSimplify<{
    readonly "offeringId": string;
} & UploadDocumentDtoRequestForm>;
export type UploadDocumentArguments = [
    input: AccordSimplify<{
        readonly "offeringId": string;
    } & UploadDocumentDtoRequestForm>,
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "multipart/form-data" | `multipart/form-data;${string}`;
        };
    }
];
export type UploadDocumentResponse = DocumentDto;
export type UploadDocumentError = ProblemDto;
export type UploadDocumentResponses = {
    readonly "201": DocumentDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
    readonly "413": ProblemDto;
};
export type UploadDocumentFullResponse = HttpResult<201, DocumentDto>;
export type UploadDocumentContract = {
    readonly "args": UploadDocumentArguments;
    readonly "input": UploadDocumentInput;
    readonly "response": UploadDocumentResponse;
    readonly "error": UploadDocumentError;
    readonly "responses": UploadDocumentResponses;
    readonly "fullResponse": UploadDocumentFullResponse;
};
