/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { BinaryUpload, HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
import type { ErrorDto } from "./shared.js";
export type DocumentCategory = ("terms" | "prospectus" | "other") & string;
export type DocumentDto = {
    readonly "category": DocumentCategory;
    readonly "filename": string;
    readonly "id": string;
    readonly "note"?: string;
    readonly "offeringId": string;
    readonly "size": number;
};
export type UploadDocumentDto = {
    readonly "category": DocumentCategory;
    readonly "file": string;
    readonly "note"?: string;
};
export type UploadDocumentDtoForm = {
    readonly "category": DocumentCategory;
    readonly "file": BinaryUpload;
    readonly "note"?: string;
};
export type GetDocumentInput = {
    readonly "documentId": string;
};
export type GetDocumentArguments = [
    input: {
        readonly "documentId": string;
    },
    options?: RequestOptions
];
export type GetDocumentResponse = DocumentDto;
export type GetDocumentError = ErrorDto;
export type GetDocumentResponses = {
    readonly "200": DocumentDto;
    readonly "400": ErrorDto;
    readonly "401": ErrorDto;
    readonly "404": ErrorDto;
};
export type GetDocumentFullResponse = HttpResult<200, DocumentDto>;
export type GetDocumentContract = {
    readonly "args": GetDocumentArguments;
    readonly "input": GetDocumentInput;
    readonly "response": GetDocumentResponse;
    readonly "error": GetDocumentError;
    readonly "responses": GetDocumentResponses;
    readonly "fullResponse": GetDocumentFullResponse;
};
export type DeleteDocumentInput = {
    readonly "documentId": string;
};
export type DeleteDocumentArguments = [
    input: {
        readonly "documentId": string;
    },
    options?: RequestOptions
];
export type DeleteDocumentResponse = undefined;
export type DeleteDocumentError = ErrorDto;
export type DeleteDocumentResponses = {
    readonly "204": undefined;
    readonly "400": ErrorDto;
    readonly "401": ErrorDto;
    readonly "404": ErrorDto;
};
export type DeleteDocumentFullResponse = HttpResult<204, undefined>;
export type DeleteDocumentContract = {
    readonly "args": DeleteDocumentArguments;
    readonly "input": DeleteDocumentInput;
    readonly "response": DeleteDocumentResponse;
    readonly "error": DeleteDocumentError;
    readonly "responses": DeleteDocumentResponses;
    readonly "fullResponse": DeleteDocumentFullResponse;
};
export type DownloadDocumentInput = {
    readonly "documentId": string;
};
export type DownloadDocumentArguments = [
    input: {
        readonly "documentId": string;
    },
    options?: RequestOptions
];
export type DownloadDocumentResponse = ArrayBuffer;
export type DownloadDocumentError = ErrorDto;
export type DownloadDocumentResponses = {
    readonly "200": ArrayBuffer;
    readonly "400": ErrorDto;
    readonly "401": ErrorDto;
    readonly "404": ErrorDto;
};
export type DownloadDocumentFullResponse = HttpResult<200, ArrayBuffer>;
export type DownloadDocumentContract = {
    readonly "args": DownloadDocumentArguments;
    readonly "input": DownloadDocumentInput;
    readonly "response": DownloadDocumentResponse;
    readonly "error": DownloadDocumentError;
    readonly "responses": DownloadDocumentResponses;
    readonly "fullResponse": DownloadDocumentFullResponse;
};
export type UploadDocumentInput = {
    readonly "offeringId": string;
} & UploadDocumentDtoForm;
export type UploadDocumentArguments = [
    input: {
        readonly "offeringId": string;
    } & UploadDocumentDtoForm,
    options?: RequestOptionsFor<"multipart/form-data">
];
export type UploadDocumentResponse = DocumentDto;
export type UploadDocumentError = ErrorDto;
export type UploadDocumentResponses = {
    readonly "201": DocumentDto;
    readonly "400": ErrorDto;
    readonly "401": ErrorDto;
    readonly "404": ErrorDto;
    readonly "413": ErrorDto;
};
export type UploadDocumentFullResponse = HttpResult<201, DocumentDto>;
export type UploadDocumentContract = {
    readonly "args": UploadDocumentArguments;
    readonly "input": UploadDocumentInput;
    readonly "response": UploadDocumentResponse;
    readonly "error": UploadDocumentError;
    readonly "responses": UploadDocumentResponses;
    readonly "fullResponse": UploadDocumentFullResponse;
};
