/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
import type {
    CompanyInvestorDto,
    CreateCompanyInvestorDtoRequest,
    CreateIndividualInvestorDtoRequest,
    ErrorDto,
    IndividualInvestorDto
} from "../models.js";
export type CreateCompanyInvestorInput = CreateCompanyInvestorDtoRequest;
export type CreateCompanyInvestorArguments = [
    input: CreateCompanyInvestorDtoRequest,
    options?: RequestOptionsFor<"application/json">
];
export type CreateCompanyInvestorResponse = CompanyInvestorDto;
export type CreateCompanyInvestorError = ErrorDto;
export type CreateCompanyInvestorResponses = {
    readonly "201": CompanyInvestorDto;
    readonly "400": ErrorDto;
    readonly "401": ErrorDto;
    readonly "404": ErrorDto;
};
export type CreateCompanyInvestorFullResponse = HttpResult<201, CompanyInvestorDto>;
export type CreateCompanyInvestorContract = {
    readonly "args": CreateCompanyInvestorArguments;
    readonly "input": CreateCompanyInvestorInput;
    readonly "response": CreateCompanyInvestorResponse;
    readonly "error": CreateCompanyInvestorError;
    readonly "responses": CreateCompanyInvestorResponses;
    readonly "fullResponse": CreateCompanyInvestorFullResponse;
};
export type CreateIndividualInvestorInput = CreateIndividualInvestorDtoRequest;
export type CreateIndividualInvestorArguments = [
    input: CreateIndividualInvestorDtoRequest,
    options?: RequestOptionsFor<"application/json">
];
export type CreateIndividualInvestorResponse = IndividualInvestorDto;
export type CreateIndividualInvestorError = ErrorDto;
export type CreateIndividualInvestorResponses = {
    readonly "201": IndividualInvestorDto;
    readonly "400": ErrorDto;
    readonly "401": ErrorDto;
    readonly "404": ErrorDto;
};
export type CreateIndividualInvestorFullResponse = HttpResult<201, IndividualInvestorDto>;
export type CreateIndividualInvestorContract = {
    readonly "args": CreateIndividualInvestorArguments;
    readonly "input": CreateIndividualInvestorInput;
    readonly "response": CreateIndividualInvestorResponse;
    readonly "error": CreateIndividualInvestorError;
    readonly "responses": CreateIndividualInvestorResponses;
    readonly "fullResponse": CreateIndividualInvestorFullResponse;
};
export type GetInvestorInput = {
    readonly "investorId": string;
};
export type GetInvestorArguments = [
    input: {
        readonly "investorId": string;
    },
    options?: RequestOptions
];
export type GetInvestorResponse = IndividualInvestorDto | CompanyInvestorDto;
export type GetInvestorError = ErrorDto;
export type GetInvestorResponses = {
    readonly "200": IndividualInvestorDto | CompanyInvestorDto;
    readonly "400": ErrorDto;
    readonly "401": ErrorDto;
    readonly "404": ErrorDto;
};
export type GetInvestorFullResponse = HttpResult<200, IndividualInvestorDto | CompanyInvestorDto>;
export type GetInvestorContract = {
    readonly "args": GetInvestorArguments;
    readonly "input": GetInvestorInput;
    readonly "response": GetInvestorResponse;
    readonly "error": GetInvestorError;
    readonly "responses": GetInvestorResponses;
    readonly "fullResponse": GetInvestorFullResponse;
};
