/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
import type { ErrorDto } from "./shared.js";
export type CompanyInvestorDto = {
    "country": string;
    "displayName": string;
    "email": string;
    "id": string;
    "kind": "company" & string;
    "registrationNumber": string;
};
export type CreateCompanyInvestorDto = {
    "country": string;
    "displayName": string;
    "email": string;
    "kind": "company" & string;
    "onboardingNote"?: never;
    "registrationNumber": string;
};
export type CreateCompanyInvestorDtoRequest = {
    "country": string;
    "displayName": string;
    "email": string;
    "kind": "company" & string;
    "onboardingNote"?: string;
    "registrationNumber": string;
};
export type CreateIndividualInvestorDto = {
    "country": string;
    "displayName": string;
    "email": string;
    "kind": "individual" & string;
    "onboardingNote"?: never;
};
export type CreateIndividualInvestorDtoRequest = {
    "country": string;
    "displayName": string;
    "email": string;
    "kind": "individual" & string;
    "onboardingNote"?: string;
};
export type IndividualInvestorDto = {
    "country": string;
    "displayName": string;
    "email": string;
    "id": string;
    "kind": "individual" & string;
};
export type CreateCompanyInvestorInput = CreateCompanyInvestorDtoRequest;
export type CreateCompanyInvestorArguments = [
    input: CreateCompanyInvestorDtoRequest,
    options?: RequestOptionsFor<"application/json">
];
export type CreateCompanyInvestorResponse = CompanyInvestorDto;
export type CreateCompanyInvestorError = ErrorDto;
export type CreateCompanyInvestorResponses = {
    "201": CompanyInvestorDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type CreateCompanyInvestorFullResponse = HttpResult<201, CompanyInvestorDto>;
export type CreateCompanyInvestorContract = {
    "args": CreateCompanyInvestorArguments;
    "input": CreateCompanyInvestorInput;
    "response": CreateCompanyInvestorResponse;
    "error": CreateCompanyInvestorError;
    "responses": CreateCompanyInvestorResponses;
    "fullResponse": CreateCompanyInvestorFullResponse;
};
export type CreateIndividualInvestorInput = CreateIndividualInvestorDtoRequest;
export type CreateIndividualInvestorArguments = [
    input: CreateIndividualInvestorDtoRequest,
    options?: RequestOptionsFor<"application/json">
];
export type CreateIndividualInvestorResponse = IndividualInvestorDto;
export type CreateIndividualInvestorError = ErrorDto;
export type CreateIndividualInvestorResponses = {
    "201": IndividualInvestorDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type CreateIndividualInvestorFullResponse = HttpResult<201, IndividualInvestorDto>;
export type CreateIndividualInvestorContract = {
    "args": CreateIndividualInvestorArguments;
    "input": CreateIndividualInvestorInput;
    "response": CreateIndividualInvestorResponse;
    "error": CreateIndividualInvestorError;
    "responses": CreateIndividualInvestorResponses;
    "fullResponse": CreateIndividualInvestorFullResponse;
};
export type GetInvestorInput = {
    "investorId": string;
};
export type GetInvestorArguments = [
    input: {
        "investorId": string;
    },
    options?: RequestOptions
];
export type GetInvestorResponse = IndividualInvestorDto | CompanyInvestorDto;
export type GetInvestorError = ErrorDto;
export type GetInvestorResponses = {
    "200": IndividualInvestorDto | CompanyInvestorDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type GetInvestorFullResponse = HttpResult<200, IndividualInvestorDto | CompanyInvestorDto>;
export type GetInvestorContract = {
    "args": GetInvestorArguments;
    "input": GetInvestorInput;
    "response": GetInvestorResponse;
    "error": GetInvestorError;
    "responses": GetInvestorResponses;
    "fullResponse": GetInvestorFullResponse;
};
