/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions } from "@accord/client";
import type { SubscriptionDto } from "./subscriptions.js";
import type { ErrorDto } from "./shared.js";
export type SubmissionJobDto = {
    "id": string;
    "result": SubscriptionDto;
    "state": "completed" & string;
};
export type GetSubmissionJobInput = {
    "jobId": string;
};
export type GetSubmissionJobArguments = [
    input: {
        "jobId": string;
    },
    options?: RequestOptions
];
export type GetSubmissionJobResponse = SubmissionJobDto;
export type GetSubmissionJobError = ErrorDto;
export type GetSubmissionJobResponses = {
    "200": SubmissionJobDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type GetSubmissionJobFullResponse = HttpResult<200, SubmissionJobDto>;
export type GetSubmissionJobContract = {
    "args": GetSubmissionJobArguments;
    "input": GetSubmissionJobInput;
    "response": GetSubmissionJobResponse;
    "error": GetSubmissionJobError;
    "responses": GetSubmissionJobResponses;
    "fullResponse": GetSubmissionJobFullResponse;
};
