/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions } from "@accord/client";
import type { ErrorDto, SubmissionJobDto } from "../models.js";
export type GetSubmissionJobInput = {
    readonly "jobId": string;
};
export type GetSubmissionJobArguments = [
    input: {
        readonly "jobId": string;
    },
    options?: RequestOptions
];
export type GetSubmissionJobResponse = SubmissionJobDto;
export type GetSubmissionJobError = ErrorDto;
export type GetSubmissionJobResponses = {
    readonly "200": SubmissionJobDto;
    readonly "400": ErrorDto;
    readonly "401": ErrorDto;
    readonly "404": ErrorDto;
};
export type GetSubmissionJobFullResponse = HttpResult<200, SubmissionJobDto>;
export type GetSubmissionJobContract = {
    readonly "args": GetSubmissionJobArguments;
    readonly "input": GetSubmissionJobInput;
    readonly "response": GetSubmissionJobResponse;
    readonly "error": GetSubmissionJobError;
    readonly "responses": GetSubmissionJobResponses;
    readonly "fullResponse": GetSubmissionJobFullResponse;
};
