/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
import type { ErrorDto } from "./shared.js";
export type Currency = ("EUR" | "USD") & string;
export type TermsDto = {
    "closesAt": string;
    "currency": Currency;
    "minimumInvestment": string;
};
export type CreateOfferingDto = {
    "description"?: string | null;
    "name": string;
    "tags"?: string[];
    "terms": TermsDto;
};
export type OfferingStatus = ("draft" | "open" | "closed") & string;
export type OfferingDto = {
    "createdAt": string;
    "description"?: string | null;
    "id": string;
    "name": string;
    "status": OfferingStatus;
    "tags"?: string[];
    "terms": TermsDto;
};
export type OfferingDtoPage = {
    "items": OfferingDto[];
    "limit": number;
    "page": number;
    "total": number;
};
export type OfferingReportDto = {
    "currency": Currency;
    "offeringId": string;
    "subscriptionCount": number;
};
export type UpdateOfferingDto = {
    "description"?: string | null;
    "name"?: string;
    "tags"?: string[];
    "terms"?: TermsDto;
};
export type ListOfferingsInput = {
    "page"?: number;
    "limit"?: number;
    "status"?: OfferingStatus[];
};
export type ListOfferingsArguments = [
    input?: {
        "page"?: number;
        "limit"?: number;
        "status"?: OfferingStatus[];
    },
    options?: RequestOptions
];
export type ListOfferingsResponse = OfferingDtoPage;
export type ListOfferingsError = ErrorDto;
export type ListOfferingsResponses = {
    "200": OfferingDtoPage;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type ListOfferingsFullResponse = HttpResult<200, OfferingDtoPage>;
export type ListOfferingsContract = {
    "args": ListOfferingsArguments;
    "input": ListOfferingsInput;
    "response": ListOfferingsResponse;
    "error": ListOfferingsError;
    "responses": ListOfferingsResponses;
    "fullResponse": ListOfferingsFullResponse;
};
export type CreateOfferingInput = CreateOfferingDto;
export type CreateOfferingArguments = [
    input: CreateOfferingDto,
    options?: RequestOptionsFor<"application/json">
];
export type CreateOfferingResponse = OfferingDto;
export type CreateOfferingError = ErrorDto;
export type CreateOfferingResponses = {
    "201": OfferingDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type CreateOfferingFullResponse = HttpResult<201, OfferingDto>;
export type CreateOfferingContract = {
    "args": CreateOfferingArguments;
    "input": CreateOfferingInput;
    "response": CreateOfferingResponse;
    "error": CreateOfferingError;
    "responses": CreateOfferingResponses;
    "fullResponse": CreateOfferingFullResponse;
};
export type GetOfferingInput = {
    "offeringId": string;
};
export type GetOfferingArguments = [
    input: {
        "offeringId": string;
    },
    options?: RequestOptions
];
export type GetOfferingResponse = OfferingDto;
export type GetOfferingError = ErrorDto;
export type GetOfferingResponses = {
    "200": OfferingDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type GetOfferingFullResponse = HttpResult<200, OfferingDto>;
export type GetOfferingContract = {
    "args": GetOfferingArguments;
    "input": GetOfferingInput;
    "response": GetOfferingResponse;
    "error": GetOfferingError;
    "responses": GetOfferingResponses;
    "fullResponse": GetOfferingFullResponse;
};
export type UpdateOfferingInput = {
    "offeringId": string;
    "body"?: UpdateOfferingDto;
};
export type UpdateOfferingArguments = [
    input: {
        "offeringId": string;
        "body"?: UpdateOfferingDto;
    },
    options?: RequestOptionsFor<"application/json">
];
export type UpdateOfferingResponse = OfferingDto;
export type UpdateOfferingError = ErrorDto;
export type UpdateOfferingResponses = {
    "200": OfferingDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type UpdateOfferingFullResponse = HttpResult<200, OfferingDto>;
export type UpdateOfferingContract = {
    "args": UpdateOfferingArguments;
    "input": UpdateOfferingInput;
    "response": UpdateOfferingResponse;
    "error": UpdateOfferingError;
    "responses": UpdateOfferingResponses;
    "fullResponse": UpdateOfferingFullResponse;
};
export type DeleteOfferingInput = {
    "offeringId": string;
};
export type DeleteOfferingArguments = [
    input: {
        "offeringId": string;
    },
    options?: RequestOptions
];
export type DeleteOfferingResponse = undefined;
export type DeleteOfferingError = ErrorDto;
export type DeleteOfferingResponses = {
    "204": undefined;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
    "409": ErrorDto;
};
export type DeleteOfferingFullResponse = HttpResult<204, undefined>;
export type DeleteOfferingContract = {
    "args": DeleteOfferingArguments;
    "input": DeleteOfferingInput;
    "response": DeleteOfferingResponse;
    "error": DeleteOfferingError;
    "responses": DeleteOfferingResponses;
    "fullResponse": DeleteOfferingFullResponse;
};
export type ExportOfferingInput = {
    "offeringId": string;
};
export type ExportOfferingArguments = [
    input: {
        "offeringId": string;
    },
    options?: RequestOptions
];
export type ExportOfferingResponse = OfferingReportDto | string;
export type ExportOfferingError = ErrorDto;
export type ExportOfferingResponses = {
    "200": OfferingReportDto | string;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type ExportOfferingFullResponse = (HttpResult<200, OfferingReportDto> & {
    "mediaType": "application/json";
}) | (HttpResult<200, string> & {
    "mediaType": "text/csv";
});
export type ExportOfferingContract = {
    "args": ExportOfferingArguments;
    "input": ExportOfferingInput;
    "response": ExportOfferingResponse;
    "error": ExportOfferingError;
    "responses": ExportOfferingResponses;
    "fullResponse": ExportOfferingFullResponse;
};
