/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions } from "@accord/client";
import type {
    CreateOfferingDto,
    OfferingDto,
    OfferingDtoPage,
    OfferingReportDto,
    OfferingStatus,
    ProblemDto,
    UpdateOfferingDto
} from "../models.js";
export type ListOfferingsInput = {
    readonly "page"?: number;
    readonly "limit"?: number;
    readonly "status"?: ReadonlyArray<OfferingStatus>;
};
export type ListOfferingsArguments = [
    input?: {
        readonly "page"?: number;
        readonly "limit"?: number;
        readonly "status"?: ReadonlyArray<OfferingStatus>;
    },
    options?: RequestOptions
];
export type ListOfferingsResponse = OfferingDtoPage;
export type ListOfferingsError = ProblemDto;
export type ListOfferingsResponses = {
    readonly "200": OfferingDtoPage;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type ListOfferingsFullResponse = HttpResult<200, OfferingDtoPage>;
export type ListOfferingsContract = {
    readonly "args": ListOfferingsArguments;
    readonly "input": ListOfferingsInput;
    readonly "response": ListOfferingsResponse;
    readonly "error": ListOfferingsError;
    readonly "responses": ListOfferingsResponses;
    readonly "fullResponse": ListOfferingsFullResponse;
};
export type CreateOfferingInput = CreateOfferingDto;
export type CreateOfferingArguments = [
    input: CreateOfferingDto,
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type CreateOfferingResponse = OfferingDto;
export type CreateOfferingError = ProblemDto;
export type CreateOfferingResponses = {
    readonly "201": OfferingDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type CreateOfferingFullResponse = HttpResult<201, OfferingDto>;
export type CreateOfferingContract = {
    readonly "args": CreateOfferingArguments;
    readonly "input": CreateOfferingInput;
    readonly "response": CreateOfferingResponse;
    readonly "error": CreateOfferingError;
    readonly "responses": CreateOfferingResponses;
    readonly "fullResponse": CreateOfferingFullResponse;
};
export type GetOfferingInput = {
    readonly "offeringId": string;
};
export type GetOfferingArguments = [
    input: {
        readonly "offeringId": string;
    },
    options?: RequestOptions
];
export type GetOfferingResponse = OfferingDto;
export type GetOfferingError = ProblemDto;
export type GetOfferingResponses = {
    readonly "200": OfferingDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type GetOfferingFullResponse = HttpResult<200, OfferingDto>;
export type GetOfferingContract = {
    readonly "args": GetOfferingArguments;
    readonly "input": GetOfferingInput;
    readonly "response": GetOfferingResponse;
    readonly "error": GetOfferingError;
    readonly "responses": GetOfferingResponses;
    readonly "fullResponse": GetOfferingFullResponse;
};
export type UpdateOfferingInput = {
    readonly "offeringId": string;
    readonly "body"?: UpdateOfferingDto;
};
export type UpdateOfferingArguments = [
    input: {
        readonly "offeringId": string;
        readonly "body"?: UpdateOfferingDto;
    },
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type UpdateOfferingResponse = OfferingDto;
export type UpdateOfferingError = ProblemDto;
export type UpdateOfferingResponses = {
    readonly "200": OfferingDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type UpdateOfferingFullResponse = HttpResult<200, OfferingDto>;
export type UpdateOfferingContract = {
    readonly "args": UpdateOfferingArguments;
    readonly "input": UpdateOfferingInput;
    readonly "response": UpdateOfferingResponse;
    readonly "error": UpdateOfferingError;
    readonly "responses": UpdateOfferingResponses;
    readonly "fullResponse": UpdateOfferingFullResponse;
};
export type DeleteOfferingInput = {
    readonly "offeringId": string;
};
export type DeleteOfferingArguments = [
    input: {
        readonly "offeringId": string;
    },
    options?: RequestOptions
];
export type DeleteOfferingResponse = undefined;
export type DeleteOfferingError = ProblemDto;
export type DeleteOfferingResponses = {
    readonly "204": undefined;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
    readonly "409": ProblemDto;
};
export type DeleteOfferingFullResponse = HttpResult<204, undefined>;
export type DeleteOfferingContract = {
    readonly "args": DeleteOfferingArguments;
    readonly "input": DeleteOfferingInput;
    readonly "response": DeleteOfferingResponse;
    readonly "error": DeleteOfferingError;
    readonly "responses": DeleteOfferingResponses;
    readonly "fullResponse": DeleteOfferingFullResponse;
};
export type ExportOfferingInput = {
    readonly "offeringId": string;
};
export type ExportOfferingArguments = [
    input: {
        readonly "offeringId": string;
    },
    options?: RequestOptions
];
export type ExportOfferingResponse = OfferingReportDto | string;
export type ExportOfferingError = ProblemDto;
export type ExportOfferingResponses = {
    readonly "200": OfferingReportDto | string;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type ExportOfferingFullResponse = (HttpResult<200, OfferingReportDto> & {
    readonly "mediaType": "application/json";
}) | (HttpResult<200, string> & {
    readonly "mediaType": "text/csv";
});
export type ExportOfferingContract = {
    readonly "args": ExportOfferingArguments;
    readonly "input": ExportOfferingInput;
    readonly "response": ExportOfferingResponse;
    readonly "error": ExportOfferingError;
    readonly "responses": ExportOfferingResponses;
    readonly "fullResponse": ExportOfferingFullResponse;
};
