/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
export type ErrorDto = {
    readonly "code": string;
    readonly "details"?: ReadonlyArray<string>;
    readonly "message": string;
    readonly "statusCode": number;
};
