/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions } from "@accord/client";
import type {
    AcceptedSubmissionDto,
    AccordSimplify,
    CreateSubscriptionDto,
    ProblemDto,
    SubscriptionDto,
    SubscriptionDtoPage
} from "../models.js";
export type ListSubscriptionsInput = {
    readonly "offeringId": string;
    readonly "page"?: number;
    readonly "limit"?: number;
    readonly "investorId"?: string;
};
export type ListSubscriptionsArguments = [
    input: {
        readonly "offeringId": string;
        readonly "page"?: number;
        readonly "limit"?: number;
        readonly "investorId"?: string;
    },
    options?: RequestOptions
];
export type ListSubscriptionsResponse = SubscriptionDtoPage;
export type ListSubscriptionsError = ProblemDto;
export type ListSubscriptionsResponses = {
    readonly "200": SubscriptionDtoPage;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type ListSubscriptionsFullResponse = HttpResult<200, SubscriptionDtoPage>;
export type ListSubscriptionsContract = {
    readonly "args": ListSubscriptionsArguments;
    readonly "input": ListSubscriptionsInput;
    readonly "response": ListSubscriptionsResponse;
    readonly "error": ListSubscriptionsError;
    readonly "responses": ListSubscriptionsResponses;
    readonly "fullResponse": ListSubscriptionsFullResponse;
};
export type CreateSubscriptionInput = AccordSimplify<{
    readonly "offeringId": string;
} & CreateSubscriptionDto>;
export type CreateSubscriptionArguments = [
    input: AccordSimplify<{
        readonly "offeringId": string;
    } & CreateSubscriptionDto>,
    options?: Omit<RequestOptions, "headers"> & {
        readonly "headers"?: Readonly<Record<string, string>> & {
            readonly "content-type"?: "application/json" | `application/json;${string}`;
        };
    }
];
export type CreateSubscriptionResponse = SubscriptionDto;
export type CreateSubscriptionError = ProblemDto;
export type CreateSubscriptionResponses = {
    readonly "201": SubscriptionDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type CreateSubscriptionFullResponse = HttpResult<201, SubscriptionDto>;
export type CreateSubscriptionContract = {
    readonly "args": CreateSubscriptionArguments;
    readonly "input": CreateSubscriptionInput;
    readonly "response": CreateSubscriptionResponse;
    readonly "error": CreateSubscriptionError;
    readonly "responses": CreateSubscriptionResponses;
    readonly "fullResponse": CreateSubscriptionFullResponse;
};
export type GetSubscriptionInput = {
    readonly "subscriptionId": string;
};
export type GetSubscriptionArguments = [
    input: {
        readonly "subscriptionId": string;
    },
    options?: RequestOptions
];
export type GetSubscriptionResponse = SubscriptionDto;
export type GetSubscriptionError = ProblemDto;
export type GetSubscriptionResponses = {
    readonly "200": SubscriptionDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type GetSubscriptionFullResponse = HttpResult<200, SubscriptionDto>;
export type GetSubscriptionContract = {
    readonly "args": GetSubscriptionArguments;
    readonly "input": GetSubscriptionInput;
    readonly "response": GetSubscriptionResponse;
    readonly "error": GetSubscriptionError;
    readonly "responses": GetSubscriptionResponses;
    readonly "fullResponse": GetSubscriptionFullResponse;
};
export type SubmitSubscriptionInput = {
    readonly "subscriptionId": string;
    readonly "background"?: boolean;
};
export type SubmitSubscriptionArguments = [
    input: {
        readonly "subscriptionId": string;
        readonly "background"?: boolean;
    },
    options?: RequestOptions
];
export type SubmitSubscriptionResponse = {
    readonly "status": 200;
    readonly "data": SubscriptionDto;
} | {
    readonly "status": 202;
    readonly "data": AcceptedSubmissionDto;
};
export type SubmitSubscriptionError = ProblemDto;
export type SubmitSubscriptionResponses = {
    readonly "200": SubscriptionDto;
    readonly "202": AcceptedSubmissionDto;
    readonly "400": ProblemDto;
    readonly "401": ProblemDto;
    readonly "404": ProblemDto;
};
export type SubmitSubscriptionFullResponse = HttpResult<200, SubscriptionDto> | HttpResult<202, AcceptedSubmissionDto>;
export type SubmitSubscriptionContract = {
    readonly "args": SubmitSubscriptionArguments;
    readonly "input": SubmitSubscriptionInput;
    readonly "response": SubmitSubscriptionResponse;
    readonly "error": SubmitSubscriptionError;
    readonly "responses": SubmitSubscriptionResponses;
    readonly "fullResponse": SubmitSubscriptionFullResponse;
};
