/* Generated by @accord/codegen. Regenerate from the OpenAPI source. */
import type { HttpResult, RequestOptions, RequestOptionsFor } from "@accord/client";
import type { ErrorDto } from "./shared.js";
export type AcceptedSubmissionDto = {
    "jobId": string;
    "state": "accepted" & string;
};
export type CreateSubscriptionDto = {
    "amount": string;
    "investorId": string;
    "metadata"?: {
        [key: string]: string;
    };
};
export type SubscriptionStatus = ("draft" | "submitted") & string;
export type SubscriptionDto = {
    "amount": string;
    "id": string;
    "investorId": string;
    "metadata"?: {
        [key: string]: string;
    };
    "offeringId": string;
    "status": SubscriptionStatus;
    "submittedAt": string | null;
};
export type SubscriptionDtoPage = {
    "items": SubscriptionDto[];
    "limit": number;
    "page": number;
    "total": number;
};
export type ListSubscriptionsInput = {
    "offeringId": string;
    "page"?: number;
    "limit"?: number;
    "investorId"?: string;
};
export type ListSubscriptionsArguments = [
    input: {
        "offeringId": string;
        "page"?: number;
        "limit"?: number;
        "investorId"?: string;
    },
    options?: RequestOptions
];
export type ListSubscriptionsResponse = SubscriptionDtoPage;
export type ListSubscriptionsError = ErrorDto;
export type ListSubscriptionsResponses = {
    "200": SubscriptionDtoPage;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type ListSubscriptionsFullResponse = HttpResult<200, SubscriptionDtoPage>;
export type ListSubscriptionsContract = {
    "args": ListSubscriptionsArguments;
    "input": ListSubscriptionsInput;
    "response": ListSubscriptionsResponse;
    "error": ListSubscriptionsError;
    "responses": ListSubscriptionsResponses;
    "fullResponse": ListSubscriptionsFullResponse;
};
export type CreateSubscriptionInput = {
    "offeringId": string;
} & CreateSubscriptionDto;
export type CreateSubscriptionArguments = [
    input: {
        "offeringId": string;
    } & CreateSubscriptionDto,
    options?: RequestOptionsFor<"application/json">
];
export type CreateSubscriptionResponse = SubscriptionDto;
export type CreateSubscriptionError = ErrorDto;
export type CreateSubscriptionResponses = {
    "201": SubscriptionDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type CreateSubscriptionFullResponse = HttpResult<201, SubscriptionDto>;
export type CreateSubscriptionContract = {
    "args": CreateSubscriptionArguments;
    "input": CreateSubscriptionInput;
    "response": CreateSubscriptionResponse;
    "error": CreateSubscriptionError;
    "responses": CreateSubscriptionResponses;
    "fullResponse": CreateSubscriptionFullResponse;
};
export type GetSubscriptionInput = {
    "subscriptionId": string;
};
export type GetSubscriptionArguments = [
    input: {
        "subscriptionId": string;
    },
    options?: RequestOptions
];
export type GetSubscriptionResponse = SubscriptionDto;
export type GetSubscriptionError = ErrorDto;
export type GetSubscriptionResponses = {
    "200": SubscriptionDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type GetSubscriptionFullResponse = HttpResult<200, SubscriptionDto>;
export type GetSubscriptionContract = {
    "args": GetSubscriptionArguments;
    "input": GetSubscriptionInput;
    "response": GetSubscriptionResponse;
    "error": GetSubscriptionError;
    "responses": GetSubscriptionResponses;
    "fullResponse": GetSubscriptionFullResponse;
};
export type SubmitSubscriptionInput = {
    "subscriptionId": string;
    "background"?: boolean;
};
export type SubmitSubscriptionArguments = [
    input: {
        "subscriptionId": string;
        "background"?: boolean;
    },
    options?: RequestOptions
];
export type SubmitSubscriptionResponse = {
    "status": 200;
    "data": SubscriptionDto;
} | {
    "status": 202;
    "data": AcceptedSubmissionDto;
};
export type SubmitSubscriptionError = ErrorDto;
export type SubmitSubscriptionResponses = {
    "200": SubscriptionDto;
    "202": AcceptedSubmissionDto;
    "400": ErrorDto;
    "401": ErrorDto;
    "404": ErrorDto;
};
export type SubmitSubscriptionFullResponse = HttpResult<200, SubscriptionDto> | HttpResult<202, AcceptedSubmissionDto>;
export type SubmitSubscriptionContract = {
    "args": SubmitSubscriptionArguments;
    "input": SubmitSubscriptionInput;
    "response": SubmitSubscriptionResponse;
    "error": SubmitSubscriptionError;
    "responses": SubmitSubscriptionResponses;
    "fullResponse": SubmitSubscriptionFullResponse;
};
